{
  config,
  lib,
  ...
}:
let
  inherit (lib)
    types
    mkOption
    lists
    mkIf
    mkForce
    ;

  patchSet =
    with types;
    submodule {
      options.name = mkOption {
        type = str;
        description = "Name of the patchset to apply";
      };
      options.overrides = mkOption {
        type = attrs;
        default = { };
        description = "Structured Attrs Kernel config to override in the patchset";
      };
    };

  definePatch =
    setName: defaultPatch:
    (mkIf
      ((lists.findSingle (x: x.name == setName) { } { } config.boot.kernel.buildConfig.patchSets) != { })
      ({
        name = setName;
        patch = null;
        structuredExtraConfig = lib.mergeAttrsList [
          defaultPatch
          (lists.findSingle (x: x.name == setName) { } { } config.boot.kernel.buildConfig.patchSets).overrides
        ];
      })
    );
in
{
  options.boot.kernel.buildConfig = {
    patchSets = lib.mkOption {
      type = lib.types.listOf patchSet;
      description = "Patches to the Kernel Config to apply";
    };
  };

  config = {
    boot.kernelPatches = with lib.kernel; [
      # (definePatch "example" { })
      (definePatch "rm-unused-fs" {
        # Filesystems
        EROFS_FS = no; # containers use this?
        HFS = no; # Probably might encounter this
        HFSPLUS_FS = no;
        # PSTORE = module; # Set upstream
        SQUASHFS = module; # Generally useful
        JFS_FS = no;
        XFS_FS = no;
        GFS2_FS = no;
        NILFS2_FS = no;
        F2FS_FS = mkForce no;
        ORANGEFS_FS = no;
        ADFS_FS = no;
        AFFS_FS = no;
        BEFS_FS = no;
        BFS_FS = no;
        EFS_FS = no;
        CRAMFS = no;
        VXFS_FS = no;
        MINIX_FS = no;
        OMFS_FS = no;
        HPFS_FS = no;
        QNX4_FS = no;
        QNX6_FS = no;
        ROMFS_FS = no;
        UFS_FS = no;
        CEPH_FS = no;
        CODA_FS = no;
        AFS_FS = no;
        "9P_FS" = no;
        ROOT_NFS = no;

        CONFIG_QFMT_V1 = no;
      })
      (definePatch "rm-x86-platform-drivers" {
        # x86 Platform Drivers
        ACERHDF = no; # Acer Aspire One Temp Sensor/Fan
        ACER_WIRELESS = no;
        ACER_WMI = no;
        ACPI_CMPC = no; # Intel Classmate PC from early 20xx
        ADV_SWBUTTON = no; # Advantech software defined button
        AMILO_RFKILL = no; # Wifi for Fujitsu-Siemens Amilo Laptops
        APPLE_GMUX = no; # Gmux on Apple Laptops
        ASUS_ARMORY = no;
        ASUS_LAPTOP = no;
        ASUS_NB_WMI = no;
        ASUS_TF103C_DOCK = no;
        ASUS_WIRELESS = no;
        ASUS_WMI = no;
        AYANEO_EC = no;
        BARCO_P50_GPIO = no;
        COMPAL_LAPTOP = no;
        DASHARO_ACPI = no;
        DELL_LAPTOP = no;
        EEEPC_LAPTOP = no;
        EEEPC_WMI = no;
        FUJITSU_LAPTOP = no;
        FUJITSU_TABLET = no;
        GIGABYTE_WMI = no;
        GPD_POCKET_FAN = no;
        HUAWEI_WMI = no;
        IDEAPAD_LAPTOP = no;
        INSPUR_PLATFORM_PROFILE = no;
        LENOVO_WMI_CAMERA = no;
        LENOVO_WMI_HOTKEY_UTILITIES = no;
        LENOVO_WMI_GAMEZONE = no;
        LENOVO_WMI_TUNING = no;
        LG_LAPTOP = no;
        MERAKI_MX100 = no; # Cisco Meraki MX100 Appliance
        MEEGOPAD_ANX7428 = no;
        MSI_EC = no; # Userspace access for the MSI platform drivers we disabled
        MSI_LAPTOP = no;
        MSI_WMI = no;
        MSI_WMI_PLATFORM = no;
        OXP_EC = no; # OneXPlayer/AOKZOE embedded controller
        PANASONIC_LAPTOP = no;
        PCENGINES_APU2 = no;
        PORTWELL_EC = no;
        REDMI_WMI = no;
        SAMSUNG_GALAXYBOOK = no;
        SAMSUNG_LAPTOP = no;
        SAMSUNG_Q10 = no;
        SEL3350_PLATFORM = no;
        SIEMENS_SIMATIC_IPC = no;
        SILICOM_PLATFORM = no;
        SONY_LAPTOP = no;
        SYSTEM76_ACPI = no;
        THINKPAD_ACPI = no; # IBM/Lenovo Thinkpad Stuff
        THINKPAD_LMI = no; # Lenovo WMI system management driver
        TOPSTAR_LAPTOP = no;
        TOSHIBA_BT_RFKILL = no;
        TOSHIBA_HAPS = no; # Toshiba Hard Drive Protection Thing
        TOSHIBA_WMI = no;
        TUXEDO_NB04_WMI_AB = no;
        WINMATE_FM07_KEYS = no;
        WIRELESS_HOTKEY = no; # Wireless button on AMD/HP/Xiaomi Laptops
        XIAOMI_WMI = no;
        X86_ANDROID_TABLETS = no;
        X86_PLATFORM_DRIVERS_DELL = mkForce no;
        X86_PLATFORM_DRIVERS_HP = mkForce no;
        X86_PLATFORM_DRIVERS_UNIWILL = no;
        YOGABOOK = no;
        YT2_1380 = no; # Lenovo Yoga Tablet 2 1380 fast charging protocol
      })
      (definePatch "rm-unused-driver-categories" {
        ACCESSIBILITY = mkForce no;
        BCMA = no; # Broadcom Specific AMBA
        CHROME_PLATFORMS = mkForce no;
        COMEDI = no; # Scientific Data Collection Hardware
        FIREWIRE = no;
        FIREWIRE_NOSY = no; # Firewire Probe Thing?
        FPGA = no;
        FSI = no;
        FUSION = mkForce no; # Fusion Message Passing Technology
        GOOGLE_FIRMWARE = lib.mkForce no;
        GOLDFISH = no; # Goldfish Virtual Platform
        GPIB = no; # General Purpose Interface Bus
        GREYBUS = no;
        HAMRADIO = lib.mkForce no; # Ham Radio Support
        HSI = no; # High-spped synchronous Serial Interface
        HSI_BOARDINFO = no;
        HTE = no;
        IIO = no; # Industrial I/O
        INFINIBAND = mkForce no; # Before ethernet was fast or something
        INTERCONNECT = no;
        IPACK_BUS = no; # IndustryPack Bus
        LIRC = mkForce no;
        MCB = no;
        MELLANOX_PLATFORM = no; # Mellanox Drivers
        MEMSTICK = no; # Sony Memory Stick
        MOST = no; # Media Oriented Systems Transport
        NTB = no;
        # OF = mkForce no; # Open Firmware/Device Trees - We use ACPI here
        PARPORT = no; # Parallel Port - which we don't have
        PPDEV = no;
        PCCARD = no; # Predecessor to PCMCIA
        # PECI = no;
        # PPS = no; # Pulse Per Second (GPS-related)
        RAS = mkForce no;
        REGULATOR = mkForce no; # Generic Voltage/Current Regulators - done via ACPI?
        REMOTEPROC = no;
        RESET_CONTROLLER = no; # GPIO and similar Reset Controllers
        # SSB = no; # Sonics Silicon Backplane - Why dependency???
        SIOX = no;
        SLIMBUS = no;
        # W1 = no;

        STAGING = mkForce no;
      })
      (definePatch "rm-unused-individual-drivers" {
        # Misc Drivers (Individual)
        AD525X_DPOT = no; # Analog Devices Digital Potentiometers
        ALTERA_STAPL = no; # Altera Firmware Download thing
        APDS9802ALS = no; # Ambient Light Sensor
        BCM_VK = no; # Broadcom VK Accelerators
        C2PORT = no; # Silicon Labs C2 Port
        # CB710_CORE = no; # PCI ENE CB710/720 Flash Memory card reader
        DS1682 = no; # Elapsed Time Recorder with Alarm - Whatever that is
        DUMMY_IRQ = no;
        DW_XDATA_PCIE = no; # Synopsys DesignWare PCIe traffic generator IP
        GENWQE = no; # IBM GenWQE Accelerators
        HI6421V600_IRQ = no; # IRQ handling for the thing on Kirin chipsets
        HISI_HIKEY_USB = no; # USB GPIO Hub on HiSilicon Hikey 960/70
        HMC6352 = no; # A compass? huh
        HP_ILO = no; # Used in HP ProLiant servers
        IBM_ASM = no; # IBM RSA service processor
        ICS932S401 = no; # A clock control chip
        ISL29003 = no; # Ambient Light Sensor
        ISL29020 = no; # Ambient Light Sensor
        KEBA_CP500 = no; # KEBA CP500 System FPGA
        LATTICE_ECP3_CONFIG = no; # Programmer for Lattice ECP3 FPGA
        MISC_ALCOR_PCI = no; # Alcor Micro PCI express card readers
        MISC_RTSX_PCI = no; # Realtek PCI express card readers
        MUX_ADG792A = no; # Multiplexer
        NSM = no; # Nitro Security Module - AWS EC2
        PCI_ENDPOINT_TEST = no;
        PHANTOM = no; # Sensable PHANToM
        SENSORS_APDS990X = no; # Ambient Light Sensor + Proximity Sensor
        SENSORS_BH1770 = no; # Ambient Light Sensor + Proximity Sensor
        SENSORS_LIS3_I2C = no; # Accelerometer
        SENSORS_LIS3LV02D = no; # Accelerometer - but 3 axis digital
        SENSORS_TSL2550 = no; # Ambient Light Sensor
        SMPRO_ERRMON = no; # Ampere Computing SMPro Error Monitor
        SMPRO_MISC = no; # Ampere Computing SMPro Misc Drivers
        TI_FPC202 = no; # Texas Instruments FPC202 Dual Port Controller
        TPS6594_ESM = no; # TI TPS6594 PMIC Error Signal Monitor
        TPS6594_PFSM = no; # TI TPS6594 PMIC Preconfigurable Finite State Machine
        VCPU_STALL_DETECTOR = no;
        VMWARE_BALLOON = no; # VMWare Memory Balloon
        VMWARE_VMCI = no; # VMWare Virtual Machine Communication Interface
        XILINX_SDFEC = no; # Xilinx Soft Decision Forward Error Correction Driver
      })
      (definePatch "rm-net-top-level" {
        # Top-level categories under Networking Drivers
        # and dependencies that might enable them

        HAMRADIO = no;
        CAN = no;
        AF_RXRPC = no;
        MCTP = no;
        NET_9P = no;
        CAIF = no;
        NFC = no;

        ARCNET = no;
        ATM_DRIVERs = no;

        B53 = no;
        FDDI = no; # Fiber Distributed Data Interface
        HIPPI = no; # High Performance Parallel Interface
        PPP = no;
        SLIP = no;
        USB_NET_DRIVERS = no;
        WWAN = no;
        VMXNET3 = no;
        USB4_NET = no;
        NETDEVSIM = no;
        ISDN = no;
        PLIP = no; # Parallel Line Internet Protocol
        WAN = mkForce no;
        HYPERV_NET = no;
        NET_FC = mkForce no;
        FUJITSU_ES = no; # Fujitsu Extended Socket Network Device
        INFINIBAND = no;

        CEPH_LIB = no;
        BLK_DEV_RBD = no; # Rados Block Device - Selects CEPH_LIB

        MLX5_CORE = no;
      })
      (definePatch "rm-net-dsa-drivers" {
        B53 = no;
        NET_DSA_BCM_SF2 = no;
        NET_DSA_LOOP = no;
        NET_DSA_HIRSCHMANN_HELLCREEK = no;
        NET_DSA_LANTIQ_GSWIP = no;
        NET_DSA_MT7530 = no;
        NET_DSA_MV88E6060 = no;
        NET_DSA_MICROCHIP_KSZ_COMMON = no;
        NET_DSA_MV88E6XXX = no;
        NET_DSA_AR9331 = no;
        NET_DSA_QCA8K = no;
        NET_DSA_SJA1105 = no;
        NET_DSA_XRS700X = no;
        NET_DSA_XRS700X_MDIO = no;
        NET_DSA_XRS700X_I2C = no;
        NET_DSA_REALTEK = no;
        NET_DSA_KS8995 = no;
        NET_DSA_VITESSE_VSC73XX = no;
        NET_DSA_VITESSE_VSC73XX_PLATFORM = no;
        NET_DSA_VITESSE_VSC73XX_SPI = no;
      })
      (definePatch "rm-net-ethernet-drivers" {
        NET_VENDOR_3COM = no;
        NET_VENDOR_ADAPTEC = no;
        NET_VENDOR_ADI = no;
        NET_VENDOR_AGERE = no;
        NET_VENDOR_ALACRITECH = no;
        NET_VENDOR_ALTEON = no;
        ALTERA_TSE = no; # Altera Triple Speed Ethernet MAC
        NET_VENDOR_AMAZON = no;
        NET_VENDOR_AMD = no;
        NET_VENDOR_AQUANTIA = no;
        NET_VENDOR_ARC = no;
        NET_VENDOR_ASIX = no;
        NET_VENDOR_ATHEROS = no;
        NET_VENDOR_BROADCOM = no;
        NET_VENDOR_CADENCE = no;
        NET_VENDOR_CAVIUM = no;
        NET_VENDOR_CORTINA = no;
        NET_VENDOR_DAVICOM = no;
        NET_VENDOR_DEC = no;
        DNET = no; # Dave Ethernet
        NET_VENDOR_ENGLEDER = no;
        ETHOC = no; # OpenCores 10/100 Mbps Ethernet MAC
        NET_VENDOR_EZCHIP = no;
        FEALNX = no; # Myson MTD-8xx PCI Ethernet
        NET_VENDOR_FREESCALE = no;
        NET_VENDOR_FUNGIBLE = no;
        NET_VENDOR_GOOGLE = no;
        NET_VENDOR_HISILICON = no;
        NET_VENDOR_HUAWEI = no;
        NET_VENDOR_I825XX = no;
        JME = no; # JMicron PCI-E Gigabit Ethernet
        NET_VENDOR_LITEX = no;
        NET_VENDOR_MARVELL = no;
        NET_VENDOR_META = no;
        NET_VENDOR_MELLANOX = no;
        NET_VENDOR_MICREL = no;
        NET_VENDOR_MICROCHIP = no;
        NET_VENDOR_MICROSEMI = no;
        NET_VENDOR_MICROSOFT = no;
        NET_VENDOR_MYRI = no;
        NET_VENDOR_NI = no;
        NET_VENDOR_NATSEMI = no;
        NET_VENDOR_NETRONOME = no;
        NXP_ENETC4 = no;
        NET_VENDOR_8390 = no;
        NET_VENDOR_NVIDIA = no;
        NET_VENDOR_OKI = no;
        NET_VENDOR_PACKET_ENGINES = no;
        NET_VENDOR_PENSANDO = no;
        NET_VENDOR_QLOGIC = no;
        NET_VENDOR_BROCADE = no;
        NET_VENDOR_QUALCOMM = no;
        NET_VENDOR_RDC = no;
        NET_VENDOR_REALTEK = no;
        NET_VENDOR_RENESAS = no;
        NET_VENDOR_ROCKER = no;
        NET_VENDOR_SAMSUNG = no;
        NET_VENDOR_SEEQ = no;
        NET_VENDOR_SILAN = no;
        NET_VENDOR_SIS = no;
        NET_VENDOR_SOLARFLARE = no;
        NET_VENDOR_SMSC = no;
        NET_VENDOR_SOCIONEXT = no;
        NET_VENDOR_STMICRO = no;
        NET_VENDOR_SUN = no;
        NET_VENDOR_SYNOPSYS = no;
        NET_VENDOR_TEHUTI = no;
        NET_VENDOR_TI = no;
        NET_VENDOR_VERTEXCOM = no;
        NET_VENDOR_VIA = no;
        NET_VENDOR_WANGXUN = no;
        NET_VENDOR_WIZNET = no;
        NET_VENDOR_XILINX = no;
      })
      (definePatch "rm-net-wlan-drivers" {
        WLAN_VENDOR_ADMTEK = no;
        WLAN_VENDOR_ATH = no;
        WLAN_VENDOR_ATMEL = no;
        WLAN_VENDOR_BROADCOM = no;
        WLAN_VENDOR_INTERSIL = no;
        WLAN_VENDOR_INTEL = no;
        WLAN_VENDOR_MARVELL = no;
        WLAN_VENDOR_MEDIATEK = no;
        WLAN_VENDOR_MICROCHIP = no;
        WLAN_VENDOR_PURELIFI = no;
        WLAN_VENDOR_RALINK = no;
        WLAN_VENDOR_REALTEK = no;
        WLAN_VENDOR_RSI = no;
        WLAN_VENDOR_SILABS = no;
        WLAN_VENDOR_ST = no;
        WLAN_VENDOR_TI = no;
        WLAN_VENDOR_ZYDAS = no;
        WLAN_VENDOR_QUANTENNA = no;
        IPW2100 = no;
        IPW2200 = no;
        IWL4965 = no;
        IWL3945 = no;
        RTL8723BS = no;
      })
      (definePatch "rm-net-ethernet-specific-phy" {
        AS21XXX_PHY = no;
        AIR_EN8811H_PHY = no;
        AMD_PHY = no;
        ADIN_PHY = no;
        ADIN1100_PHY = no;
        AQUANTIA_PHY = no;
        AX88796B_PHY = no;
        BROADCOM_PHY = no;
        BCM54140_PHY = no;
        BCM7XXX_PHY = no;
        BCM84881_PHY = no;
        BCM87XX_PHY = no;
        BCM_NET_PHYLIB = no;
        BCM_NET_PHYPTP = no;
        CICADA_PHY = no;
        CORTINA_PHY = no;
        DAVICOM_PHY = no;
        ICPLUS_PHY = no;
        LXT_PHY = no;
        INTEL_XWAY_PHY = no;
        LSI_ET1011C_PHY = no;
        MARVELL_PHY = no;
        MARVELL_10G_PHY = no;
        MARVELL_88Q2XXX_PHY = no;
        MARVELL_88X2222_PHY = no;
        MAXLINEAR_GPHY = no;
        MAXLINEAR_86110_PHY = no;
        MEDIATEK_GE_PHY = no;
        MICREL_PHY = no;
        MICROCHIP_T1S_PHY = no;
        MICROCHIP_PHY = no;
        MICROCHIP_T1_PHY = no;
        MICROSEMI_PHY = no;
        MOTORCOMM_PHY = no;
        NATIONAL_PHY = no;
        NXP_CBTX_PHY = no;
        NXP_C45_TJA11XX_PHY = no;
        NXP_TJA11XX_PHY = no;
        NCN26000_PHY = no;
        AT803X_PHY = no;
        QCA83XX_PHY = no;
        QCA808X_PHY = no;
        QCA807X_PHY = no;
        QSEMI_PHY = no;
        REALTEK_PHY = no;
        RENESAS_PHY = no;
        ROCKCHIP_PHY = no;
        SMSC_PHY = no;
        STE10XP = no;
        TERANETICS_PHY = no;
        DP83822_PHY = no;
        DP83TC811_PHY = no;
        DP83848_PHY = no;
        DP83867_PHY = no;
        DP83869_PHY = no;
        DP83TD510_PHY = no;
        DP83TG720_PHY = no;
        VITESSE_PHY = no;
        XILINX_GMII2RGMII = no;
        PSE_CONTROLLER = no;
        MDIO_HISI_FEMAC = no;
        MDIO_MVUSB = no;
        MDIO_MSCC_MIIM = no;
        MDIO_OCTEON = no;
        MDIO_IPQ4019 = no;
        MDIO_IPQ8064 = no;
        MDIO_THUNDER = no;
      })
      (definePatch "rm-parallel-ata" {
        # Parallel ATA
        # PATA_TIMINGS = no; # Set Incorrectly
        PATA_ACPI = no;
        PATA_LEGACY = no;
        PATA_ALI = no;
        PATA_AMD = no;
        PATA_ARTOP = no;
        PATA_ATIIXP = no;
        PATA_ATP867X = no;
        PATA_CMD64X = no;
        PATA_CYPRESS = no;
        PATA_EFAR = no;
        PATA_HPT366 = no;
        PATA_HPT37X = no;
        PATA_HPT3X2N = no;
        PATA_HPT3X3 = no;
        # PATA_HPT3X3_DMA is not set
        PATA_IT8213 = no;
        PATA_IT821X = no;
        PATA_JMICRON = no;
        # PATA_MARVELL = no;
        PATA_NETCELL = no;
        PATA_NINJA32 = no;
        PATA_NS87415 = no;
        PATA_OLDPIIX = no;
        PATA_OPTIDMA = no;
        PATA_PDC2027X = no;
        PATA_PDC_OLD = no;
        PATA_RADISYS = no;
        PATA_RDC = no;
        PATA_SCH = no;
        PATA_SERVERWORKS = no;
        PATA_SIL680 = no;
        # PATA_SIS = no; # Set Incorrectly
        PATA_TOSHIBA = no;
        PATA_TRIFLEX = no;
        PATA_VIA = no;
        PATA_WINBOND = no;
        PATA_CMD640_PCI = no;
        PATA_MPIIX = no;
        PATA_NS87410 = no;
        PATA_OPTI = no;
        PATA_RZ1000 = no;
        SBP_TARGET = no;
        PPDEV = no;
      })
      (definePatch "rm-unused-graphics" {
        # Graphics
        AGP = mkForce no;
        DRM_AMDGPU = no;
        DRM_AST = no;
        DRM_ETNAVIV = no;
        DRM_GMA500 = mkForce no;
        DRM_GUD = no;
        DRM_HISI_HIBMC = no;
        DRM_I915 = yes; # We do want intel graphics
        DRM_MGAG200 = no;
        DRM_NOUVEAU = no; # Using stupid nvidia proprietary drivers
        DRM_PANEL_RASPBERRYPI_TOUCHSCREEN = no;
        DRM_QXL = no;
        DRM_RADEON = no;
        DRM_ST7571 = no;
        DRM_SSD130x = no;
        DRM_APPLETBDRM = no;
        DRM_BOCHS = no;
        DRM_CIRRUS_QEMU = no;
        DRM_GM12U320 = no;
        DRM_VBOXVIDEO = no;
        DRM_VGEM = no;
        DRM_VMWGFX = no;
        DRM_XE = no;
        FB = mkForce no; # Replaced by DRM/KMS
      })
      (definePatch "rm-hid-specific-keyboard" {
        # KEYBOARD_ATKBD = no; - Needed to use any laptop keyboard
        # HID/Input Drivers
        MACINTOSH_DRIVERS = no;
        MAC_EMUMOUSEBTN = no;
        KEYBOARD_ADP5585 = no;
        KEYBOARD_ADP5588 = no;
        KEYBOARD_APPLESPI = mkForce no;
        KEYBOARD_QT1050 = no;
        KEYBOARD_QT1070 = no;
        KEYBOARD_QT2160 = no;
        KEYBOARD_DLINK_DIR685 = no;
        KEYBOARD_LKKBD = no;
        KEYBOARD_TCA8418 = no;
        KEYBOARD_LM8323 = no;
        KEYBOARD_LM8333 = no;
        KEYBOARD_MAX7359 = no;
        KEYBOARD_MAX7360 = no;
        KEYBOARD_MPR121 = no;
        KEYBOARD_NEWTON = no;
        KEYBOARD_OPENCORES = no;
        KEYBOARD_PINEPHONE = no;
        KEYBOARD_SAMSUNG = no;
        KEYBOARD_STOWAWAY = no;
        KEYBOARD_SUNKBD = no;
        KEYBOARD_STMPE = no;
        KEYBOARD_IQS62X = no;
        KEYBOARD_OMAP4 = no;
        KEYBOARD_TM2_TOUCHKEY = no;
        KEYBOARD_XTKBD = no;
        KEYBOARD_CAP11XX = no;
        KEYBOARD_BCM = no;
        KEYBOARD_MTK_PMIC = no;
        KEYBOARD_CYPRESS_SF = no;
      })
      (definePatch "rm-hid-specific-mouse" {
        MOUSE_PS2 = no;

        MOUSE_APPLETOUCH = no;
        MOUSE_BCM5974 = no;
        MOUSE_CYAPA = no;
        MOUSE_ELAN_I2C = no;
        MOUSE_VSXXXAA = no;
      })
      (definePatch "rm-hid-misc" {
        JOYSTICK_DB9 = no;
        JOYSTICK_GAMECON = no;
        JOYSTICK_TURBOGRAFX = no;
        JOYSTICK_WALKERA0701 = no;

        INPUT_TABLET = no;
        INPUT_TOUCHSCREEN = no;
        INPUT_MISC = no;
      })
      (definePatch "rm-pcie-top-level" {
        PCI_SW_SWITCHTEC = no;
        PCI_PWRCTRL_SLOT = no;
        CXL_BUS = no;
        PCCARD = no;
        RAPIDIO = no;
        PC104 = no;

        MCHP_LAN966X_PCI = no; # Microchip LAN966X_PCIE
        GP_PCI1XXXX = no; # Microchip PCI1XXXX PCIe to GPIO Expander + OTP/EEPROM Manager

        DWC_PCIE_PMU = no; # Synopsys DesignWare PCIe PMU on Alibaba HW

        PCIE_CADENCE_PLAT_HOST = no;
        PCIE_MICROCHIP_HOST = no;

        CB710_CORE = no; # ENE CB710 PCI Flash Memory Reader
        CB710_MMC = no; # ENE CB710 PCI Flash Memory Reader
        MMC_CB710 = no;

        APPLICOM = no; # Applicom intelligent fieldbus card
        XILLYBUS = no;
        XILLYUSB = no;
      })
      (definePatch "rm-scsi-top-level" {
        CHR_DEV_ST = no; # SCSI Tape Drives
        BLK_DEV_SR = no; # SCSI CD-ROM
        CHR_DEV_SCH = no; # SCSI Media Changer (like in jukeboxes)

        SCSI_SAS_ATTRS = no; # SCSI SAS Transport Attributes
        SCSI_SAS_LIBSAS = no;
        SCSI_PPA = no; # IOMEGA Parallel Port - older
        SCSI_IMM = no; # IOMEGA Parallel Port - newer

      })
      (definePatch "rm-media-tuners" {
        # TV tuners and things like what linux supported all this?
        RC_CORE = mkForce no;
        VIDEO_TVEEPROM = no;
        VIDEO_TUNER = no;
        MEDIA_CONTROLLER_DVB = no;
        DVB_DYNAMIC_MINORS = mkForce no;
        VIDEO_USBTV = no;
        RADIO_ADAPTERS = no;
        MEDIA_ANALOG_TV_SUPPORT = mkForce no;
        MEDIA_CEC_SUPPORT = mkForce no;
        MEDIA_COMMON_OPTIONS = no;
        MEDIA_DIGITAL_TV_SUPPORT = mkForce no;
        MEDIA_PLATFORM_DRIVERS = no;
        MEDIA_PCI_SUPPORT = mkForce no;
        MEDIA_RADIO_SUPPORT = no;
        MEDIA_SDR_SUPPORT = no;
        MEDIA_TEST_SUPPORT = no;
        MEDIA_ATTACH = mkForce no;
        CYPRESS_FIRMWARE = no;
        USB_GSPCA = no;
        USB_AIRSPY = no;
        USB_HACKRF = no;
        USB_MSI2500 = no;
        SMS_SIANO_MDTV = no;
        MEDIA_TUNER = no;
        TOUCHSCREEN_SUR40 = no;
        DVB_AS102 = no;
        DVB_B2C2_FLEXCOP_USB = no;
        # DVB_B2C2_FLEXCOP_USB_DEBUG is not set
        DVB_USB_V2 = no;
        SMS_USB_DRV = no;
        DVB_TTUSB_BUDGET = no;
        DVB_TTUSB_DEC = no;
        DVB_B2C2_FLEXCOP = no;
        MEDIA_TUNER_E4000 = no;
        MEDIA_TUNER_FC0011 = no;
        MEDIA_TUNER_FC0012 = no;
        MEDIA_TUNER_FC0013 = no;
        MEDIA_TUNER_FC2580 = no;
        MEDIA_TUNER_IT913X = no;
        MEDIA_TUNER_M88RS6000T = no;
        MEDIA_TUNER_MAX2165 = no;
        MEDIA_TUNER_MC44S803 = no;
        MEDIA_TUNER_MSI001 = no;
        MEDIA_TUNER_MT2060 = no;
        MEDIA_TUNER_MT2063 = no;
        MEDIA_TUNER_MT20XX = no;
        MEDIA_TUNER_MT2131 = no;
        MEDIA_TUNER_MT2266 = no;
        MEDIA_TUNER_MXL301RF = no;
        MEDIA_TUNER_MXL5005S = no;
        MEDIA_TUNER_MXL5007T = no;
        MEDIA_TUNER_QM1D1B0004 = no;
        MEDIA_TUNER_QM1D1C0042 = no;
        MEDIA_TUNER_QT1010 = no;
        MEDIA_TUNER_R820T = no;
        MEDIA_TUNER_SI2157 = no;
        MEDIA_TUNER_SIMPLE = no;
        MEDIA_TUNER_TDA18212 = no;
        MEDIA_TUNER_TDA18218 = no;
        MEDIA_TUNER_TDA18250 = no;
        MEDIA_TUNER_TDA18271 = no;
        MEDIA_TUNER_TDA827X = no;
        MEDIA_TUNER_TDA8290 = no;
        MEDIA_TUNER_TDA9887 = no;
        MEDIA_TUNER_TEA5761 = no;
        MEDIA_TUNER_TEA5767 = no;
        MEDIA_TUNER_TUA9001 = no;
        MEDIA_TUNER_XC2028 = no;
        MEDIA_TUNER_XC4000 = no;
        MEDIA_TUNER_XC5000 = no;
        DVB_M88DS3103 = no;
        DVB_MXL5XX = no;
        DVB_STB0899 = no;
        DVB_STB6100 = no;
        DVB_STV090x = no;
        DVB_STV0910 = no;
        DVB_STV6110x = no;
        DVB_STV6111 = no;
        DVB_DRXK = no;
        DVB_MN88472 = no;
        DVB_MN88473 = no;
        DVB_SI2165 = no;
        DVB_TDA18271C2DD = no;
        DVB_CX24110 = no;
        DVB_CX24116 = no;
        DVB_CX24117 = no;
        DVB_CX24120 = no;
        DVB_CX24123 = no;
        DVB_DS3000 = no;
        DVB_MB86A16 = no;
        DVB_MT312 = no;
        DVB_S5H1420 = no;
        DVB_SI21XX = no;
        DVB_STB6000 = no;
        DVB_STV0288 = no;
        DVB_STV0299 = no;
        DVB_STV0900 = no;
        DVB_STV6110 = no;
        DVB_TDA10071 = no;
        DVB_TDA10086 = no;
        DVB_TDA8083 = no;
        DVB_TDA8261 = no;
        DVB_TDA826X = no;
        DVB_TS2020 = no;
        DVB_TUA6100 = no;
        DVB_TUNER_CX24113 = no;
        DVB_TUNER_ITD1000 = no;
        DVB_VES1X93 = no;
        DVB_ZL10036 = no;
        DVB_ZL10039 = no;
        DVB_AF9013 = no;
        DVB_AS102_FE = no;
        DVB_CX22700 = no;
        DVB_CX22702 = no;
        DVB_CXD2820R = no;
        DVB_CXD2841ER = no;
        DVB_DIB3000MB = no;
        DVB_DIB3000MC = no;
        DVB_DIB7000M = no;
        DVB_DIB7000P = no;
        DVB_DIB9000 = no;
        DVB_DRXD = no;
        DVB_EC100 = no;
        DVB_L64781 = no;
        DVB_MT352 = no;
        DVB_NXT6000 = no;
        DVB_RTL2830 = no;
        DVB_RTL2832 = no;
        DVB_RTL2832_SDR = no;
        DVB_S5H1432 = no;
        DVB_SI2168 = no;
        DVB_SP887X = no;
        DVB_STV0367 = no;
        DVB_TDA10048 = no;
        DVB_TDA1004X = no;
        DVB_ZD1301_DEMOD = no;
        DVB_ZL10353 = no;
        DVB_CXD2880 = no;
        DVB_STV0297 = no;
        DVB_TDA10021 = no;
        DVB_TDA10023 = no;
        DVB_VES1820 = no;
        DVB_AU8522 = no;
        DVB_AU8522_DTV = no;
        DVB_AU8522_V4L = no;
        DVB_BCM3510 = no;
        DVB_LG2160 = no;
        DVB_LGDT3305 = no;
        DVB_LGDT3306A = no;
        DVB_LGDT330X = no;
        DVB_MXL692 = no;
        DVB_NXT200X = no;
        DVB_OR51132 = no;
        DVB_OR51211 = no;
        DVB_S5H1409 = no;
        DVB_S5H1411 = no;
        DVB_DIB8000 = no;
        DVB_MB86A20S = no;
        DVB_S921 = no;
        DVB_MN88443X = no;
        DVB_TC90522 = no;
        DVB_PLL = no;
        DVB_TUNER_DIB0070 = no;
        DVB_TUNER_DIB0090 = no;
        DVB_A8293 = no;
        DVB_AF9033 = no;
        DVB_ASCOT2E = no;
        DVB_ATBM8830 = no;
        DVB_HELENE = no;
        DVB_HORUS3A = no;
        DVB_ISL6405 = no;
        DVB_ISL6421 = no;
        DVB_ISL6423 = no;
        DVB_IX2505V = no;
        DVB_LGS8GL5 = no;
        DVB_LGS8GXX = no;
        DVB_LNBH25 = no;
        DVB_LNBH29 = no;
        DVB_LNBP21 = no;
        DVB_LNBP22 = no;
        DVB_M88RS2000 = no;
        DVB_TDA665x = no;
        DVB_DRX39XYJ = no;
        DVB_CXD2099 = no;
        DVB_SP2 = no;
        DVB_DUMMY_FE = no;
        VIDEO_GO7007 = no;
        VIDEO_HDPVR = no;
        VIDEO_PVRUSB2 = no;
        VIDEO_STK1160 = no;
        VIDEO_AU0828 = no;
        VIDEO_CX231XX = no;
      })
      (definePatch "rm-dallas-1wire" {
        W1_MASTER_AMD_AXI = no;
        W1_MASTER_MATROX = no;
        W1_MASTER_DS2490 = no;
        W1_MASTER_DS2482 = no;
        W1_MASTER_SGI = no;

        W1_SLAVE_DS2405 = no;
        W1_SLAVE_DS2408 = no;
        W1_SLAVE_DS2413 = no;
        W1_SLAVE_DS2406 = no;
        W1_SLAVE_DS2423 = no;
        W1_SLAVE_DS2805 = no;
        W1_SLAVE_DS2430 = no;
        W1_SLAVE_DS2431 = no;
        W1_SLAVE_DS2433 = no;
        W1_SLAVE_DS2438 = no;
        W1_SLAVE_DS250X = no;
        W1_SLAVE_DS28E04 = no;
      })
      (definePatch "rm-watchdog-timers" {

        LENOVO_SE10_WDT = no;
        LENOVO_SE30_WDT = no;
        ZIIRAVE_WATCHDOG = no;
        MAX63XX_WATCHDOG = no;
        ACQUIRE_WDT = no;
        ADVANTECH_WDT = no;
        ADVANTECH_EC_WDT = no;
        ALIM1535_WDT = no;
        ALIM7101_WDT = no;
        EBC_C384_WDT = no;
        EXAR_WDT = no;
        F71808E_WDT = no;
        SP5100_TCO = no;
        SBC_FITPC2_WATCHDOG = no;
        EUROTECH_WDT = no;
        IB700_WDT = no;
        IBMASR = no;
        WAFER_WDT = no;
        I6300ESB_WDT = no;
        IE6XX_WDT = no;
        ITCO_WDT = no;
        IT8712F_WDT = no;
        IT87_WDT = no;
        HP_WATCHDOG = no;
        HPWDT_NMI_DECODING = no;
        SC1200_WDT = no;
        PC87413_WDT = no;
        NV_TCO = no;
        "60XX_WDT" = no;
        SMSC_SCH311X_WDT = no;
        SMSC37B787_WDT = no;
        TQMX86_WDT = no;
        VIA_WDT = no;
        W83627HF_WDT = no;
        W83877F_WDT = no;
        W83977F_WDT = no;
        MACHZ_WDT = no;
        SBC_EPX_C3_WATCHDOG = no;
        MEN_A21_WDT = no;

        PCIPCWATCHDOG = no;
        WDTPCI = no;

        USBPCWATCHDOG = no;
      })
      (definePatch "rm-multifunction-device" {
        MFD_ADP5585 = no;
        MFD_ACT8945A = no;
        MFD_AS3711 = no;
        MFD_SMPRO = no;
        MFD_AS3722 = no;
        PMIC_ADP5520 = no;
        MFD_AAT2870_CORE = no;
        MFD_ATMEL_FLEXCOM = no;
        MFD_ATMEL_HLCDC = no;
        CONFIG_MFD_BCM590XX = no;
        MFD_BD9571MWV = no;
        MFD_AXP20X_I2C = no;
        MFD_CGBC = no;
        MFD_CS40L50_I2C = no;
        MFD_CS40L50_SPI = no;
        MFD_CS42L43_I2C = no;
        MFD_LOCHNAGAR = no;
        MFD_MADERA = no;
        PMIC_DA903X = no;
        MFD_DA9052_SPI = no;
        MFD_DA9052_I2C = no;
        MFD_DA9055 = no;
        MFD_DA9062 = no;
        MFD_DA9063 = no;
        MFD_DA9150 = no;
        MFD_DLN2 = no;
        MFD_GATEWORKS_GSC = no;
        MFD_MC13XXX_SPI = no;
        MFD_MC13XXX_I2C = no;
        MFD_MP2629 = no;
        MFD_HI6421_PMIC = no;
        MFD_HI6421_SPMI = no;
        MFD_INTEL_QUARK_I2C_GPIO = no;
        LPC_ICH = no;
        LPC_SCH = no;
        MFD_INTEL_LPSS_PCI = no;
        MFD_IQS62X = no;
        MFD_JANZ_CMODIO = no;
        MFD_KEMPLD = no;
        MFD_88PM800 = no;
        MFD_88PM805 = no;
        MFD_88PM860X = no;
        MFD_88PM886_PMIC = no;
        MFD_MAX5970 = no;
        MFD_MAX14577 = no;
        MFD_MAX77541 = no;
        MFD_MAX77620 = no;
        MFD_MAX77650 = no;
        MFD_MAX77686 = no;
        MFD_MAX77693 = no;
        MFD_MAX77705 = no;
        MFD_MAX77714 = no;
        MFD_MAX77759 = no;
        MFD_MAX77843 = no;
        MFD_MAX8907 = no;
        MFD_MAX8925 = no;
        MFD_MAX8997 = no;
        MFD_MAX8998 = no;
        MFD_MT6360 = no;
        MFD_MT6370 = no;
        MFD_MT6397 = no;
        MFD_MENF21BMC = no;
        MFD_NCT6694 = no;
        MFD_OCELOT = no;
        EZX_PCAP = no;
        MFD_CPCAP = no;
        MFD_VIPERBOARD = no;
        MFD_NTXEC = no;
        MFD_RETU = no;
        MFD_SY7636A = no;
        CONFIG_MFD_RDC321X = no;
        MFD_RT4831 = no;
        MFD_RT5033 = no;
        MFD_RT5120 = no;
        MFD_RC5T583 = no;
        MFD_RK8XX_I2C = no;
        MFD_RK8XX_SPI = no;
        MFD_RN5T618 = no;
        MFD_SEC_I2C = no;
        MFD_SI476X_CORE = no;
        MFD_SM501 = no;
        MFD_SKY81452 = no;
        MFD_STMPE = no;
        MFD_LP3943 = no;
        MFD_LP8788 = no;
        MFD_TI_LMU = no;
        MFD_BQ257XX = no;
        MFD_PALMAS = no;
        TPS6105X = no;
        TPS65010 = no;
        TPS6507X = no;
        MFD_TPS65086 = no;
        MFD_TPS65090 = no;
        MFD_TPS65217 = no;
        MFD_TI_LP873X = no;
        MFD_TI_LP87565 = no;
        MFD_TPS65218 = no;
        MFD_TPS65219 = no;
        MFD_TPS6586X = no;
        MFD_TPS65910 = no;
        MFD_TPS65912_I2C = no;
        MFD_TPS65912_SPI = no;
        MFD_TPS6594_I2C = no;
        MFD_TPS6594_SPI = no;
        TWL4030_CORE = no;
        TWL6040_CORE = no;
        MFD_WL1273_CORE = no;
        MFD_LM3533 = no;
        MFD_TC3589X = no;
        MFD_TQMX86 = no;
        MFD_VX855 = no;
        GPIO_VX855 = no;
        MFD_ARIZONA_I2C = no;
        MFD_ARIZONA_SPI = no;
        MFD_WM8400 = no;
        MFD_WM831X_I2C = no;
        MFD_WM831X_SPI = no;
        MFD_WM8350_I2C = no;
        MFD_WM8994 = no;
        MFD_ROHM_BD718XX = no;
        MFD_ROHM_BD71828 = no;
        MFD_ROHM_BD957XMUF = no;
        MFD_ROHM_BD96801 = no;
        MFD_STPMIC1 = no;
        CONFIG_MFD_STMFX = no;
        PINCTRL_STMFX = no;
        MFD_ATC260X_I2C = no;
        MFD_QCOM_PM8008 = no;
        RAVE_SP_CORE = no;
        MFD_INTEL_M10_BMC_SPI = no;
        MFD_QNAP_MCU = no;
        MFD_RSMU_I2C = no;
        MFD_RSMU_SPI = no;
        MFD_MAX7360 = no;
      })
      (definePatch "rm-specific-regulators" {
        REGULATOR_88PG86X = no;
        REGULATOR_ACT8865 = no;
        REGULATOR_AD5398 = no;
        REGULATOR_ADP5055 = no;
        REGULATOR_AW37503 = no;
        REGULATOR_BCM590XX = no;
        REGULATOR_DA9121 = no;
        REGULATOR_DA9210 = no;
        REGULATOR_DA9211 = no;
        REGULATOR_FAN53555 = no;
        REGULATOR_FAN53880 = no;
        REGULATOR_ISL9305 = no;
        REGULATOR_ISL6271A = no;
        REGULATOR_LP3971 = no;
        REGULATOR_LP3972 = no;
        REGULATOR_LP872X = no;
        REGULATOR_LP8755 = no;
        REGULATOR_LTC3589 = no;
        REGULATOR_LTC3676 = no;
        REGULATOR_MAX1586 = no;
        REGULATOR_MAX77503 = no;
        REGULATOR_MAX77857 = no;
        REGULATOR_MAX8649 = no;
        REGULATOR_MAX8660 = no;
        REGULATOR_MAX8893 = no;
        REGULATOR_MAX8952 = no;
        REGULATOR_MAX8973 = no;
        REGULATOR_MAX20086 = no;
        REGULATOR_MAX20411 = no;
        REGULATOR_MAX77826 = no;
        REGULATOR_MAX77838 = no;
        REGULATOR_MCP16502 = no;
        REGULATOR_MP5416 = no;
        REGULATOR_MP8859 = no;
        REGULATOR_MP886X = no;
        REGULATOR_MPQ7920 = no;
        REGULATOR_MT6311 = no;
        REGULATOR_MT6315 = no;
        REGULATOR_PCA9450 = no;
        REGULATOR_PF9453 = no;
        REGULATOR_PF0900 = no;
        REGULATOR_PF530X = no;
        REGULATOR_PF8X00 = no;
        REGULATOR_PFUZE100 = no;
        REGULATOR_PV88060 = no;
        REGULATOR_PV88080 = no;
        REGULATOR_PV88090 = no;
        REGULATOR_QCOM_SPMI = no;
        REGULATOR_QCOM_USB_VBUS = no;
        REGULATOR_RAA215300 = no;
        REGULATOR_RASPBERRYPI_TOUCHSCREEN_ATTINY = no;
        REGULATOR_RASPBERRYPI_TOUCHSCREEN_V2 = no;
        REGULATOR_RT4801 = no;
        REGULATOR_RT4803 = no;
        REGULATOR_RT5133 = no;
        REGULATOR_RT5190A = no;
        REGULATOR_RT5739 = no;
        REGULATOR_RT5759 = no;
        REGULATOR_RT6160 = no;
        REGULATOR_RT6190 = no;
        REGULATOR_RT6245 = no;
        REGULATOR_RTQ2134 = no;
        REGULATOR_RTMV20 = no;
        REGULATOR_RTQ6752 = no;
        REGULATOR_RTQ2208 = no;
        REGULATOR_SLG51000 = no;
        REGULATOR_SY8106A = no;
        REGULATOR_SY8824X = no;
        REGULATOR_SY8827N = no;
        REGULATOR_TPS51632 = no;
        REGULATOR_TPS62360 = no;
        REGULATOR_TPS6286X = no;
        REGULATOR_TPS6287X = no;
        REGULATOR_TPS65023 = no;
        REGULATOR_TPS6507X = no;
        REGULATOR_TPS65132 = no;
        REGULATOR_TPS6524X = no;
        REGULATOR_QCOM_LABIBB = no;
      })
      (definePatch "rm-specific-graphics-drm" {
        DRM_KOMEDA = no;

        DRM_RADEON = no;
        DRM_AMDGPU = no;
        DRM_NOUVEAU = no;
        DRM_I915 = no;
        DRM_XE = no;
        DRM_VGEM = no;
        DRM_VKMS = no;
        DRM_GMA500 = no;
        DRM_UDL = no;
        DRM_AST = no;
        DRM_MGAG200 = no;
        DRM_QXL = no;

        DRM_PANEL_ABT_Y030XX067A = no;
        DRM_PANEL_ARM_VERSATILE = no;
        DRM_PANEL_AUO_A030JTN01 = no;
        DRM_PANEL_LVDS = no;
        DRM_PANEL_ILITEK_IL9322 = no;
        DRM_PANEL_ILITEK_ILI9341 = no;
        DRM_PANEL_INNOLUX_EJ030NA = no;
        DRM_PANEL_LG_LB035Q02 = no;
        DRM_PANEL_LG_LG4573 = no;
        DRM_PANEL_NEC_NL8048HL11 = no;
        DRM_PANEL_NEWVISION_NV3052C = no;
        DRM_PANEL_NOVATEK_NT39016 = no;
        DRM_PANEL_OLIMEX_LCD_OLINUXINO = no;
        DRM_PANEL_ORISETECH_OTA5601A = no;
        DRM_PANEL_SAMSUNG_S6E88A0_AMS452EF01 = no;
        DRM_PANEL_SAMSUNG_ATNA33XC20 = no;
        DRM_PANEL_SAMSUNG_DB7430 = no;
        DRM_PANEL_SAMSUNG_LD9040 = no;
        DRM_PANEL_SAMSUNG_S6D27A1 = no;
        DRM_PANEL_SAMSUNG_S6D7AA0 = no;
        DRM_PANEL_SAMSUNG_S6E63M0 = no;
        DRM_PANEL_SAMSUNG_S6E8AA0 = no;
        DRM_PANEL_SEIKO_43WVF1G = no;
        DRM_PANEL_SHARP_LS037V7DW01 = no;
        DRM_PANEL_SITRONIX_ST7701 = no;
        DRM_PANEL_SITRONIX_ST7789V = no;
        DRM_PANEL_SONY_ACX565AKM = no;
        DRM_PANEL_EDP = no;
        DRM_PANEL_SIMPLE = no;
        DRM_PANEL_TPO_TD028TTEC1 = no;
        DRM_PANEL_TPO_TD043MTEA1 = no;
        DRM_PANEL_TPO_TPG110 = no;
        DRM_PANEL_WIDECHIPS_WS2401 = no;

        DRM_CHIPONE_ICN6211 = no;
        DRM_CHRONTEL_CH7033 = no;
        DRM_DISPLAY_CONNECTOR = no;
        DRM_I2C_NXP_TDA998X = no;
        DRM_ITE_IT6263 = no;
        DRM_ITE_IT6505 = no;
        DRM_LONTIUM_LT8912B = no;
        DRM_LONTIUM_LT9211 = no;
        DRM_LONTIUM_LT9611 = no;
        DRM_LONTIUM_LT9611UXC = no;
        DRM_ITE_IT66121 = no;
        DRM_LVDS_CODEC = no;
        DRM_MEGACHIPS_STDPXXXX_GE_B850V3_FW = no;
        DRM_NWL_MIPI_DSI = no;
        DRM_NXP_PTN3460 = no;
        DRM_PARADE_PS8622 = no;
        DRM_PARADE_PS8640 = no;
        DRM_SAMSUNG_DSIM = no;
        DRM_SIL_SII8620 = no;
        DRM_SII902X = no;
        DRM_SII9234 = no;
        DRM_SIMPLE_BRIDGE = no;
        DRM_SOLOMON_SSD2825 = no;
        DRM_THINE_THC63LVD1024 = no;
        DRM_TOSHIBA_TC358762 = no;
        DRM_TOSHIBA_TC358764 = no;
        DRM_TOSHIBA_TC358767 = no;
        DRM_TOSHIBA_TC358768 = no;
        DRM_TOSHIBA_TC358775 = no;
        DRM_TI_DLPC3433 = no;
        DRM_TI_TDP158 = no;
        DRM_TI_TFP410 = no;
        DRM_TI_SN65DSI83 = no;
        DRM_TI_SN65DSI86 = no;
        DRM_TI_TPD12S015 = no;
        DRM_WAVESHARE_BRIDGE = no;
        DRM_ANALOGIX_ANX6345 = no;
        DRM_ANALOGIX_ANX78XX = no;
        DRM_ANALOGIX_ANX7625 = no;
        DRM_I2C_ADV7511 = no;
        DRM_CDNS_DSI = no;
        DRM_CDNS_MHDP8546 = no;
        # end of Display Interface Bridges

        DRM_ETNAVIV = no;
        DRM_HISI_HIBMC = no;
        DRM_LOGICVC = no;
        DRM_APPLETBDRM = no;
        DRM_ARCPGU = no;
        DRM_BOCHS = no;
        DRM_CIRRUS_QEMU = no;
        DRM_GM12U320 = no;
        DRM_PANEL_MIPI_DBI = no;
        DRM_PIXPAPER = no;
        TINYDRM_HX8357D = no;
        TINYDRM_ILI9163 = no;
        TINYDRM_ILI9225 = no;
        TINYDRM_ILI9341 = no;
        TINYDRM_ILI9486 = no;
        TINYDRM_MI0283QT = no;
        TINYDRM_REPAPER = no;
        TINYDRM_SHARP_MEMORY = no;
        DRM_VBOXVIDEO = no;
        DRM_GUD = no;
        DRM_ST7571_I2C = no;
        DRM_ST7586 = no;
        DRM_ST7735R = no;
        DRM_SSD130X = no;

        FB = no;
      })
      (definePatch "rm-specific-backlight-lcd" {
        LCD_CLASS_DEVICE = no;
        BACKLIGHT_KTD253 = no;
        BACKLIGHT_KTD2801 = no;
        BACKLIGHT_KTZ8866 = no;
        BACKLIGHT_QCOM_WLED = no;
        BACKLIGHT_SAHARA = no;
        BACKLIGHT_ADP8860 = no;
        BACKLIGHT_ADP8870 = no;
        BACKLIGHT_LM3509 = no;
        BACKLIGHT_LM3630A = no;
        BACKLIGHT_LM3639 = no;
        BACKLIGHT_LP855X = no;
        BACKLIGHT_MP3309C = no;
        BACKLIGHT_LV5207LP = no;
        BACKLIGHT_BD6107 = no;
        BACKLIGHT_ARCXCNN = no;
      })
      (definePatch "rm-specific-audio-drivers" {
      })
    ];
  };
}
