{
  config,
  lib,
  ...
}:
let
  inherit (lib)
    types
    mkOption
    lists
    mkIf
    mkForce
    ;

  patchSet =
    with types;
    submodule {
      options.name = mkOption {
        type = str;
        description = "Name of the patchset to apply";
      };
      options.overrides = mkOption {
        type = attrs;
        default = { };
        description = "Structured Attrs Kernel config to override in the patchset";
      };
    };

  definePatch =
    setName: defaultPatch:
    (mkIf
      ((lists.findSingle (x: x.name == setName) { } { } config.boot.kernel.buildConfig.patchSets) != { })
      ({
        name = setName;
        patch = null;
        structuredExtraConfig = lib.mergeAttrsList [
          defaultPatch
          (lists.findSingle (x: x.name == setName) { } { } config.boot.kernel.buildConfig.patchSets).overrides
        ];
      })
    );
in
{
  options.boot.kernel.buildConfig = {
    patchSets = lib.mkOption {
      type = lib.types.listOf patchSet;
      description = "Patches to the Kernel Config to apply";
    };
  };

  config = {
    boot.kernelPatches = with lib.kernel; [
      # (definePatch "example" { })
      (definePatch "rm-unused-fs" {
        # Filesystems
        EROFS_FS = no; # containers use this?
        HFS = no; # Probably might encounter this
        HFSPLUS_FS = no;
        # PSTORE = module; # Set upstream
        SQUASHFS = module; # Generally useful
        JFS_FS = no;
        XFS_FS = no;
        GFS2_FS = no;
        NILFS2_FS = no;
        F2FS_FS = mkForce no;
        ORANGEFS_FS = no;
        ADFS_FS = no;
        AFFS_FS = no;
        BEFS_FS = no;
        BFS_FS = no;
        EFS_FS = no;
        CRAMFS = no;
        VXFS_FS = no;
        MINIX_FS = no;
        OMFS_FS = no;
        HPFS_FS = no;
        QNX4_FS = no;
        QNX6_FS = no;
        ROMFS_FS = no;
        UFS_FS = no;
        CEPH_FS = no;
        CODA_FS = no;
        AFS_FS = no;
        "9P_FS" = no;
        ROOT_NFS = no;

        CONFIG_QFMT_V1 = no;
      })
      (definePatch "rm-x86-platform-drivers" {
        # x86 Platform Drivers
        ACERHDF = no; # Acer Aspire One Temp Sensor/Fan
        ACER_WIRELESS = no;
        ACER_WMI = no;
        ACPI_CMPC = no; # Intel Classmate PC from early 20xx
        ADV_SWBUTTON = no; # Advantech software defined button
        AMILO_RFKILL = no; # Wifi for Fujitsu-Siemens Amilo Laptops
        APPLE_GMUX = no; # Gmux on Apple Laptops
        ASUS_ARMORY = no;
        ASUS_LAPTOP = no;
        ASUS_NB_WMI = no;
        ASUS_TF103C_DOCK = no;
        ASUS_WIRELESS = no;
        ASUS_WMI = no;
        AYANEO_EC = no;
        BARCO_P50_GPIO = no;
        COMPAL_LAPTOP = no;
        DASHARO_ACPI = no;
        DELL_LAPTOP = no;
        EEEPC_LAPTOP = no;
        EEEPC_WMI = no;
        FUJITSU_LAPTOP = no;
        FUJITSU_TABLET = no;
        GIGABYTE_WMI = no;
        GPD_POCKET_FAN = no;
        HUAWEI_WMI = no;
        IDEAPAD_LAPTOP = no;
        INSPUR_PLATFORM_PROFILE = no;
        LENOVO_WMI_CAMERA = no;
        LENOVO_WMI_HOTKEY_UTILITIES = no;
        LENOVO_WMI_GAMEZONE = no;
        LENOVO_WMI_TUNING = no;
        LG_LAPTOP = no;
        MERAKI_MX100 = no; # Cisco Meraki MX100 Appliance
        MEEGOPAD_ANX7428 = no;
        MSI_EC = no; # Userspace access for the MSI platform drivers we disabled
        MSI_LAPTOP = no;
        MSI_WMI = no;
        MSI_WMI_PLATFORM = no;
        OXP_EC = no; # OneXPlayer/AOKZOE embedded controller
        PANASONIC_LAPTOP = no;
        PCENGINES_APU2 = no;
        PORTWELL_EC = no;
        REDMI_WMI = no;
        SAMSUNG_GALAXYBOOK = no;
        SAMSUNG_LAPTOP = no;
        SAMSUNG_Q10 = no;
        SEL3350_PLATFORM = no;
        SIEMENS_SIMATIC_IPC = no;
        SILICOM_PLATFORM = no;
        SONY_LAPTOP = no;
        SYSTEM76_ACPI = no;
        THINKPAD_ACPI = no; # IBM/Lenovo Thinkpad Stuff
        THINKPAD_LMI = no; # Lenovo WMI system management driver
        TOPSTAR_LAPTOP = no;
        TOSHIBA_BT_RFKILL = no;
        TOSHIBA_HAPS = no; # Toshiba Hard Drive Protection Thing
        TOSHIBA_WMI = no;
        TUXEDO_NB04_WMI_AB = no;
        WINMATE_FM07_KEYS = no;
        WIRELESS_HOTKEY = no; # Wireless button on AMD/HP/Xiaomi Laptops
        XIAOMI_WMI = no;
        X86_ANDROID_TABLETS = no;
        X86_PLATFORM_DRIVERS_DELL = mkForce no;
        X86_PLATFORM_DRIVERS_HP = mkForce no;
        X86_PLATFORM_DRIVERS_UNIWILL = no;
        YOGABOOK = no;
        YT2_1380 = no; # Lenovo Yoga Tablet 2 1380 fast charging protocol
      })
      (definePatch "rm-unused-driver-categories" {
        ACCESSIBILITY = mkForce no;
        BCMA = no; # Broadcom Specific AMBA
        CHROME_PLATFORMS = mkForce no;
        COMEDI = no; # Scientific Data Collection Hardware
        FIREWIRE = no;
        FIREWIRE_NOSY = no; # Firewire Probe Thing?
        FPGA = no;
        FSI = no;
        FUSION = mkForce no; # Fusion Message Passing Technology
        GOOGLE_FIRMWARE = lib.mkForce no;
        GOLDFISH = no; # Goldfish Virtual Platform
        GPIB = no; # General Purpose Interface Bus
        GREYBUS = no;
        HAMRADIO = lib.mkForce no; # Ham Radio Support
        HSI = no; # High-spped synchronous Serial Interface
        HSI_BOARDINFO = no;
        HTE = no;
        IIO = no; # Industrial I/O
        INFINIBAND = mkForce no; # Before ethernet was fast or something
        INTERCONNECT = no;
        IPACK_BUS = no; # IndustryPack Bus
        LIRC = mkForce no;
        MCB = no;
        MELLANOX_PLATFORM = no; # Mellanox Drivers
        MEMSTICK = no; # Sony Memory Stick
        MOST = no; # Media Oriented Systems Transport
        NTB = no;
        # OF = mkForce no; # Open Firmware/Device Trees - We use ACPI here
        PARPORT = no; # Parallel Port - which we don't have
        PPDEV = no;
        PCCARD = no; # Predecessor to PCMCIA
        # PECI = no;
        # PPS = no; # Pulse Per Second (GPS-related)
        RAS = mkForce no;
        REGULATOR = mkForce no; # Generic Voltage/Current Regulators - done via ACPI?
        REMOTEPROC = no;
        RESET_CONTROLLER = no; # GPIO and similar Reset Controllers
        # SSB = no; # Sonics Silicon Backplane - Why dependency???
        SIOX = no;
        SLIMBUS = no;
        # W1 = no;

        STAGING = mkForce no;
      })
      (definePatch "rm-unused-individual-drivers" {
        # Misc Drivers (Individual)
        AD525X_DPOT = no; # Analog Devices Digital Potentiometers
        ALTERA_STAPL = no; # Altera Firmware Download thing
        APDS9802ALS = no; # Ambient Light Sensor
        BCM_VK = no; # Broadcom VK Accelerators
        C2PORT = no; # Silicon Labs C2 Port
        # CB710_CORE = no; # PCI ENE CB710/720 Flash Memory card reader
        DS1682 = no; # Elapsed Time Recorder with Alarm - Whatever that is
        DUMMY_IRQ = no;
        DW_XDATA_PCIE = no; # Synopsys DesignWare PCIe traffic generator IP
        GENWQE = no; # IBM GenWQE Accelerators
        HI6421V600_IRQ = no; # IRQ handling for the thing on Kirin chipsets
        HISI_HIKEY_USB = no; # USB GPIO Hub on HiSilicon Hikey 960/70
        HMC6352 = no; # A compass? huh
        HP_ILO = no; # Used in HP ProLiant servers
        IBM_ASM = no; # IBM RSA service processor
        ICS932S401 = no; # A clock control chip
        ISL29003 = no; # Ambient Light Sensor
        ISL29020 = no; # Ambient Light Sensor
        KEBA_CP500 = no; # KEBA CP500 System FPGA
        LATTICE_ECP3_CONFIG = no; # Programmer for Lattice ECP3 FPGA
        MISC_ALCOR_PCI = no; # Alcor Micro PCI express card readers
        MISC_RTSX_PCI = no; # Realtek PCI express card readers
        MUX_ADG792A = no; # Multiplexer
        NSM = no; # Nitro Security Module - AWS EC2
        PCI_ENDPOINT_TEST = no;
        PHANTOM = no; # Sensable PHANToM
        SENSORS_APDS990X = no; # Ambient Light Sensor + Proximity Sensor
        SENSORS_BH1770 = no; # Ambient Light Sensor + Proximity Sensor
        SENSORS_LIS3_I2C = no; # Accelerometer
        SENSORS_LIS3LV02D = no; # Accelerometer - but 3 axis digital
        SENSORS_TSL2550 = no; # Ambient Light Sensor
        SMPRO_ERRMON = no; # Ampere Computing SMPro Error Monitor
        SMPRO_MISC = no; # Ampere Computing SMPro Misc Drivers
        TI_FPC202 = no; # Texas Instruments FPC202 Dual Port Controller
        TPS6594_ESM = no; # TI TPS6594 PMIC Error Signal Monitor
        TPS6594_PFSM = no; # TI TPS6594 PMIC Preconfigurable Finite State Machine
        VCPU_STALL_DETECTOR = no;
        VMWARE_BALLOON = no; # VMWare Memory Balloon
        VMWARE_VMCI = no; # VMWare Virtual Machine Communication Interface
        XILINX_SDFEC = no; # Xilinx Soft Decision Forward Error Correction Driver
      })
      (definePatch "rm-net-top-level" {
        # Top-level categories under Networking Drivers
        # and dependencies that might enable them

        HAMRADIO = no;
        CAN = no;
        AF_RXRPC = no;
        MCTP = no;
        NET_9P = no;
        CAIF = no;
        NFC = no;

        ARCNET = no;
        ATM_DRIVERs = no;

        B53 = no;
        FDDI = no; # Fiber Distributed Data Interface
        HIPPI = no; # High Performance Parallel Interface
        PPP = no;
        SLIP = no;
        USB_NET_DRIVERS = no;
        WWAN = no;
        VMXNET3 = no;
        USB4_NET = no;
        NETDEVSIM = no;
        ISDN = no;
        PLIP = no; # Parallel Line Internet Protocol
        WAN = mkForce no;
        HYPERV_NET = no;
        NET_FC = mkForce no;
        FUJITSU_ES = no; # Fujitsu Extended Socket Network Device
        INFINIBAND = no;

        CEPH_LIB = no;
        BLK_DEV_RBD = no; # Rados Block Device - Selects CEPH_LIB

        MLX5_CORE = no;
      })
      (definePatch "rm-net-dsa-drivers" {
        B53 = no;
        NET_DSA_BCM_SF2 = no;
        NET_DSA_LOOP = no;
        NET_DSA_HIRSCHMANN_HELLCREEK = no;
        NET_DSA_LANTIQ_GSWIP = no;
        NET_DSA_MT7530 = no;
        NET_DSA_MV88E6060 = no;
        NET_DSA_MICROCHIP_KSZ_COMMON = no;
        NET_DSA_MV88E6XXX = no;
        NET_DSA_AR9331 = no;
        NET_DSA_QCA8K = no;
        NET_DSA_SJA1105 = no;
        NET_DSA_XRS700X = no;
        NET_DSA_XRS700X_MDIO = no;
        NET_DSA_XRS700X_I2C = no;
        NET_DSA_REALTEK = no;
        NET_DSA_KS8995 = no;
        NET_DSA_VITESSE_VSC73XX = no;
        NET_DSA_VITESSE_VSC73XX_PLATFORM = no;
        NET_DSA_VITESSE_VSC73XX_SPI = no;
      })
      (definePatch "rm-net-ethernet-drivers" {
        NET_VENDOR_3COM = no;
        NET_VENDOR_ADAPTEC = no;
        NET_VENDOR_ADI = no;
        NET_VENDOR_AGERE = no;
        NET_VENDOR_ALACRITECH = no;
        NET_VENDOR_ALTEON = no;
        ALTERA_TSE = no; # Altera Triple Speed Ethernet MAC
        NET_VENDOR_AMAZON = no;
        NET_VENDOR_AMD = no;
        NET_VENDOR_AQUANTIA = no;
        NET_VENDOR_ARC = no;
        NET_VENDOR_ASIX = no;
        NET_VENDOR_ATHEROS = no;
        NET_VENDOR_BROADCOM = no;
        NET_VENDOR_CADENCE = no;
        NET_VENDOR_CAVIUM = no;
        NET_VENDOR_CORTINA = no;
        NET_VENDOR_DAVICOM = no;
        NET_VENDOR_DEC = no;
        DNET = no; # Dave Ethernet
        NET_VENDOR_ENGLEDER = no;
        ETHOC = no; # OpenCores 10/100 Mbps Ethernet MAC
        NET_VENDOR_EZCHIP = no;
        FEALNX = no; # Myson MTD-8xx PCI Ethernet
        NET_VENDOR_FREESCALE = no;
        NET_VENDOR_FUNGIBLE = no;
        NET_VENDOR_GOOGLE = no;
        NET_VENDOR_HISILICON = no;
        NET_VENDOR_HUAWEI = no;
        NET_VENDOR_I825XX = no;
        JME = no; # JMicron PCI-E Gigabit Ethernet
        NET_VENDOR_LITEX = no;
        NET_VENDOR_MARVELL = no;
        NET_VENDOR_META = no;
        NET_VENDOR_MELLANOX = no;
        NET_VENDOR_MICREL = no;
        NET_VENDOR_MICROCHIP = no;
        NET_VENDOR_MICROSEMI = no;
        NET_VENDOR_MICROSOFT = no;
        NET_VENDOR_MYRI = no;
        NET_VENDOR_NI = no;
        NET_VENDOR_NATSEMI = no;
        NET_VENDOR_NETRONOME = no;
        NXP_ENETC4 = no;
        NET_VENDOR_8390 = no;
        NET_VENDOR_NVIDIA = no;
        NET_VENDOR_OKI = no;
        NET_VENDOR_PACKET_ENGINES = no;
        NET_VENDOR_PENSANDO = no;
        NET_VENDOR_QLOGIC = no;
        NET_VENDOR_BROCADE = no;
        NET_VENDOR_QUALCOMM = no;
        NET_VENDOR_RDC = no;
        NET_VENDOR_REALTEK = no;
        NET_VENDOR_RENESAS = no;
        NET_VENDOR_ROCKER = no;
        NET_VENDOR_SAMSUNG = no;
        NET_VENDOR_SEEQ = no;
        NET_VENDOR_SILAN = no;
        NET_VENDOR_SIS = no;
        NET_VENDOR_SOLARFLARE = no;
        NET_VENDOR_SMSC = no;
        NET_VENDOR_SOCIONEXT = no;
        NET_VENDOR_STMICRO = no;
        NET_VENDOR_SUN = no;
        NET_VENDOR_SYNOPSYS = no;
        NET_VENDOR_TEHUTI = no;
        NET_VENDOR_TI = no;
        NET_VENDOR_VERTEXCOM = no;
        NET_VENDOR_VIA = no;
        NET_VENDOR_WANGXUN = no;
        NET_VENDOR_WIZNET = no;
        NET_VENDOR_XILINX = no;
      })
      (definePatch "rm-net-wlan-drivers" {
        WLAN_VENDOR_ADMTEK = no;
        WLAN_VENDOR_ATH = no;
        WLAN_VENDOR_ATMEL = no;
        WLAN_VENDOR_BROADCOM = no;
        WLAN_VENDOR_INTERSIL = no;
        WLAN_VENDOR_INTEL = no;
        WLAN_VENDOR_MARVELL = no;
        WLAN_VENDOR_MEDIATEK = no;
        WLAN_VENDOR_MICROCHIP = no;
        WLAN_VENDOR_PURELIFI = no;
        WLAN_VENDOR_RALINK = no;
        WLAN_VENDOR_REALTEK = no;
        WLAN_VENDOR_RSI = no;
        WLAN_VENDOR_SILABS = no;
        WLAN_VENDOR_ST = no;
        WLAN_VENDOR_TI = no;
        WLAN_VENDOR_ZYDAS = no;
        WLAN_VENDOR_QUANTENNA = no;
        IPW2100 = no;
        IPW2200 = no;
        IWL4965 = no;
        IWL3945 = no;
        RTL8723BS = no;
      })
      (definePatch "rm-net-ethernet-specific-phy" {
        AS21XXX_PHY = no;
        AIR_EN8811H_PHY = no;
        AMD_PHY = no;
        ADIN_PHY = no;
        ADIN1100_PHY = no;
        AQUANTIA_PHY = no;
        # AX88796B_PHY = no;
        # USB_NET_AX8817X = no;
        BROADCOM_PHY = no;
        BCM54140_PHY = no;
        BCM7XXX_PHY = no;
        BCM84881_PHY = no;
        BCM87XX_PHY = no;
        BCM_NET_PHYLIB = no;
        BCM_NET_PHYPTP = no;
        CICADA_PHY = no;
        CORTINA_PHY = no;
        DAVICOM_PHY = no;
        ICPLUS_PHY = no;
        LXT_PHY = no;
        INTEL_XWAY_PHY = no;
        LSI_ET1011C_PHY = no;
        MARVELL_PHY = no;
        MARVELL_10G_PHY = no;
        MARVELL_88Q2XXX_PHY = no;
        MARVELL_88X2222_PHY = no;
        MAXLINEAR_GPHY = no;
        MAXLINEAR_86110_PHY = no;
        MEDIATEK_GE_PHY = no;
        MICREL_PHY = no;
        MICROCHIP_T1S_PHY = no;
        # MICROCHIP_PHY = no;
        USB_LAN78XX = no;
        MICROCHIP_T1_PHY = no;
        MICROSEMI_PHY = no;
        MOTORCOMM_PHY = no;
        NATIONAL_PHY = no;
        NXP_CBTX_PHY = no;
        NXP_C45_TJA11XX_PHY = no;
        NXP_TJA11XX_PHY = no;
        NCN26000_PHY = no;
        AT803X_PHY = no;
        QCA83XX_PHY = no;
        QCA808X_PHY = no;
        QCA807X_PHY = no;
        QSEMI_PHY = no;
        REALTEK_PHY = no;
        RENESAS_PHY = no;
        ROCKCHIP_PHY = no;
        # SMSC_PHY = no;
        MESON_GXL_PHY = no;
        USB_NET_SMSC95XX = no;
        NET_DSA_SMSC_LAN9303 = no;
        STE10XP = no;
        TERANETICS_PHY = no;
        DP83822_PHY = no;
        DP83TC811_PHY = no;
        DP83848_PHY = no;
        DP83867_PHY = no;
        DP83869_PHY = no;
        DP83TD510_PHY = no;
        DP83TG720_PHY = no;
        VITESSE_PHY = no;
        XILINX_GMII2RGMII = no;
        PSE_CONTROLLER = no;
        MDIO_HISI_FEMAC = no;
        MDIO_MVUSB = no;
        MDIO_MSCC_MIIM = no;
        MDIO_OCTEON = no;
        MDIO_IPQ4019 = no;
        MDIO_IPQ8064 = no;
        MDIO_THUNDER = no;
      })
      (definePatch "rm-parallel-ata" {
        # Parallel ATA
        # PATA_TIMINGS = no; # Set Incorrectly
        PATA_ACPI = no;
        PATA_LEGACY = no;
        PATA_ALI = no;
        PATA_AMD = no;
        PATA_ARTOP = no;
        PATA_ATIIXP = no;
        PATA_ATP867X = no;
        PATA_CMD64X = no;
        PATA_CYPRESS = no;
        PATA_EFAR = no;
        PATA_HPT366 = no;
        PATA_HPT37X = no;
        PATA_HPT3X2N = no;
        PATA_HPT3X3 = no;
        # PATA_HPT3X3_DMA is not set
        PATA_IT8213 = no;
        PATA_IT821X = no;
        PATA_JMICRON = no;
        # PATA_MARVELL = no;
        PATA_NETCELL = no;
        PATA_NINJA32 = no;
        PATA_NS87415 = no;
        PATA_OLDPIIX = no;
        PATA_OPTIDMA = no;
        PATA_PDC2027X = no;
        PATA_PDC_OLD = no;
        PATA_RADISYS = no;
        PATA_RDC = no;
        PATA_SCH = no;
        PATA_SERVERWORKS = no;
        PATA_SIL680 = no;
        # PATA_SIS = no; # Set Incorrectly
        PATA_TOSHIBA = no;
        PATA_TRIFLEX = no;
        PATA_VIA = no;
        PATA_WINBOND = no;
        PATA_CMD640_PCI = no;
        PATA_MPIIX = no;
        PATA_NS87410 = no;
        PATA_OPTI = no;
        PATA_RZ1000 = no;
        SBP_TARGET = no;
        PPDEV = no;
      })
      (definePatch "rm-unused-graphics" {
        # Graphics
        AGP = mkForce no;
        DRM_AMDGPU = no;
        DRM_AST = no;
        DRM_ETNAVIV = no;
        DRM_GMA500 = mkForce no;
        DRM_GUD = no;
        DRM_HISI_HIBMC = no;
        DRM_I915 = yes; # We do want intel graphics
        DRM_MGAG200 = no;
        DRM_NOUVEAU = no; # Using stupid nvidia proprietary drivers
        DRM_PANEL_RASPBERRYPI_TOUCHSCREEN = no;
        DRM_QXL = no;
        DRM_RADEON = no;
        DRM_ST7571 = no;
        DRM_SSD130x = no;
        DRM_APPLETBDRM = no;
        DRM_BOCHS = no;
        DRM_CIRRUS_QEMU = no;
        DRM_GM12U320 = no;
        DRM_VBOXVIDEO = no;
        DRM_VGEM = no;
        DRM_VMWGFX = no;
        DRM_XE = no;
        FB = mkForce no; # Replaced by DRM/KMS
      })
      (definePatch "rm-hid-specific-keyboard" {
        # KEYBOARD_ATKBD = no; - Needed to use any laptop keyboard
        # HID/Input Drivers
        MACINTOSH_DRIVERS = no;
        MAC_EMUMOUSEBTN = no;
        KEYBOARD_ADP5585 = no;
        KEYBOARD_ADP5588 = no;
        KEYBOARD_APPLESPI = mkForce no;
        KEYBOARD_QT1050 = no;
        KEYBOARD_QT1070 = no;
        KEYBOARD_QT2160 = no;
        KEYBOARD_DLINK_DIR685 = no;
        KEYBOARD_LKKBD = no;
        KEYBOARD_TCA8418 = no;
        KEYBOARD_LM8323 = no;
        KEYBOARD_LM8333 = no;
        KEYBOARD_MAX7359 = no;
        KEYBOARD_MAX7360 = no;
        KEYBOARD_MPR121 = no;
        KEYBOARD_NEWTON = no;
        KEYBOARD_OPENCORES = no;
        KEYBOARD_PINEPHONE = no;
        KEYBOARD_SAMSUNG = no;
        KEYBOARD_STOWAWAY = no;
        KEYBOARD_SUNKBD = no;
        KEYBOARD_STMPE = no;
        KEYBOARD_IQS62X = no;
        KEYBOARD_OMAP4 = no;
        KEYBOARD_TM2_TOUCHKEY = no;
        KEYBOARD_XTKBD = no;
        KEYBOARD_CAP11XX = no;
        KEYBOARD_BCM = no;
        KEYBOARD_MTK_PMIC = no;
        KEYBOARD_CYPRESS_SF = no;
      })
      (definePatch "rm-hid-specific-mouse" {
        MOUSE_PS2 = no;

        MOUSE_APPLETOUCH = no;
        MOUSE_BCM5974 = no;
        MOUSE_CYAPA = no;
        MOUSE_ELAN_I2C = no;
        MOUSE_VSXXXAA = no;
      })
      (definePatch "rm-hid-misc" {
        JOYSTICK_DB9 = no;
        JOYSTICK_GAMECON = no;
        JOYSTICK_TURBOGRAFX = no;
        JOYSTICK_WALKERA0701 = no;

        INPUT_TABLET = no;
        INPUT_TOUCHSCREEN = no;
        INPUT_MISC = no;
      })
      (definePatch "rm-pcie-top-level" {
        PCI_SW_SWITCHTEC = no;
        PCI_PWRCTRL_SLOT = no;
        CXL_BUS = no;
        PCCARD = no;
        RAPIDIO = no;
        PC104 = no;

        MCHP_LAN966X_PCI = no; # Microchip LAN966X_PCIE
        GP_PCI1XXXX = no; # Microchip PCI1XXXX PCIe to GPIO Expander + OTP/EEPROM Manager

        DWC_PCIE_PMU = no; # Synopsys DesignWare PCIe PMU on Alibaba HW

        PCIE_CADENCE_PLAT_HOST = no;
        PCIE_MICROCHIP_HOST = no;

        CB710_CORE = no; # ENE CB710 PCI Flash Memory Reader
        CB710_MMC = no; # ENE CB710 PCI Flash Memory Reader
        MMC_CB710 = no;

        APPLICOM = no; # Applicom intelligent fieldbus card
        XILLYBUS = no;
        XILLYUSB = no;
      })
      (definePatch "rm-scsi-top-level" {
        CHR_DEV_ST = no; # SCSI Tape Drives
        BLK_DEV_SR = no; # SCSI CD-ROM
        CDROM = no;
        CHR_DEV_SCH = no; # SCSI Media Changer (like in jukeboxes)

        # SCSI_SAS_ATTRS = no; # SCSI SAS Transport Attributes
        # SCSI_SAS_LIBSAS = no;
        SCSI_PPA = no; # IOMEGA Parallel Port - older
        SCSI_IMM = no; # IOMEGA Parallel Port - newer

      })
      (definePatch "rm-media-tuners" {
        # TV tuners and things like what linux supported all this?
        RC_CORE = mkForce no;
        VIDEO_TVEEPROM = no;
        VIDEO_TUNER = no;
        MEDIA_CONTROLLER_DVB = no;
        DVB_DYNAMIC_MINORS = mkForce no;
        VIDEO_USBTV = no;
        RADIO_ADAPTERS = no;
        MEDIA_ANALOG_TV_SUPPORT = mkForce no;
        MEDIA_CEC_SUPPORT = mkForce no;
        MEDIA_COMMON_OPTIONS = no;
        MEDIA_DIGITAL_TV_SUPPORT = mkForce no;
        MEDIA_PLATFORM_DRIVERS = no;
        MEDIA_PCI_SUPPORT = mkForce no;
        MEDIA_RADIO_SUPPORT = no;
        MEDIA_SDR_SUPPORT = no;
        MEDIA_TEST_SUPPORT = no;
        MEDIA_ATTACH = mkForce no;
        CYPRESS_FIRMWARE = no;
        USB_GSPCA = no;
        USB_AIRSPY = no;
        USB_HACKRF = no;
        USB_MSI2500 = no;
        SMS_SIANO_MDTV = no;
        MEDIA_TUNER = no;
        TOUCHSCREEN_SUR40 = no;
        DVB_AS102 = no;
        DVB_B2C2_FLEXCOP_USB = no;
        # DVB_B2C2_FLEXCOP_USB_DEBUG is not set
        DVB_USB_V2 = no;
        SMS_USB_DRV = no;
        DVB_TTUSB_BUDGET = no;
        DVB_TTUSB_DEC = no;
        DVB_B2C2_FLEXCOP = no;
        MEDIA_TUNER_E4000 = no;
        MEDIA_TUNER_FC0011 = no;
        MEDIA_TUNER_FC0012 = no;
        MEDIA_TUNER_FC0013 = no;
        MEDIA_TUNER_FC2580 = no;
        MEDIA_TUNER_IT913X = no;
        MEDIA_TUNER_M88RS6000T = no;
        MEDIA_TUNER_MAX2165 = no;
        MEDIA_TUNER_MC44S803 = no;
        MEDIA_TUNER_MSI001 = no;
        MEDIA_TUNER_MT2060 = no;
        MEDIA_TUNER_MT2063 = no;
        MEDIA_TUNER_MT20XX = no;
        MEDIA_TUNER_MT2131 = no;
        MEDIA_TUNER_MT2266 = no;
        MEDIA_TUNER_MXL301RF = no;
        MEDIA_TUNER_MXL5005S = no;
        MEDIA_TUNER_MXL5007T = no;
        MEDIA_TUNER_QM1D1B0004 = no;
        MEDIA_TUNER_QM1D1C0042 = no;
        MEDIA_TUNER_QT1010 = no;
        MEDIA_TUNER_R820T = no;
        MEDIA_TUNER_SI2157 = no;
        MEDIA_TUNER_SIMPLE = no;
        MEDIA_TUNER_TDA18212 = no;
        MEDIA_TUNER_TDA18218 = no;
        MEDIA_TUNER_TDA18250 = no;
        MEDIA_TUNER_TDA18271 = no;
        MEDIA_TUNER_TDA827X = no;
        MEDIA_TUNER_TDA8290 = no;
        MEDIA_TUNER_TDA9887 = no;
        MEDIA_TUNER_TEA5761 = no;
        MEDIA_TUNER_TEA5767 = no;
        MEDIA_TUNER_TUA9001 = no;
        MEDIA_TUNER_XC2028 = no;
        MEDIA_TUNER_XC4000 = no;
        MEDIA_TUNER_XC5000 = no;
        DVB_M88DS3103 = no;
        DVB_MXL5XX = no;
        DVB_STB0899 = no;
        DVB_STB6100 = no;
        DVB_STV090x = no;
        DVB_STV0910 = no;
        DVB_STV6110x = no;
        DVB_STV6111 = no;
        DVB_DRXK = no;
        DVB_MN88472 = no;
        DVB_MN88473 = no;
        DVB_SI2165 = no;
        DVB_TDA18271C2DD = no;
        DVB_CX24110 = no;
        DVB_CX24116 = no;
        DVB_CX24117 = no;
        DVB_CX24120 = no;
        DVB_CX24123 = no;
        DVB_DS3000 = no;
        DVB_MB86A16 = no;
        DVB_MT312 = no;
        DVB_S5H1420 = no;
        DVB_SI21XX = no;
        DVB_STB6000 = no;
        DVB_STV0288 = no;
        DVB_STV0299 = no;
        DVB_STV0900 = no;
        DVB_STV6110 = no;
        DVB_TDA10071 = no;
        DVB_TDA10086 = no;
        DVB_TDA8083 = no;
        DVB_TDA8261 = no;
        DVB_TDA826X = no;
        DVB_TS2020 = no;
        DVB_TUA6100 = no;
        DVB_TUNER_CX24113 = no;
        DVB_TUNER_ITD1000 = no;
        DVB_VES1X93 = no;
        DVB_ZL10036 = no;
        DVB_ZL10039 = no;
        DVB_AF9013 = no;
        DVB_AS102_FE = no;
        DVB_CX22700 = no;
        DVB_CX22702 = no;
        DVB_CXD2820R = no;
        DVB_CXD2841ER = no;
        DVB_DIB3000MB = no;
        DVB_DIB3000MC = no;
        DVB_DIB7000M = no;
        DVB_DIB7000P = no;
        DVB_DIB9000 = no;
        DVB_DRXD = no;
        DVB_EC100 = no;
        DVB_L64781 = no;
        DVB_MT352 = no;
        DVB_NXT6000 = no;
        DVB_RTL2830 = no;
        DVB_RTL2832 = no;
        DVB_RTL2832_SDR = no;
        DVB_S5H1432 = no;
        DVB_SI2168 = no;
        DVB_SP887X = no;
        DVB_STV0367 = no;
        DVB_TDA10048 = no;
        DVB_TDA1004X = no;
        DVB_ZD1301_DEMOD = no;
        DVB_ZL10353 = no;
        DVB_CXD2880 = no;
        DVB_STV0297 = no;
        DVB_TDA10021 = no;
        DVB_TDA10023 = no;
        DVB_VES1820 = no;
        DVB_AU8522 = no;
        DVB_AU8522_DTV = no;
        DVB_AU8522_V4L = no;
        DVB_BCM3510 = no;
        DVB_LG2160 = no;
        DVB_LGDT3305 = no;
        DVB_LGDT3306A = no;
        DVB_LGDT330X = no;
        DVB_MXL692 = no;
        DVB_NXT200X = no;
        DVB_OR51132 = no;
        DVB_OR51211 = no;
        DVB_S5H1409 = no;
        DVB_S5H1411 = no;
        DVB_DIB8000 = no;
        DVB_MB86A20S = no;
        DVB_S921 = no;
        DVB_MN88443X = no;
        DVB_TC90522 = no;
        DVB_PLL = no;
        DVB_TUNER_DIB0070 = no;
        DVB_TUNER_DIB0090 = no;
        DVB_A8293 = no;
        DVB_AF9033 = no;
        DVB_ASCOT2E = no;
        DVB_ATBM8830 = no;
        DVB_HELENE = no;
        DVB_HORUS3A = no;
        DVB_ISL6405 = no;
        DVB_ISL6421 = no;
        DVB_ISL6423 = no;
        DVB_IX2505V = no;
        DVB_LGS8GL5 = no;
        DVB_LGS8GXX = no;
        DVB_LNBH25 = no;
        DVB_LNBH29 = no;
        DVB_LNBP21 = no;
        DVB_LNBP22 = no;
        DVB_M88RS2000 = no;
        DVB_TDA665x = no;
        DVB_DRX39XYJ = no;
        DVB_CXD2099 = no;
        DVB_SP2 = no;
        DVB_DUMMY_FE = no;
        VIDEO_GO7007 = no;
        VIDEO_HDPVR = no;
        VIDEO_PVRUSB2 = no;
        VIDEO_STK1160 = no;
        VIDEO_AU0828 = no;
        VIDEO_CX231XX = no;
      })
      (definePatch "rm-dallas-1wire" {
        W1_MASTER_AMD_AXI = no;
        W1_MASTER_MATROX = no;
        W1_MASTER_DS2490 = no;
        W1_MASTER_DS2482 = no;
        W1_MASTER_SGI = no;

        W1_SLAVE_DS2405 = no;
        W1_SLAVE_DS2408 = no;
        W1_SLAVE_DS2413 = no;
        W1_SLAVE_DS2406 = no;
        W1_SLAVE_DS2423 = no;
        W1_SLAVE_DS2805 = no;
        W1_SLAVE_DS2430 = no;
        W1_SLAVE_DS2431 = no;
        W1_SLAVE_DS2433 = no;
        W1_SLAVE_DS2438 = no;
        W1_SLAVE_DS250X = no;
        W1_SLAVE_DS28E04 = no;
      })
      (definePatch "rm-watchdog-timers" {

        LENOVO_SE10_WDT = no;
        LENOVO_SE30_WDT = no;
        ZIIRAVE_WATCHDOG = no;
        MAX63XX_WATCHDOG = no;
        ACQUIRE_WDT = no;
        ADVANTECH_WDT = no;
        ADVANTECH_EC_WDT = no;
        ALIM1535_WDT = no;
        ALIM7101_WDT = no;
        EBC_C384_WDT = no;
        EXAR_WDT = no;
        F71808E_WDT = no;
        SP5100_TCO = no;
        SBC_FITPC2_WATCHDOG = no;
        EUROTECH_WDT = no;
        IB700_WDT = no;
        IBMASR = no;
        WAFER_WDT = no;
        I6300ESB_WDT = no;
        IE6XX_WDT = no;
        ITCO_WDT = no;
        IT8712F_WDT = no;
        IT87_WDT = no;
        HP_WATCHDOG = no;
        HPWDT_NMI_DECODING = no;
        SC1200_WDT = no;
        PC87413_WDT = no;
        NV_TCO = no;
        "60XX_WDT" = no;
        SMSC_SCH311X_WDT = no;
        SMSC37B787_WDT = no;
        TQMX86_WDT = no;
        VIA_WDT = no;
        W83627HF_WDT = no;
        W83877F_WDT = no;
        W83977F_WDT = no;
        MACHZ_WDT = no;
        SBC_EPX_C3_WATCHDOG = no;
        MEN_A21_WDT = no;

        PCIPCWATCHDOG = no;
        WDTPCI = no;

        USBPCWATCHDOG = no;
      })
      (definePatch "rm-multifunction-device" {
        MFD_ADP5585 = no;
        MFD_ACT8945A = no;
        MFD_AS3711 = no;
        MFD_SMPRO = no;
        MFD_AS3722 = no;
        PMIC_ADP5520 = no;
        MFD_AAT2870_CORE = no;
        MFD_ATMEL_FLEXCOM = no;
        MFD_ATMEL_HLCDC = no;
        CONFIG_MFD_BCM590XX = no;
        MFD_BD9571MWV = no;
        MFD_AXP20X_I2C = no;
        MFD_CGBC = no;
        MFD_CS40L50_I2C = no;
        MFD_CS40L50_SPI = no;
        MFD_CS42L43_I2C = no;
        MFD_LOCHNAGAR = no;
        MFD_MADERA = no;
        PMIC_DA903X = no;
        MFD_DA9052_SPI = no;
        MFD_DA9052_I2C = no;
        MFD_DA9055 = no;
        MFD_DA9062 = no;
        MFD_DA9063 = no;
        MFD_DA9150 = no;
        MFD_DLN2 = no;
        MFD_GATEWORKS_GSC = no;
        MFD_MC13XXX_SPI = no;
        MFD_MC13XXX_I2C = no;
        MFD_MP2629 = no;
        MFD_HI6421_PMIC = no;
        MFD_HI6421_SPMI = no;
        MFD_INTEL_QUARK_I2C_GPIO = no;
        LPC_ICH = no;
        LPC_SCH = no;
        MFD_INTEL_LPSS_PCI = no;
        MFD_IQS62X = no;
        MFD_JANZ_CMODIO = no;
        MFD_KEMPLD = no;
        MFD_88PM800 = no;
        MFD_88PM805 = no;
        MFD_88PM860X = no;
        MFD_88PM886_PMIC = no;
        MFD_MAX5970 = no;
        MFD_MAX14577 = no;
        MFD_MAX77541 = no;
        MFD_MAX77620 = no;
        MFD_MAX77650 = no;
        MFD_MAX77686 = no;
        MFD_MAX77693 = no;
        MFD_MAX77705 = no;
        MFD_MAX77714 = no;
        MFD_MAX77759 = no;
        MFD_MAX77843 = no;
        MFD_MAX8907 = no;
        MFD_MAX8925 = no;
        MFD_MAX8997 = no;
        MFD_MAX8998 = no;
        MFD_MT6360 = no;
        MFD_MT6370 = no;
        MFD_MT6397 = no;
        MFD_MENF21BMC = no;
        MFD_NCT6694 = no;
        MFD_OCELOT = no;
        EZX_PCAP = no;
        MFD_CPCAP = no;
        MFD_VIPERBOARD = no;
        MFD_NTXEC = no;
        MFD_RETU = no;
        MFD_SY7636A = no;
        CONFIG_MFD_RDC321X = no;
        MFD_RT4831 = no;
        MFD_RT5033 = no;
        MFD_RT5120 = no;
        MFD_RC5T583 = no;
        MFD_RK8XX_I2C = no;
        MFD_RK8XX_SPI = no;
        MFD_RN5T618 = no;
        MFD_SEC_I2C = no;
        MFD_SI476X_CORE = no;
        MFD_SM501 = no;
        MFD_SKY81452 = no;
        MFD_STMPE = no;
        MFD_LP3943 = no;
        MFD_LP8788 = no;
        MFD_TI_LMU = no;
        MFD_BQ257XX = no;
        MFD_PALMAS = no;
        TPS6105X = no;
        TPS65010 = no;
        TPS6507X = no;
        MFD_TPS65086 = no;
        MFD_TPS65090 = no;
        MFD_TPS65217 = no;
        MFD_TI_LP873X = no;
        MFD_TI_LP87565 = no;
        MFD_TPS65218 = no;
        MFD_TPS65219 = no;
        MFD_TPS6586X = no;
        MFD_TPS65910 = no;
        MFD_TPS65912_I2C = no;
        MFD_TPS65912_SPI = no;
        MFD_TPS6594_I2C = no;
        MFD_TPS6594_SPI = no;
        TWL4030_CORE = no;
        TWL6040_CORE = no;
        MFD_WL1273_CORE = no;
        MFD_LM3533 = no;
        MFD_TC3589X = no;
        MFD_TQMX86 = no;
        MFD_VX855 = no;
        GPIO_VX855 = no;
        MFD_ARIZONA_I2C = no;
        MFD_ARIZONA_SPI = no;
        MFD_WM8400 = no;
        MFD_WM831X_I2C = no;
        MFD_WM831X_SPI = no;
        MFD_WM8350_I2C = no;
        MFD_WM8994 = no;
        MFD_ROHM_BD718XX = no;
        MFD_ROHM_BD71828 = no;
        MFD_ROHM_BD957XMUF = no;
        MFD_ROHM_BD96801 = no;
        MFD_STPMIC1 = no;
        CONFIG_MFD_STMFX = no;
        PINCTRL_STMFX = no;
        MFD_ATC260X_I2C = no;
        MFD_QCOM_PM8008 = no;
        RAVE_SP_CORE = no;
        MFD_INTEL_M10_BMC_SPI = no;
        MFD_QNAP_MCU = no;
        MFD_RSMU_I2C = no;
        MFD_RSMU_SPI = no;
        MFD_MAX7360 = no;
      })
      (definePatch "rm-specific-regulators" {
        REGULATOR_88PG86X = no;
        REGULATOR_ACT8865 = no;
        REGULATOR_AD5398 = no;
        REGULATOR_ADP5055 = no;
        REGULATOR_AW37503 = no;
        REGULATOR_BCM590XX = no;
        REGULATOR_DA9121 = no;
        REGULATOR_DA9210 = no;
        REGULATOR_DA9211 = no;
        REGULATOR_FAN53555 = no;
        REGULATOR_FAN53880 = no;
        REGULATOR_ISL9305 = no;
        REGULATOR_ISL6271A = no;
        REGULATOR_LP3971 = no;
        REGULATOR_LP3972 = no;
        REGULATOR_LP872X = no;
        REGULATOR_LP8755 = no;
        REGULATOR_LTC3589 = no;
        REGULATOR_LTC3676 = no;
        REGULATOR_MAX1586 = no;
        REGULATOR_MAX77503 = no;
        REGULATOR_MAX77857 = no;
        REGULATOR_MAX8649 = no;
        REGULATOR_MAX8660 = no;
        REGULATOR_MAX8893 = no;
        REGULATOR_MAX8952 = no;
        REGULATOR_MAX8973 = no;
        REGULATOR_MAX20086 = no;
        REGULATOR_MAX20411 = no;
        REGULATOR_MAX77826 = no;
        REGULATOR_MAX77838 = no;
        REGULATOR_MCP16502 = no;
        REGULATOR_MP5416 = no;
        REGULATOR_MP8859 = no;
        REGULATOR_MP886X = no;
        REGULATOR_MPQ7920 = no;
        REGULATOR_MT6311 = no;
        REGULATOR_MT6315 = no;
        REGULATOR_PCA9450 = no;
        REGULATOR_PF9453 = no;
        REGULATOR_PF0900 = no;
        REGULATOR_PF530X = no;
        REGULATOR_PF8X00 = no;
        REGULATOR_PFUZE100 = no;
        REGULATOR_PV88060 = no;
        REGULATOR_PV88080 = no;
        REGULATOR_PV88090 = no;
        REGULATOR_QCOM_SPMI = no;
        REGULATOR_QCOM_USB_VBUS = no;
        REGULATOR_RAA215300 = no;
        REGULATOR_RASPBERRYPI_TOUCHSCREEN_ATTINY = no;
        REGULATOR_RASPBERRYPI_TOUCHSCREEN_V2 = no;
        REGULATOR_RT4801 = no;
        REGULATOR_RT4803 = no;
        REGULATOR_RT5133 = no;
        REGULATOR_RT5190A = no;
        REGULATOR_RT5739 = no;
        REGULATOR_RT5759 = no;
        REGULATOR_RT6160 = no;
        REGULATOR_RT6190 = no;
        REGULATOR_RT6245 = no;
        REGULATOR_RTQ2134 = no;
        REGULATOR_RTMV20 = no;
        REGULATOR_RTQ6752 = no;
        REGULATOR_RTQ2208 = no;
        REGULATOR_SLG51000 = no;
        REGULATOR_SY8106A = no;
        REGULATOR_SY8824X = no;
        REGULATOR_SY8827N = no;
        REGULATOR_TPS51632 = no;
        REGULATOR_TPS62360 = no;
        REGULATOR_TPS6286X = no;
        REGULATOR_TPS6287X = no;
        REGULATOR_TPS65023 = no;
        REGULATOR_TPS6507X = no;
        REGULATOR_TPS65132 = no;
        REGULATOR_TPS6524X = no;
        REGULATOR_QCOM_LABIBB = no;
      })
      (definePatch "rm-specific-graphics-drm" {
        DRM_KOMEDA = no;

        DRM_RADEON = no;
        DRM_AMDGPU = no;
        DRM_NOUVEAU = no;
        DRM_I915 = mkForce no;
        DRM_XE = no;
        DRM_VGEM = no;
        DRM_VKMS = no;
        DRM_GMA500 = no;
        DRM_UDL = no;
        DRM_AST = no;
        DRM_MGAG200 = no;
        DRM_QXL = no;

        DRM_PANEL_ABT_Y030XX067A = no;
        DRM_PANEL_ARM_VERSATILE = no;
        DRM_PANEL_AUO_A030JTN01 = no;
        DRM_PANEL_LVDS = no;
        DRM_PANEL_ILITEK_IL9322 = no;
        DRM_PANEL_ILITEK_ILI9341 = no;
        DRM_PANEL_INNOLUX_EJ030NA = no;
        DRM_PANEL_LG_LB035Q02 = no;
        DRM_PANEL_LG_LG4573 = no;
        DRM_PANEL_NEC_NL8048HL11 = no;
        DRM_PANEL_NEWVISION_NV3052C = no;
        DRM_PANEL_NOVATEK_NT39016 = no;
        DRM_PANEL_OLIMEX_LCD_OLINUXINO = no;
        DRM_PANEL_ORISETECH_OTA5601A = no;
        DRM_PANEL_SAMSUNG_S6E88A0_AMS452EF01 = no;
        DRM_PANEL_SAMSUNG_ATNA33XC20 = no;
        DRM_PANEL_SAMSUNG_DB7430 = no;
        DRM_PANEL_SAMSUNG_LD9040 = no;
        DRM_PANEL_SAMSUNG_S6D27A1 = no;
        DRM_PANEL_SAMSUNG_S6D7AA0 = no;
        DRM_PANEL_SAMSUNG_S6E63M0 = no;
        DRM_PANEL_SAMSUNG_S6E8AA0 = no;
        DRM_PANEL_SEIKO_43WVF1G = no;
        DRM_PANEL_SHARP_LS037V7DW01 = no;
        DRM_PANEL_SITRONIX_ST7701 = no;
        DRM_PANEL_SITRONIX_ST7789V = no;
        DRM_PANEL_SONY_ACX565AKM = no;
        DRM_PANEL_EDP = no;
        DRM_PANEL_SIMPLE = no;
        DRM_PANEL_TPO_TD028TTEC1 = no;
        DRM_PANEL_TPO_TD043MTEA1 = no;
        DRM_PANEL_TPO_TPG110 = no;
        DRM_PANEL_WIDECHIPS_WS2401 = no;

        DRM_CHIPONE_ICN6211 = no;
        DRM_CHRONTEL_CH7033 = no;
        DRM_DISPLAY_CONNECTOR = no;
        DRM_I2C_NXP_TDA998X = no;
        DRM_ITE_IT6263 = no;
        DRM_ITE_IT6505 = no;
        DRM_LONTIUM_LT8912B = no;
        DRM_LONTIUM_LT9211 = no;
        DRM_LONTIUM_LT9611 = no;
        DRM_LONTIUM_LT9611UXC = no;
        DRM_ITE_IT66121 = no;
        DRM_LVDS_CODEC = no;
        DRM_MEGACHIPS_STDPXXXX_GE_B850V3_FW = no;
        DRM_NWL_MIPI_DSI = no;
        DRM_NXP_PTN3460 = no;
        DRM_PARADE_PS8622 = no;
        DRM_PARADE_PS8640 = no;
        DRM_SAMSUNG_DSIM = no;
        DRM_SIL_SII8620 = no;
        DRM_SII902X = no;
        DRM_SII9234 = no;
        DRM_SIMPLE_BRIDGE = no;
        DRM_SOLOMON_SSD2825 = no;
        DRM_THINE_THC63LVD1024 = no;
        DRM_TOSHIBA_TC358762 = no;
        DRM_TOSHIBA_TC358764 = no;
        DRM_TOSHIBA_TC358767 = no;
        DRM_TOSHIBA_TC358768 = no;
        DRM_TOSHIBA_TC358775 = no;
        DRM_TI_DLPC3433 = no;
        DRM_TI_TDP158 = no;
        DRM_TI_TFP410 = no;
        DRM_TI_SN65DSI83 = no;
        DRM_TI_SN65DSI86 = no;
        DRM_TI_TPD12S015 = no;
        DRM_WAVESHARE_BRIDGE = no;
        DRM_ANALOGIX_ANX6345 = no;
        DRM_ANALOGIX_ANX78XX = no;
        DRM_ANALOGIX_ANX7625 = no;
        DRM_I2C_ADV7511 = no;
        DRM_CDNS_DSI = no;
        DRM_CDNS_MHDP8546 = no;
        # end of Display Interface Bridges

        DRM_ETNAVIV = no;
        DRM_HISI_HIBMC = no;
        DRM_LOGICVC = no;
        DRM_APPLETBDRM = no;
        DRM_ARCPGU = no;
        DRM_BOCHS = no;
        DRM_CIRRUS_QEMU = no;
        DRM_GM12U320 = no;
        DRM_PANEL_MIPI_DBI = no;
        DRM_PIXPAPER = no;
        TINYDRM_HX8357D = no;
        TINYDRM_ILI9163 = no;
        TINYDRM_ILI9225 = no;
        TINYDRM_ILI9341 = no;
        TINYDRM_ILI9486 = no;
        TINYDRM_MI0283QT = no;
        TINYDRM_REPAPER = no;
        TINYDRM_SHARP_MEMORY = no;
        DRM_VBOXVIDEO = no;
        DRM_GUD = no;
        DRM_ST7571_I2C = no;
        DRM_ST7586 = no;
        DRM_ST7735R = no;
        DRM_SSD130X = no;

        FB = no;
      })
      (definePatch "rm-specific-backlight-lcd" {
        LCD_CLASS_DEVICE = no;
        BACKLIGHT_KTD253 = no;
        BACKLIGHT_KTD2801 = no;
        BACKLIGHT_KTZ8866 = no;
        BACKLIGHT_QCOM_WLED = no;
        BACKLIGHT_SAHARA = no;
        BACKLIGHT_ADP8860 = no;
        BACKLIGHT_ADP8870 = no;
        BACKLIGHT_LM3509 = no;
        BACKLIGHT_LM3630A = no;
        BACKLIGHT_LM3639 = no;
        BACKLIGHT_LP855X = no;
        BACKLIGHT_MP3309C = no;
        BACKLIGHT_LV5207LP = no;
        BACKLIGHT_BD6107 = no;
        BACKLIGHT_ARCXCNN = no;
      })
      (definePatch "rm-specific-battery-sensors" {
        IP5XXX_POWER = no;
        TEST_POWER = no;
        CHARGER_ADP5061 = no;
        BATTERY_CHAGALL = no;
        BATTERY_CW2015 = no;
        BATTERY_DS2760 = no;
        BATTERY_DS2780 = no;
        BATTERY_DS2781 = no;
        BATTERY_DS2782 = no;
        BATTERY_HUAWEI_GAOKUN = no;
        BATTERY_LENOVO_YOGA_C630 = no;
        BATTERY_SAMSUNG_SDI = no;
        BATTERY_SBS = no;
        CHARGER_SBS = no;
        MANAGER_SBS = no;
        BATTERY_BQ27XXX = no;
        BATTERY_BQ27XXX_I2C = no;
        BATTERY_BQ27XXX_HDQ = no;
        BATTERY_BQ27XXX_DT_UPDATES_NVM = no;
        BATTERY_MAX17042 = no;
        BATTERY_MAX1720X = no;
        BATTERY_MAX1721X = no;
        CHARGER_ISP1704 = no;
        CHARGER_MAX8903 = no;
        CHARGER_LP8727 = no;
        CHARGER_GPIO = no;
        CHARGER_MANAGER = no;
        CHARGER_LT3651 = no;
        CHARGER_LTC4162L = no;
        CHARGER_DETECTOR_MAX14656 = no;
        CHARGER_MAX77976 = no;
        CHARGER_MAX8971 = no;
        CHARGER_QCOM_SMBB = no;
        BATTERY_PM8916_BMS_VM = no;
        CHARGER_PM8916_LBC = no;
        CHARGER_BQ2415X = no;
        CHARGER_BQ24190 = no;
        CHARGER_BQ24257 = no;
        CHARGER_BQ24735 = no;
        CHARGER_BQ2515X = no;
        CHARGER_BQ25890 = no;
        CHARGER_BQ25980 = no;
        CHARGER_BQ256XX = no;
        CHARGER_SMB347 = no;
        BATTERY_GAUGE_LTC2941 = no;
        BATTERY_GOLDFISH = no;
        BATTERY_RT5033 = no;
        CHARGER_RT9455 = no;
        CHARGER_RT9467 = no;
        CHARGER_RT9471 = no;
        CHARGER_SC2731 = no;
        FUEL_GAUGE_STC3117 = no;
        CHARGER_UCS1002 = no;
        CHARGER_BD99954 = no;
        BATTERY_SURFACE = no;
        CHARGER_SURFACE = no;
        BATTERY_UG3105 = no;
        FUEL_GAUGE_MM8013 = no;

        SENSORS_AD7314 = no;
        SENSORS_AD7414 = no;
        SENSORS_AD7418 = no;
        SENSORS_ADM1025 = no;
        SENSORS_ADM1026 = no;
        SENSORS_ADM1029 = no;
        SENSORS_ADM1031 = no;
        SENSORS_ADM1177 = no;
        SENSORS_ADM9240 = no;
        SENSORS_ADT7X10 = no;
        SENSORS_ADT7310 = no;
        SENSORS_ADT7410 = no;
        SENSORS_ADT7411 = no;
        SENSORS_ADT7462 = no;
        SENSORS_ADT7470 = no;
        SENSORS_ADT7475 = no;
        SENSORS_AHT10 = no;
        SENSORS_AQUACOMPUTER_D5NEXT = no;
        SENSORS_AS370 = no;
        SENSORS_ASC7621 = no;
        SENSORS_ASUS_ROG_RYUJIN = no;
        SENSORS_AXI_FAN_CONTROL = no;
        SENSORS_ARM_SCMI = no;
        SENSORS_ARM_SCPI = no;
        SENSORS_ATXP1 = no;
        SENSORS_CHIPCAP2 = no;
        SENSORS_CORSAIR_CPRO = no;
        SENSORS_CORSAIR_PSU = no;
        SENSORS_DRIVETEMP = no;
        SENSORS_DS620 = no;
        SENSORS_DS1621 = no;
        SENSORS_I5K_AMB = no;
        SENSORS_SPARX5 = no;
        SENSORS_F71805F = no;
        SENSORS_F71882FG = no;
        SENSORS_F75375S = no;
        SENSORS_MC33XS2410 = no;
        SENSORS_FTSTEUTATES = no;
        SENSORS_GIGABYTE_WATERFORCE = no;
        SENSORS_GL518SM = no;
        SENSORS_GL520SM = no;
        SENSORS_G760A = no;
        SENSORS_G762 = no;
        SENSORS_GPIO_FAN = no;
        SENSORS_HIH6130 = no;
        SENSORS_HS3001 = no;
        SENSORS_HTU31 = no;
        SENSORS_IBMAEM = no;
        SENSORS_IBMPEX = no;
        SENSORS_ISL28022 = no;
        SENSORS_IT87 = no;
        SENSORS_JC42 = no;
        SENSORS_POWERZ = no;
        SENSORS_POWR1220 = no;
        SENSORS_LINEAGE = no;
        SENSORS_LTC2945 = no;
        SENSORS_LTC2947 = no;
        SENSORS_LTC2947_I2C = no;
        SENSORS_LTC2947_SPI = no;
        SENSORS_LTC2990 = no;
        SENSORS_LTC2991 = no;
        SENSORS_LTC2992 = no;
        SENSORS_LTC4151 = no;
        SENSORS_LTC4215 = no;
        SENSORS_LTC4222 = no;
        SENSORS_LTC4245 = no;
        SENSORS_LTC4260 = no;
        SENSORS_LTC4261 = no;
        SENSORS_LTC4282 = no;
        SENSORS_MAX1111 = no;
        SENSORS_MAX127 = no;
        SENSORS_MAX16065 = no;
        SENSORS_MAX1619 = no;
        SENSORS_MAX1668 = no;
        SENSORS_MAX197 = no;
        SENSORS_MAX31722 = no;
        SENSORS_MAX31730 = no;
        SENSORS_MAX31760 = no;
        MAX31827 = no;
        SENSORS_MAX6620 = no;
        SENSORS_MAX6621 = no;
        SENSORS_MAX6639 = no;
        SENSORS_MAX6650 = no;
        SENSORS_MAX6697 = no;
        SENSORS_MAX31790 = no;
        SENSORS_MC34VR500 = no;
        SENSORS_MCP3021 = no;
        SENSORS_TC654 = no;
        SENSORS_TPS23861 = no;
        SENSORS_MR75203 = no;
        SENSORS_ADCXX = no;
        SENSORS_LM63 = no;
        SENSORS_LM70 = no;
        SENSORS_LM73 = no;
        SENSORS_LM75 = no;
        SENSORS_LM77 = no;
        SENSORS_LM78 = no;
        SENSORS_LM80 = no;
        SENSORS_LM83 = no;
        SENSORS_LM85 = no;
        SENSORS_LM87 = no;
        SENSORS_LM90 = no;
        SENSORS_LM92 = no;
        SENSORS_LM93 = no;
        SENSORS_LM95234 = no;
        SENSORS_LM95241 = no;
        SENSORS_LM95245 = no;
        SENSORS_PC87360 = no;
        SENSORS_PC87427 = no;
        SENSORS_NCT6683 = no;
        SENSORS_NCT6775_CORE = no;
        SENSORS_NCT6775 = no;
        SENSORS_NCT6775_I2C = no;
        SENSORS_NCT7363 = no;
        SENSORS_NCT7802 = no;
        SENSORS_NCT7904 = no;
        SENSORS_NPCM7XX = no;
        SENSORS_NZXT_KRAKEN2 = no;
        SENSORS_NZXT_KRAKEN3 = no;
        SENSORS_NZXT_SMART2 = no;
        SENSORS_OCC_P8_I2C = no;
        SENSORS_OCC = no;
        SENSORS_PCF8591 = no;
        SENSORS_PECI_CPUTEMP = no;
        SENSORS_PECI_DIMMTEMP = no;
        SENSORS_PECI = no;
        PMBUS = no;
        SENSORS_PMBUS = no;
        SENSORS_ACBEL_FSG032 = no;
        SENSORS_ADM1266 = no;
        SENSORS_ADM1275 = no;
        SENSORS_ADP1050 = no;
        SENSORS_ADP1050_REGULATOR = no;
        SENSORS_BEL_PFE = no;
        SENSORS_BPA_RS600 = no;
        SENSORS_CRPS = no;
        SENSORS_DELTA_AHE50DC_FAN = no;
        SENSORS_FSP_3Y = no;
        SENSORS_IBM_CFFPS = no;
        SENSORS_DPS920AB = no;
        SENSORS_INA233 = no;
        SENSORS_INSPUR_IPSPS = no;
        SENSORS_IR35221 = no;
        SENSORS_IR36021 = no;
        SENSORS_IR38064 = no;
        SENSORS_IR38064_REGULATOR = no;
        SENSORS_IRPS5401 = no;
        SENSORS_ISL68137 = no;
        SENSORS_LM25066 = no;
        SENSORS_LM25066_REGULATOR = no;
        SENSORS_LT3074 = no;
        SENSORS_LT3074_REGULATOR = no;
        SENSORS_LT7182S = no;
        SENSORS_LTC2978 = no;
        SENSORS_LTC2978_REGULATOR = no;
        SENSORS_LTC3815 = no;
        SENSORS_LTC4286 = no;
        SENSORS_MAX15301 = no;
        SENSORS_MAX16064 = no;
        SENSORS_MAX16601 = no;
        SENSORS_MAX20730 = no;
        SENSORS_MAX20751 = no;
        SENSORS_MAX31785 = no;
        SENSORS_MAX34440 = no;
        SENSORS_MAX8688 = no;
        SENSORS_MP2856 = no;
        SENSORS_MP2869 = no;
        SENSORS_MP2888 = no;
        SENSORS_MP2891 = no;
        SENSORS_MP29502 = no;
        SENSORS_MP2975 = no;
        SENSORS_MP2993 = no;
        SENSORS_MP2975_REGULATOR = no;
        SENSORS_MP5023 = no;
        SENSORS_MP5920 = no;
        SENSORS_MP5990 = no;
        SENSORS_MP9941 = no;
        SENSORS_MPQ7932_REGULATOR = no;
        SENSORS_MPQ7932 = no;
        SENSORS_MPQ8785 = no;
        SENSORS_PIM4328 = no;
        SENSORS_PLI1209BC = no;
        SENSORS_PLI1209BC_REGULATOR = no;
        SENSORS_PM6764TR = no;
        SENSORS_PXE1610 = no;
        SENSORS_Q54SJ108A2 = no;
        SENSORS_STPDDC60 = no;
        SENSORS_TDA38640 = no;
        SENSORS_TDA38640_REGULATOR = no;
        SENSORS_TPS25990 = no;
        SENSORS_TPS25990_REGULATOR = no;
        SENSORS_TPS40422 = no;
        SENSORS_TPS53679 = no;
        SENSORS_TPS546D24 = no;
        SENSORS_UCD9000 = no;
        SENSORS_UCD9200 = no;
        SENSORS_XDP710 = no;
        SENSORS_XDPE152 = no;
        SENSORS_XDPE122 = no;
        SENSORS_XDPE122_REGULATOR = no;
        SENSORS_ZL6100 = no;
        SENSORS_PT5161L = no;
        SENSORS_PWM_FAN = no;
        SENSORS_SA67MCU = no;
        SENSORS_SL28CPLD = no;
        SENSORS_SBTSI = no;
        SENSORS_SHT15 = no;
        SENSORS_SHT21 = no;
        SENSORS_SHT3x = no;
        SENSORS_SHT4x = no;
        SENSORS_SHTC1 = no;
        SENSORS_SIS5595 = no;
        SENSORS_DME1737 = no;
        SENSORS_EMC1403 = no;
        SENSORS_EMC2103 = no;
        SENSORS_EMC2305 = no;
        SENSORS_EMC6W201 = no;
        SENSORS_SMSC47M1 = no;
        SENSORS_SMSC47M192 = no;
        SENSORS_SMSC47B397 = no;
        SENSORS_SCH56XX_COMMON = no;
        SENSORS_SCH5627 = no;
        SENSORS_SCH5636 = no;
        SENSORS_STTS751 = no;
        SENSORS_SG2042_MCU = no;
        SENSORS_SURFACE_FAN = no;
        SENSORS_SURFACE_TEMP = no;
        SENSORS_ADC128D818 = no;
        SENSORS_ADS7828 = no;
        SENSORS_ADS7871 = no;
        SENSORS_AMC6821 = no;
        SENSORS_INA209 = no;
        SENSORS_INA2XX = no;
        SENSORS_INA238 = no;
        SENSORS_INA3221 = no;
        SENSORS_SPD5118 = no;
        SENSORS_SPD5118_DETECT = no;
        SENSORS_TC74 = no;
        SENSORS_THMC50 = no;
        SENSORS_TMP102 = no;
        SENSORS_TMP103 = no;
        SENSORS_TMP108 = no;
        SENSORS_TMP401 = no;
        SENSORS_TMP421 = no;
        SENSORS_TMP464 = no;
        SENSORS_TMP513 = no;
        SENSORS_VEXPRESS = no;
        SENSORS_VIA686A = no;
        SENSORS_VT1211 = no;
        SENSORS_VT8231 = no;
        SENSORS_W83773G = no;
        SENSORS_W83781D = no;
        SENSORS_W83791D = no;
        SENSORS_W83792D = no;
        SENSORS_W83793 = no;
        SENSORS_W83795 = no;
        SENSORS_W83795_FANCTRL = no;
        SENSORS_W83L785TS = no;
        SENSORS_W83L786NG = no;
        SENSORS_W83627HF = no;
        SENSORS_W83627EHF = no;
        SENSORS_XGENE = no;
      })
      (definePatch "rm-specific-rtc-clocks" {
        RTC_DRV_ABB5ZES3 = no;
        RTC_DRV_ABEOZ9 = no;
        RTC_DRV_ABX80X = no;
        RTC_DRV_AC100 = no;
        RTC_DRV_BRCMSTB = no;
        RTC_DRV_DS1307 = no;
        RTC_DRV_DS1307_CENTURY = no;
        RTC_DRV_DS1374 = no;
        RTC_DRV_DS1374_WDT = no;
        RTC_DRV_DS1672 = no;
        RTC_DRV_HYM8563 = no;
        RTC_DRV_MAX6900 = no;
        RTC_DRV_MAX31335 = no;
        RTC_DRV_NCT3018Y = no;
        RTC_DRV_RS5C372 = no;
        RTC_DRV_ISL1208 = no;
        RTC_DRV_ISL12022 = no;
        RTC_DRV_ISL12026 = no;
        RTC_DRV_X1205 = no;
        RTC_DRV_PCF8523 = no;
        RTC_DRV_PCF85363 = no;
        RTC_DRV_PCF8563 = no;
        RTC_DRV_PCF8583 = no;
        RTC_DRV_M41T80 = no;
        RTC_DRV_M41T80_WDT = no;
        RTC_DRV_BQ32K = no;
        RTC_DRV_S35390A = no;
        RTC_DRV_FM3130 = no;
        RTC_DRV_RX8010 = no;
        RTC_DRV_RX8111 = no;
        RTC_DRV_RX8581 = no;
        RTC_DRV_RX8025 = no;
        RTC_DRV_EM3027 = no;
        RTC_DRV_RV3028 = no;
        RTC_DRV_RV3032 = no;
        RTC_DRV_RV8803 = no;
        RTC_DRV_S5M = no;
        RTC_DRV_SD2405AL = no;
        RTC_DRV_SD3078 = no;

        #
        # SPI RTC drivers
        #
        RTC_DRV_M41T93 = no;
        RTC_DRV_M41T94 = no;
        RTC_DRV_DS1302 = no;
        RTC_DRV_DS1305 = no;
        RTC_DRV_DS1343 = no;
        RTC_DRV_DS1347 = no;
        RTC_DRV_DS1390 = no;
        RTC_DRV_MAX6916 = no;
        RTC_DRV_R9701 = no;
        RTC_DRV_RX4581 = no;
        RTC_DRV_RS5C348 = no;
        RTC_DRV_MAX6902 = no;
        RTC_DRV_PCF2123 = no;
        RTC_DRV_MCP795 = no;
        RTC_I2C_AND_SPI = no;

        #
        # SPI and I2C RTC drivers
        #
        RTC_DRV_DS3232 = no;
        RTC_DRV_DS3232_HWMON = no;
        RTC_DRV_PCF2127 = no;
        RTC_DRV_PCF85063 = no;
        RTC_DRV_RV3029C2 = no;
        RTC_DRV_RV3029_HWMON = no;
        RTC_DRV_RX6110 = no;

        #
        # Platform RTC drivers
        #
        RTC_DRV_DS1286 = no;
        RTC_DRV_DS1511 = no;
        RTC_DRV_DS1553 = no;
        RTC_DRV_DS1685_FAMILY = no;
        RTC_DRV_DS1685 = no;
        RTC_DRV_DS1689 = no;
        RTC_DRV_DS17285 = no;
        RTC_DRV_DS17485 = no;
        RTC_DRV_DS17885 = no;
        RTC_DRV_DS1742 = no;
        RTC_DRV_DS2404 = no;
        RTC_DRV_EFI = no;
        RTC_DRV_STK17TA8 = no;
        RTC_DRV_M48T86 = no;
        RTC_DRV_M48T35 = no;
        RTC_DRV_M48T59 = no;
        RTC_DRV_MSM6242 = no;
        RTC_DRV_RP5C01 = no;
        RTC_DRV_SC27XX = no;
        RTC_DRV_OPTEE = no;
        RTC_DRV_ZYNQMP = no;

        #
        # on-CPU RTC drivers
        #
        RTC_DRV_CV1800 = no;
        RTC_DRV_IMXDI = no;
        RTC_DRV_FSL_FTM_ALARM = no;
        RTC_DRV_MESON_VRTC = no;
        RTC_DRV_S3C = no;
        RTC_DRV_SH = no;
        RTC_DRV_PL030 = no;
        RTC_DRV_PL031 = no;
        RTC_DRV_SUN6I = no;
        RTC_DRV_MV = no;
        RTC_DRV_ARMADA38X = no;
        RTC_DRV_CADENCE = no;
        RTC_DRV_FTRTC010 = no;
        RTC_DRV_PM8XXX = no;
        RTC_DRV_TEGRA = no;
        RTC_DRV_MXC = no;
        RTC_DRV_MXC_V2 = no;
        RTC_DRV_SNVS = no;
        RTC_DRV_BBNSM = no;
        RTC_DRV_IMX_BBM_SCMI = no;
        RTC_DRV_IMX_SC = no;
        RTC_DRV_MT2712 = no;
        RTC_DRV_MT7622 = no;
        RTC_DRV_XGENE = no;
        RTC_DRV_R7301 = no;
        RTC_DRV_STM32 = no;
        RTC_DRV_RTD119X = no;
        RTC_DRV_TI_K3 = no;
        RTC_DRV_MA35D1 = no;
        RTC_DRV_RENESAS_RTCA3 = no;
        RTC_DRV_GOLDFISH = no;
        RTC_DRV_AMLOGIC_A4 = no;
        RTC_DRV_S32G = no;
      })
      (definePatch "rm-specific-hw-clocks" {
        CLK_VEXPRESS_OSC = no;
        # end of Clock driver for ARM Reference designs

        LMK04832 = no;
        COMMON_CLK_APPLE_NCO = no;
        COMMON_CLK_MAX9485 = no;
        COMMON_CLK_HI655X = no;
        COMMON_CLK_SCMI = no;
        COMMON_CLK_SCPI = no;
        COMMON_CLK_SI5341 = no;
        COMMON_CLK_SI5351 = no;
        COMMON_CLK_SI514 = no;
        COMMON_CLK_SI544 = no;
        COMMON_CLK_SI570 = no;
        COMMON_CLK_CDCE706 = no;
        COMMON_CLK_CDCE925 = no;
        COMMON_CLK_CS2000_CP = no;
        COMMON_CLK_EN7523 = no;
        COMMON_CLK_FSL_FLEXSPI = no;
        COMMON_CLK_FSL_SAI = no;
        COMMON_CLK_S2MPS11 = no;
        COMMON_CLK_AXI_CLKGEN = no;
        CLK_QORIQ = no;
        CLK_LS1028A_PLLDIG = no;
        COMMON_CLK_XGENE = no;
        COMMON_CLK_NPCM8XX = no;
        COMMON_CLK_RS9_PCIE = no;
        COMMON_CLK_SI521XX = no;
        COMMON_CLK_VC3 = no;
        COMMON_CLK_VC5 = no;
        COMMON_CLK_VC7 = no;
        # CONFIG_COMMON_CLK_FIXED_MMIO is not set
        CLK_OWL_S500 = no;
        CLK_OWL_S700 = no;
        CLK_OWL_S900 = no;
        CLK_BCM_63XX = no;
        COMMON_CLK_IPROC = no;
        CLK_BCM_NS2 = no;
        CLK_BCM_SR = no;
        COMMON_CLK_HI3516CV300 = no;
        COMMON_CLK_HI3519 = no;
        COMMON_CLK_HI3559A = no;
        COMMON_CLK_HI3660 = no;
        COMMON_CLK_HI3670 = no;
        COMMON_CLK_HI3798CV200 = no;
        COMMON_CLK_HI6220 = no;
        RESET_HISI = no;
        STUB_CLK_HI6220 = no;
        STUB_CLK_HI3660 = no;
        MXC_CLK = no;
        MXC_CLK_SCU = no;
        CLK_IMX8MM = no;
        CLK_IMX8MN = no;
        CLK_IMX8MP = no;
        CLK_IMX8MQ = no;
        CLK_IMX8QXP = no;
        CLK_IMX8ULP = no;
        CLK_IMX93 = no;
        CLK_IMX95_BLK_CTL = no;
        TI_SCI_CLK = no;
        # CONFIG_TI_SCI_CLK_PROBE_FROM_FW is not set
        TI_SYSCON_CLK = no;

        #
        # Clock driver for MediaTek SoC
        #
        COMMON_CLK_MEDIATEK = no;
        COMMON_CLK_MEDIATEK_FHCTL = no;
        COMMON_CLK_MT2712 = no;
        COMMON_CLK_MT2712_BDPSYS = no;
        COMMON_CLK_MT2712_IMGSYS = no;
        COMMON_CLK_MT2712_JPGDECSYS = no;
        COMMON_CLK_MT2712_MFGCFG = no;
        COMMON_CLK_MT2712_MMSYS = no;
        COMMON_CLK_MT2712_VDECSYS = no;
        COMMON_CLK_MT2712_VENCSYS = no;
        COMMON_CLK_MT6735 = no;
        COMMON_CLK_MT6735_IMGSYS = no;
        COMMON_CLK_MT6735_MFGCFG = no;
        COMMON_CLK_MT6735_VDECSYS = no;
        COMMON_CLK_MT6735_VENCSYS = no;
        COMMON_CLK_MT6765 = no;
        COMMON_CLK_MT6765_AUDIOSYS = no;
        COMMON_CLK_MT6765_CAMSYS = no;
        COMMON_CLK_MT6765_GCESYS = no;
        COMMON_CLK_MT6765_MMSYS = no;
        COMMON_CLK_MT6765_IMGSYS = no;
        COMMON_CLK_MT6765_VCODECSYS = no;
        COMMON_CLK_MT6765_MFGSYS = no;
        COMMON_CLK_MT6765_MIPI0ASYS = no;
        COMMON_CLK_MT6765_MIPI0BSYS = no;
        COMMON_CLK_MT6765_MIPI1ASYS = no;
        COMMON_CLK_MT6765_MIPI1BSYS = no;
        COMMON_CLK_MT6765_MIPI2ASYS = no;
        COMMON_CLK_MT6765_MIPI2BSYS = no;
        COMMON_CLK_MT6779 = no;
        COMMON_CLK_MT6779_MMSYS = no;
        COMMON_CLK_MT6779_IMGSYS = no;
        COMMON_CLK_MT6779_IPESYS = no;
        COMMON_CLK_MT6779_CAMSYS = no;
        COMMON_CLK_MT6779_VDECSYS = no;
        COMMON_CLK_MT6779_VENCSYS = no;
        COMMON_CLK_MT6779_MFGCFG = no;
        COMMON_CLK_MT6779_AUDSYS = no;
        COMMON_CLK_MT6795 = no;
        COMMON_CLK_MT6795_MFGCFG = no;
        COMMON_CLK_MT6795_MMSYS = no;
        COMMON_CLK_MT6795_VDECSYS = no;
        COMMON_CLK_MT6795_VENCSYS = no;
        COMMON_CLK_MT6797 = no;
        COMMON_CLK_MT6797_MMSYS = no;
        COMMON_CLK_MT6797_IMGSYS = no;
        COMMON_CLK_MT6797_VDECSYS = no;
        COMMON_CLK_MT6797_VENCSYS = no;
        COMMON_CLK_MT7622 = no;
        COMMON_CLK_MT7622_ETHSYS = no;
        COMMON_CLK_MT7622_HIFSYS = no;
        COMMON_CLK_MT7622_AUDSYS = no;
        COMMON_CLK_MT7981 = no;
        COMMON_CLK_MT7981_ETHSYS = no;
        COMMON_CLK_MT7986 = no;
        COMMON_CLK_MT7986_ETHSYS = no;
        COMMON_CLK_MT7988 = no;
        COMMON_CLK_MT8167 = no;
        COMMON_CLK_MT8167_AUDSYS = no;
        COMMON_CLK_MT8167_IMGSYS = no;
        COMMON_CLK_MT8167_MFGCFG = no;
        COMMON_CLK_MT8167_MMSYS = no;
        COMMON_CLK_MT8167_VDECSYS = no;
        COMMON_CLK_MT8173 = no;
        COMMON_CLK_MT8173_IMGSYS = no;
        COMMON_CLK_MT8173_MMSYS = no;
        COMMON_CLK_MT8173_VDECSYS = no;
        COMMON_CLK_MT8173_VENCSYS = no;
        COMMON_CLK_MT8183 = no;
        COMMON_CLK_MT8183_AUDIOSYS = no;
        COMMON_CLK_MT8183_CAMSYS = no;
        COMMON_CLK_MT8183_IMGSYS = no;
        COMMON_CLK_MT8183_IPU_CORE0 = no;
        COMMON_CLK_MT8183_IPU_CORE1 = no;
        COMMON_CLK_MT8183_IPU_ADL = no;
        COMMON_CLK_MT8183_IPU_CONN = no;
        COMMON_CLK_MT8183_MFGCFG = no;
        COMMON_CLK_MT8183_MMSYS = no;
        COMMON_CLK_MT8183_VDECSYS = no;
        COMMON_CLK_MT8183_VENCSYS = no;
        COMMON_CLK_MT8186 = no;
        COMMON_CLK_MT8186_CAMSYS = no;
        COMMON_CLK_MT8186_IMGSYS = no;
        COMMON_CLK_MT8186_IPESYS = no;
        COMMON_CLK_MT8186_WPESYS = no;
        COMMON_CLK_MT8186_IMP_IIC_WRAP = no;
        COMMON_CLK_MT8186_MCUSYS = no;
        COMMON_CLK_MT8186_MDPSYS = no;
        COMMON_CLK_MT8186_MFGCFG = no;
        COMMON_CLK_MT8186_MMSYS = no;
        COMMON_CLK_MT8186_VDECSYS = no;
        COMMON_CLK_MT8186_VENCSYS = no;
        COMMON_CLK_MT8188 = no;
        COMMON_CLK_MT8188_ADSP_AUDIO26M = no;
        COMMON_CLK_MT8188_CAMSYS = no;
        COMMON_CLK_MT8188_IMGSYS = no;
        COMMON_CLK_MT8188_IMP_IIC_WRAP = no;
        COMMON_CLK_MT8188_IPESYS = no;
        COMMON_CLK_MT8188_MFGCFG = no;
        COMMON_CLK_MT8188_VDECSYS = no;
        COMMON_CLK_MT8188_VDOSYS = no;
        COMMON_CLK_MT8188_VENCSYS = no;
        COMMON_CLK_MT8188_VPPSYS = no;
        COMMON_CLK_MT8188_WPESYS = no;
        COMMON_CLK_MT8192 = no;
        COMMON_CLK_MT8192_AUDSYS = no;
        COMMON_CLK_MT8192_CAMSYS = no;
        COMMON_CLK_MT8192_IMGSYS = no;
        COMMON_CLK_MT8192_IMP_IIC_WRAP = no;
        COMMON_CLK_MT8192_IPESYS = no;
        COMMON_CLK_MT8192_MDPSYS = no;
        COMMON_CLK_MT8192_MFGCFG = no;
        COMMON_CLK_MT8192_MMSYS = no;
        COMMON_CLK_MT8192_MSDC = no;
        COMMON_CLK_MT8192_SCP_ADSP = no;
        COMMON_CLK_MT8192_VDECSYS = no;
        COMMON_CLK_MT8192_VENCSYS = no;
        COMMON_CLK_MT8195 = no;
        COMMON_CLK_MT8195_APUSYS = no;
        COMMON_CLK_MT8195_IMP_IIC_WRAP = no;
        COMMON_CLK_MT8195_MFGCFG = no;
        COMMON_CLK_MT8195_SCP_ADSP = no;
        COMMON_CLK_MT8195_VDOSYS = no;
        COMMON_CLK_MT8195_VPPSYS = no;
        COMMON_CLK_MT8195_CAMSYS = no;
        COMMON_CLK_MT8195_IMGSYS = no;
        COMMON_CLK_MT8195_IPESYS = no;
        COMMON_CLK_MT8195_WPESYS = no;
        COMMON_CLK_MT8195_VDECSYS = no;
        COMMON_CLK_MT8195_VENCSYS = no;
        COMMON_CLK_MT8196 = no;
        COMMON_CLK_MT8196_IMP_IIC_WRAP = no;
        COMMON_CLK_MT8196_MCUSYS = no;
        COMMON_CLK_MT8196_MDPSYS = no;
        COMMON_CLK_MT8196_MFGCFG = no;
        COMMON_CLK_MT8196_MMSYS = no;
        COMMON_CLK_MT8196_PEXTPSYS = no;
        COMMON_CLK_MT8196_UFSSYS = no;
        COMMON_CLK_MT8196_VDECSYS = no;
        COMMON_CLK_MT8196_VENCSYS = no;
        COMMON_CLK_MT8365 = no;
        COMMON_CLK_MT8365_APU = no;
        COMMON_CLK_MT8365_CAM = no;
        COMMON_CLK_MT8365_MFG = no;
        COMMON_CLK_MT8365_MMSYS = no;
        COMMON_CLK_MT8365_VDEC = no;
        COMMON_CLK_MT8365_VENC = no;
        COMMON_CLK_MT8516 = no;
        COMMON_CLK_MT8516_AUDSYS = no;
        # end of Clock driver for MediaTek SoC

        #
        # Clock support for Amlogic platforms
        #
        COMMON_CLK_MESON_REGMAP = no;
        COMMON_CLK_MESON_DUALDIV = no;
        COMMON_CLK_MESON_MPLL = no;
        COMMON_CLK_MESON_PHASE = no;
        COMMON_CLK_MESON_PLL = no;
        COMMON_CLK_MESON_SCLK_DIV = no;
        COMMON_CLK_MESON_VID_PLL_DIV = no;
        COMMON_CLK_MESON_VCLK = no;
        COMMON_CLK_MESON_CLKC_UTILS = no;
        COMMON_CLK_MESON_AO_CLKC = no;
        COMMON_CLK_MESON_CPU_DYNDIV = no;
        COMMON_CLK_GXBB = no;
        COMMON_CLK_AXG = no;
        COMMON_CLK_AXG_AUDIO = no;
        COMMON_CLK_A1_PLL = no;
        COMMON_CLK_A1_PERIPHERALS = no;
        COMMON_CLK_C3_PLL = no;
        COMMON_CLK_C3_PERIPHERALS = no;
        COMMON_CLK_G12A = no;
        COMMON_CLK_S4_PLL = no;
        COMMON_CLK_S4_PERIPHERALS = no;
        # end of Clock support for Amlogic platforms

        ARMADA_AP_CP_HELPER = no;
        ARMADA_37XX_CLK = no;
        ARMADA_AP806_SYSCON = no;
        ARMADA_AP_CPU_CLK = no;
        ARMADA_CP110_SYSCON = no;
        COMMON_CLK_NUVOTON = no;
        CLK_MA35D1 = no;
        QCOM_GDSC = no;
        COMMON_CLK_QCOM = no;
        CLK_GLYMUR_DISPCC = no;
        CLK_GLYMUR_GCC = no;
        CLK_GLYMUR_TCSRCC = no;
        CLK_X1E80100_CAMCC = no;
        CLK_X1E80100_DISPCC = no;
        CLK_X1E80100_GCC = no;
        CLK_X1E80100_GPUCC = no;
        CLK_X1E80100_TCSRCC = no;
        CLK_X1P42100_GPUCC = no;
        CLK_QCM2290_GPUCC = no;
        QCOM_A53PLL = no;
        QCOM_A7PLL = no;
        QCOM_CLK_APCS_MSM8916 = no;
        QCOM_CLK_APCC_MSM8996 = no;
        QCOM_CLK_RPM = no;
        QCOM_CLK_SMD_RPM = no;
        QCOM_CLK_RPMH = no;
        IPQ_APSS_PLL = no;
        IPQ_APSS_5424 = no;
        IPQ_APSS_6018 = no;
        IPQ_CMN_PLL = no;
        IPQ_GCC_4019 = no;
        IPQ_GCC_5018 = no;
        IPQ_GCC_5332 = no;
        IPQ_GCC_5424 = no;
        IPQ_GCC_6018 = no;
        IPQ_GCC_8074 = no;
        IPQ_GCC_9574 = no;
        IPQ_NSSCC_9574 = no;
        IPQ_NSSCC_QCA8K = no;
        MSM_GCC_8916 = no;
        MSM_GCC_8917 = no;
        MSM_GCC_8939 = no;
        MSM_GCC_8953 = no;
        MSM_GCC_8976 = no;
        MSM_MMCC_8994 = no;
        MSM_GCC_8994 = no;
        MSM_GCC_8996 = no;
        MSM_MMCC_8996 = no;
        MSM_GCC_8998 = no;
        MSM_GPUCC_8998 = no;
        MSM_MMCC_8998 = no;
        QCM_GCC_2290 = no;
        QCM_DISPCC_2290 = no;
        QCS_DISPCC_615 = no;
        QCS_CAMCC_615 = no;
        QCS_GCC_404 = no;
        SA_CAMCC_8775P = no;
        QCS_GCC_8300 = no;
        QCS_GCC_615 = no;
        QCS_GPUCC_615 = no;
        QCS_VIDEOCC_615 = no;
        SC_CAMCC_7180 = no;
        SC_CAMCC_7280 = no;
        SC_CAMCC_8180X = no;
        SC_CAMCC_8280XP = no;
        SA_DISPCC_8775P = no;
        SC_DISPCC_7180 = no;
        SC_DISPCC_7280 = no;
        SC_DISPCC_8280XP = no;
        SA_GCC_8775P = no;
        SA_GPUCC_8775P = no;
        SAR_GCC_2130P = no;
        SAR_GPUCC_2130P = no;
        SC_GCC_7180 = no;
        SC_GCC_7280 = no;
        SC_GCC_8180X = no;
        SC_GCC_8280XP = no;
        SC_GPUCC_7180 = no;
        SC_GPUCC_7280 = no;
        SC_GPUCC_8280XP = no;
        SC_LPASSCC_7280 = no;
        SC_LPASSCC_8280XP = no;
        SC_LPASS_CORECC_7180 = no;
        SC_LPASS_CORECC_7280 = no;
        SC_VIDEOCC_7180 = no;
        SC_VIDEOCC_7280 = no;
        SDM_CAMCC_845 = no;
        SDM_GCC_660 = no;
        SDM_MMCC_660 = no;
        SDM_GPUCC_660 = no;
        QCS_TURING_404 = no;
        QCS_Q6SSTOP_404 = no;
        QDU_GCC_1000 = no;
        QDU_ECPRICC_1000 = no;
        SDM_GCC_845 = no;
        SDM_GPUCC_845 = no;
        SDM_VIDEOCC_845 = no;
        SDM_DISPCC_845 = no;
        SDM_LPASSCC_845 = no;
        SDX_GCC_75 = no;
        SM_CAMCC_4450 = no;
        SM_CAMCC_6350 = no;
        SM_CAMCC_7150 = no;
        SM_CAMCC_MILOS = no;
        SM_CAMCC_8150 = no;
        SM_CAMCC_8250 = no;
        SM_CAMCC_8450 = no;
        SM_CAMCC_8550 = no;
        SM_CAMCC_8650 = no;
        SM_DISPCC_4450 = no;
        SM_DISPCC_6115 = no;
        SM_DISPCC_6125 = no;
        SM_DISPCC_7150 = no;
        SM_DISPCC_8250 = no;
        SM_DISPCC_6350 = no;
        SM_DISPCC_6375 = no;
        SM_DISPCC_MILOS = no;
        SM_DISPCC_8450 = no;
        SM_DISPCC_8550 = no;
        SM_DISPCC_8750 = no;
        SM_GCC_4450 = no;
        SM_GCC_6115 = no;
        SM_GCC_6125 = no;
        SM_GCC_6350 = no;
        SM_GCC_6375 = no;
        SM_GCC_7150 = no;
        SM_GCC_MILOS = no;
        SM_GCC_8150 = no;
        SM_GCC_8250 = no;
        SM_GCC_8350 = no;
        SM_GCC_8450 = no;
        SM_GCC_8550 = no;
        SM_GCC_8650 = no;
        SM_GCC_8750 = no;
        SM_GPUCC_4450 = no;
        SM_GPUCC_6115 = no;
        SM_GPUCC_6125 = no;
        SM_GPUCC_6375 = no;
        SM_GPUCC_6350 = no;
        SM_GPUCC_MILOS = no;
        SM_GPUCC_8150 = no;
        SM_GPUCC_8250 = no;
        SM_GPUCC_8350 = no;
        SM_GPUCC_8450 = no;
        SM_GPUCC_8550 = no;
        SM_GPUCC_8650 = no;
        SM_LPASSCC_6115 = no;
        SM_TCSRCC_8550 = no;
        SM_TCSRCC_8650 = no;
        SM_TCSRCC_8750 = no;
        SA_VIDEOCC_8775P = no;
        SM_VIDEOCC_6350 = no;
        SM_VIDEOCC_7150 = no;
        SM_VIDEOCC_MILOS = no;
        SM_VIDEOCC_8150 = no;
        SM_VIDEOCC_8250 = no;
        SM_VIDEOCC_8350 = no;
        SM_VIDEOCC_8550 = no;
        SPMI_PMIC_CLKDIV = no;
        QCOM_HFPLL = no;
        KPSS_XCC = no;
        CLK_GFM_LPASS_SM8250 = no;
        SM_VIDEOCC_8450 = no;
        CLK_RENESAS = no;
        CLK_R8A774A1 = no;
        CLK_R8A774B1 = no;
        CLK_R8A774C0 = no;
        CLK_R8A774E1 = no;
        CLK_R8A7795 = no;
        CLK_R8A77960 = no;
        CLK_R8A77961 = no;
        CLK_R8A77965 = no;
        CLK_R8A77970 = no;
        CLK_R8A77980 = no;
        CLK_R8A77990 = no;
        CLK_R8A77995 = no;
        CLK_R8A779A0 = no;
        CLK_R8A779F0 = no;
        CLK_R8A779G0 = no;
        CLK_R8A779H0 = no;
        CLK_R9A07G043 = no;
        CLK_R9A07G044 = no;
        CLK_R9A07G054 = no;
        CLK_R9A08G045 = no;
        CLK_R9A09G011 = no;
        CLK_R9A09G047 = no;
        CLK_R9A09G056 = no;
        CLK_R9A09G057 = no;
        CLK_R9A09G077 = no;
        CLK_R9A09G087 = no;
        CLK_RCAR_CPG_LIB = no;
        CLK_RCAR_GEN3_CPG = no;
        CLK_RCAR_GEN4_CPG = no;
        CLK_RCAR_USB2_CLOCK_SEL = no;
        CLK_RZG2L = no;
        CLK_RZV2H = no;
        CLK_RENESAS_VBATTB = no;
        CLK_RENESAS_CPG_MSSR = no;
        CLK_RENESAS_DIV6 = no;
        COMMON_CLK_ROCKCHIP = no;
        CLK_PX30 = no;
        CLK_RK3308 = no;
        CLK_RK3328 = no;
        CLK_RK3368 = no;
        CLK_RK3399 = no;
        CLK_RK3528 = no;
        CLK_RK3562 = no;
        CLK_RK3568 = no;
        CLK_RK3576 = no;
        CLK_RK3588 = no;
        COMMON_CLK_SAMSUNG = no;
        EXYNOS_ARM64_COMMON_CLK = no;
        EXYNOS_AUDSS_CLK_CON = no;
        EXYNOS_CLKOUT = no;
        TESLA_FSD_COMMON_CLK = no;
        CLK_INTEL_SOCFPGA = no;
        CLK_INTEL_SOCFPGA64 = no;
        CLK_SOPHGO_CV1800 = no;
        CLK_SOPHGO_SG2042_PLL = no;
        CLK_SOPHGO_SG2042_CLKGEN = no;
        CLK_SOPHGO_SG2042_RPGATE = no;
        CLK_SOPHGO_SG2044 = no;
        CLK_SOPHGO_SG2044_PLL = no;
        SPRD_COMMON_CLK = no;
        SPRD_SC9860_CLK = no;
        SPRD_SC9863A_CLK = no;
        SPRD_UMS512_CLK = no;
        SUNXI_CCU = no;
        SUN50I_A64_CCU = no;
        SUN50I_A100_CCU = no;
        SUN50I_A100_R_CCU = no;
        SUN50I_H6_CCU = no;
        SUN50I_H616_CCU = no;
        SUN50I_H6_R_CCU = no;
        SUN55I_A523_CCU = no;
        SUN55I_A523_MCU_CCU = no;
        SUN55I_A523_R_CCU = no;
        SUN6I_RTC_CCU = no;
        SUN8I_H3_CCU = no;
        SUN8I_DE2_CCU = mkForce no;
        SUN8I_R_CCU = no;
        CLK_TEGRA_BPMP = no;
        TEGRA_CLK_DFLL = no;
        COMMON_CLK_STM32MP = no;
        COMMON_CLK_STM32MP215 = no;
        COMMON_CLK_STM32MP257 = no;
        CLK_UNIPHIER = no;
        COMMON_CLK_VISCONTI = no;
        XILINX_VCU = no;
        COMMON_CLK_XLNX_CLKWZRD = no;
        COMMON_CLK_ZYNQMP = no;

        HWSPINLOCK = no;
        HWSPINLOCK_OMAP = no;
        HWSPINLOCK_QCOM = no;
        HWSPINLOCK_SPRD = no;
        HWSPINLOCK_SUN6I = no;

        #
        # Clock Source drivers
        #

        OMAP_DM_TIMER = no;
        DW_APB_TIMER = no;
        DW_APB_TIMER_OF = no;
        ROCKCHIP_TIMER = no;
        OWL_TIMER = no;
        SUN4I_TIMER = no;
        TEGRA_TIMER = no;
        TEGRA186_TIMER = no;
        NPCM7XX_TIMER = no;
        CLKSRC_STM32_LP = no;
        FSL_ERRATUM_A008585 = no;
        HISILICON_ERRATUM_161010101 = no;
        SUN50I_ERRATUM_UNKNOWN1 = no;
        CLKSRC_EXYNOS_MCT = no;
        SYS_SUPPORTS_SH_CMT = no;
        MTK_TIMER = no;
        MTK_CPUX_TIMER = no;
        SPRD_TIMER = no;
        SH_TIMER_CMT = no;
        RENESAS_OSTM = no;
        TIMER_IMX_SYS_CTR = no;
        # CONFIG_NXP_STM_TIMER is not set
        # end of Clock Source drivers
      })
      (definePatch "rm-specific-pinctrl" {
        PINCTRL_AMD = mkForce no;
        PINCTRL_APPLE_GPIO = no;
        PINCTRL_AXP209 = no;
        PINCTRL_AW9523 = no;
        PINCTRL_CY8C95X0 = no;
        PINCTRL_KEEMBAY = no;
        PINCTRL_MCP23S08_I2C = no;
        PINCTRL_MCP23S08_SPI = no;
        PINCTRL_MCP23S08 = no;
        PINCTRL_MICROCHIP_SGPIO = no;
        PINCTRL_OCELOT = no;
        PINCTRL_ROCKCHIP = no;
        PINCTRL_SCMI = no;
        # CONFIG_PINCTRL_STMFX is not set
        PINCTRL_SX150X = no;
        PINCTRL_ZYNQMP = no;
        PINCTRL_RP1 = no;
        PINCTRL_OWL = no;
        PINCTRL_S700 = no;
        PINCTRL_S900 = no;
        # PINCTRL_BCM2835 = no;
        PINCTRL_BCM4908 = no;
        PINCTRL_BRCMSTB = no;
        PINCTRL_BCM2712 = no;
        PINCTRL_IPROC_GPIO = no;
        PINCTRL_NS2_MUX = no;
        # CONFIG_PINCTRL_AS370 is not set
        # CONFIG_PINCTRL_BERLIN_BG4CT is not set
        PINCTRL_IMX = no;
        PINCTRL_IMX_SCMI = no;
        PINCTRL_IMX_SCU = no;
        PINCTRL_IMX8MM = no;
        PINCTRL_IMX8MN = no;
        PINCTRL_IMX8MP = no;
        PINCTRL_IMX8MQ = no;
        PINCTRL_IMX8QM = no;
        PINCTRL_IMX8QXP = no;
        PINCTRL_IMX8DXL = no;
        PINCTRL_IMX8ULP = no;
        PINCTRL_IMX91 = no;
        PINCTRL_IMX93 = no;

        #
        # MediaTek pinctrl drivers
        #
        EINT_MTK = no;
        PINCTRL_MTK = no;
        PINCTRL_MTK_V2 = no;
        PINCTRL_MTK_MOORE = no;
        PINCTRL_MTK_PARIS = no;
        PINCTRL_AIROHA = no;
        PINCTRL_MT2712 = no;
        PINCTRL_MT6765 = no;
        PINCTRL_MT6779 = no;
        PINCTRL_MT6795 = no;
        PINCTRL_MT6797 = no;
        PINCTRL_MT6893 = no;
        PINCTRL_MT7622 = no;
        PINCTRL_MT7981 = no;
        PINCTRL_MT7986 = no;
        PINCTRL_MT7988 = no;
        PINCTRL_MT8167 = no;
        PINCTRL_MT8173 = no;
        PINCTRL_MT8183 = no;
        PINCTRL_MT8186 = no;
        PINCTRL_MT8188 = no;
        PINCTRL_MT8189 = no;
        PINCTRL_MT8192 = no;
        PINCTRL_MT8195 = no;
        PINCTRL_MT8196 = no;
        PINCTRL_MT8365 = no;
        PINCTRL_MT8516 = no;
        # end of MediaTek pinctrl drivers

        PINCTRL_MESON = no;
        PINCTRL_MESON_GXBB = no;
        PINCTRL_MESON_GXL = no;
        PINCTRL_MESON8_PMX = no;
        PINCTRL_MESON_AXG = no;
        PINCTRL_MESON_AXG_PMX = no;
        PINCTRL_MESON_G12A = no;
        PINCTRL_MESON_A1 = no;
        PINCTRL_MESON_S4 = no;
        PINCTRL_AMLOGIC_A4 = no;
        PINCTRL_AMLOGIC_C3 = no;
        PINCTRL_AMLOGIC_T7 = no;
        PINCTRL_MVEBU = no;
        PINCTRL_ARMADA_AP806 = no;
        PINCTRL_ARMADA_CP110 = no;
        PINCTRL_AC5 = no;
        PINCTRL_ARMADA_37XX = no;
        PINCTRL_NPCM8XX = no;
        # CONFIG_PINCTRL_MA35D1 is not set
        # CONFIG_PINCTRL_S32G2 is not set
        PINCTRL_MSM = no;
        PINCTRL_GLYMUR = no;
        PINCTRL_IPQ5018 = no;
        PINCTRL_IPQ5332 = no;
        PINCTRL_IPQ5424 = no;
        PINCTRL_IPQ8074 = no;
        PINCTRL_IPQ6018 = no;
        PINCTRL_IPQ9574 = no;
        PINCTRL_MDM9607 = no;
        PINCTRL_MSM8916 = no;
        PINCTRL_MSM8917 = no;
        PINCTRL_MSM8953 = no;
        PINCTRL_MSM8976 = no;
        PINCTRL_MSM8994 = no;
        PINCTRL_MSM8996 = no;
        PINCTRL_MSM8998 = no;
        PINCTRL_QCM2290 = no;
        PINCTRL_QCS404 = no;
        PINCTRL_QCS615 = no;
        PINCTRL_QCS8300 = no;
        PINCTRL_QDF2XXX = no;
        PINCTRL_QDU1000 = no;
        PINCTRL_SA8775P = no;
        PINCTRL_SAR2130P = no;
        PINCTRL_SC7180 = no;
        PINCTRL_SC7280 = no;
        PINCTRL_SC8180X = no;
        PINCTRL_SC8280XP = no;
        PINCTRL_SDM660 = no;
        PINCTRL_SDM670 = no;
        PINCTRL_SDM845 = no;
        PINCTRL_SDX75 = no;
        PINCTRL_SM4450 = no;
        PINCTRL_SM6115 = no;
        PINCTRL_SM6125 = no;
        PINCTRL_SM6350 = no;
        PINCTRL_SM6375 = no;
        PINCTRL_SM7150 = no;
        PINCTRL_MILOS = no;
        PINCTRL_SM8150 = no;
        PINCTRL_SM8250 = no;
        PINCTRL_SM8350 = no;
        PINCTRL_SM8450 = no;
        PINCTRL_SM8550 = no;
        PINCTRL_SM8650 = no;
        PINCTRL_SM8750 = no;
        PINCTRL_X1E80100 = no;
        PINCTRL_QCOM_SPMI_PMIC = no;
        PINCTRL_QCOM_SSBI_PMIC = no;
        PINCTRL_LPASS_LPI = no;
        PINCTRL_SC7280_LPASS_LPI = no;
        PINCTRL_SDM660_LPASS_LPI = no;
        PINCTRL_SM4250_LPASS_LPI = no;
        PINCTRL_SM6115_LPASS_LPI = no;
        PINCTRL_SM8250_LPASS_LPI = no;
        PINCTRL_SM8450_LPASS_LPI = no;
        PINCTRL_SC8280XP_LPASS_LPI = no;
        PINCTRL_SM8550_LPASS_LPI = no;
        PINCTRL_SM8650_LPASS_LPI = no;
        PINCTRL_RTD = no;
        PINCTRL_RTD1619B = no;
        PINCTRL_RTD1319D = no;
        PINCTRL_RTD1315E = no;

        #
        # Renesas pinctrl drivers
        #
        PINCTRL_RENESAS = no;
        PINCTRL_SH_PFC = no;
        PINCTRL_PFC_R8A774A1 = no;
        PINCTRL_PFC_R8A774B1 = no;
        PINCTRL_PFC_R8A774C0 = no;
        PINCTRL_PFC_R8A774E1 = no;
        PINCTRL_PFC_R8A77951 = no;
        PINCTRL_PFC_R8A77960 = no;
        PINCTRL_PFC_R8A77961 = no;
        PINCTRL_PFC_R8A77965 = no;
        PINCTRL_PFC_R8A77970 = no;
        PINCTRL_PFC_R8A77980 = no;
        PINCTRL_PFC_R8A77990 = no;
        PINCTRL_PFC_R8A77995 = no;
        PINCTRL_PFC_R8A779A0 = no;
        PINCTRL_PFC_R8A779F0 = no;
        PINCTRL_PFC_R8A779G0 = no;
        PINCTRL_PFC_R8A779H0 = no;
        PINCTRL_RZG2L = no;
        PINCTRL_RZT2H = no;
        PINCTRL_RZV2M = no;
        # end of Renesas pinctrl drivers

        PINCTRL_SAMSUNG = no;
        PINCTRL_EXYNOS = no;
        PINCTRL_EXYNOS_ARM64 = no;
        PINCTRL_SOPHGO_COMMON = no;
        PINCTRL_SOPHGO_CV18XX_OPS = no;
        PINCTRL_SOPHGO_CV1800B = no;
        PINCTRL_SOPHGO_CV1812H = no;
        PINCTRL_SOPHGO_SG2000 = no;
        PINCTRL_SOPHGO_SG2002 = no;
        PINCTRL_SOPHGO_SG2042_OPS = no;
        PINCTRL_SOPHGO_SG2042 = no;
        PINCTRL_SOPHGO_SG2044 = no;
        PINCTRL_SPRD = no;
        PINCTRL_SPRD_SC9860 = no;
        PINCTRL_STM32 = no;
        PINCTRL_STM32MP257 = no;
        PINCTRL_STM32_HDP = no;
        PINCTRL_SUNXI = no;
        # CONFIG_PINCTRL_SUN4I_A10 is not set
        # CONFIG_PINCTRL_SUN5I is not set
        # CONFIG_PINCTRL_SUN6I_A31 is not set
        # CONFIG_PINCTRL_SUN6I_A31_R is not set
        # CONFIG_PINCTRL_SUN8I_A23 is not set
        # CONFIG_PINCTRL_SUN8I_A33 is not set
        # CONFIG_PINCTRL_SUN8I_A83T is not set
        # CONFIG_PINCTRL_SUN8I_A83T_R is not set
        # CONFIG_PINCTRL_SUN8I_A23_R is not set
        # CONFIG_PINCTRL_SUN8I_H3 is not set
        PINCTRL_SUN8I_H3_R = no;
        # CONFIG_PINCTRL_SUN8I_V3S is not set
        # CONFIG_PINCTRL_SUN9I_A80 is not set
        # CONFIG_PINCTRL_SUN9I_A80_R is not set
        # CONFIG_PINCTRL_SUN20I_D1 is not set
        PINCTRL_SUN50I_A64 = no;
        PINCTRL_SUN50I_A64_R = no;
        PINCTRL_SUN50I_A100 = no;
        PINCTRL_SUN50I_A100_R = no;
        PINCTRL_SUN50I_H5 = no;
        PINCTRL_SUN50I_H6 = no;
        PINCTRL_SUN50I_H6_R = no;
        PINCTRL_SUN50I_H616 = no;
        PINCTRL_SUN50I_H616_R = no;
        PINCTRL_SUN55I_A523 = no;
        PINCTRL_SUN55I_A523_R = no;
        PINCTRL_TEGRA = no;
        PINCTRL_TEGRA124 = no;
        PINCTRL_TEGRA210 = no;
        PINCTRL_TEGRA186 = no;
        PINCTRL_TEGRA194 = no;
        PINCTRL_TEGRA234 = no;
        PINCTRL_TEGRA_XUSB = no;
        PINCTRL_UNIPHIER = no;
        # CONFIG_PINCTRL_UNIPHIER_LD4 is not set
        # CONFIG_PINCTRL_UNIPHIER_PRO4 is not set
        # CONFIG_PINCTRL_UNIPHIER_SLD8 is not set
        # CONFIG_PINCTRL_UNIPHIER_PRO5 is not set
        # CONFIG_PINCTRL_UNIPHIER_PXS2 is not set
        # CONFIG_PINCTRL_UNIPHIER_LD6B is not set
        PINCTRL_UNIPHIER_LD11 = no;
        PINCTRL_UNIPHIER_LD20 = no;
        PINCTRL_UNIPHIER_PXS3 = no;
        PINCTRL_UNIPHIER_NX1 = no;
        PINCTRL_VISCONTI = no;
        PINCTRL_TMPV7700 = no;
      })
      (definePatch "rm-specific-serial" {

        #
        # Serial drivers
        #
        SERIAL_8250_DEPRECATED_OPTIONS = no;
        SERIAL_8250_16550A_VARIANTS = no;
        # CONFIG_SERIAL_8250_FINTEK is not set
        # CONFIG_SERIAL_8250_MANY_PORTS is not set
        # CONFIG_SERIAL_8250_DETECT_IRQ is not set
        # CONFIG_SERIAL_8250_RSA is not set
        SERIAL_8250_DWLIB = no;
        # SERIAL_8250_BCM2835AUX = no;
        SERIAL_8250_FSL = no;
        SERIAL_8250_DW = no;
        SERIAL_8250_EM = no;
        # CONFIG_SERIAL_8250_RT288X is not set
        SERIAL_8250_OMAP = no;
        SERIAL_8250_OMAP_TTYO_FIXUP = no;
        SERIAL_8250_MT6577 = no;
        SERIAL_8250_UNIPHIER = no;
        SERIAL_8250_PERICOM = no;
        SERIAL_8250_TEGRA = no;
        SERIAL_8250_BCM7271 = no;
        SERIAL_OF_PLATFORM = no;

        #
        # Non-8250 serial port support
        #
        SERIAL_AMBA_PL010 = no;
        SERIAL_AMBA_PL011 = no;
        SERIAL_AMBA_PL011_CONSOLE = no;
        # CONFIG_SERIAL_EARLYCON_SEMIHOST is not set
        # CONFIG_SERIAL_ATMEL is not set
        SERIAL_MESON = no;
        SERIAL_MESON_CONSOLE = no;
        SERIAL_SAMSUNG = no;
        SERIAL_SAMSUNG_CONSOLE = no;
        SERIAL_TEGRA = no;
        SERIAL_TEGRA_TCU = no;
        SERIAL_TEGRA_TCU_CONSOLE = no;
        SERIAL_TEGRA_UTC = no;
        SERIAL_TEGRA_UTC_CONSOLE = no;
        SERIAL_MAX3100 = no;
        SERIAL_MAX310X = no;
        SERIAL_IMX = no;
        SERIAL_IMX_CONSOLE = no;
        SERIAL_IMX_EARLYCON = no;
        SERIAL_UARTLITE = no;
        SERIAL_SH_SCI = no;
        SERIAL_SH_SCI_CONSOLE = no;
        SERIAL_SH_SCI_EARLYCON = no;
        SERIAL_SH_SCI_DMA = no;
        SERIAL_RSCI = no;
        SERIAL_JSM = no;
        SERIAL_MSM = no;
        SERIAL_MSM_CONSOLE = no;
        SERIAL_QCOM_GENI = no;
        SERIAL_QCOM_GENI_CONSOLE = no;
        SERIAL_SIFIVE = no;
        SERIAL_SCCNXP = no;
        SERIAL_SC16IS7XX = no;
        SERIAL_SC16IS7XX_I2C = no;
        SERIAL_SC16IS7XX_SPI = no;
        SERIAL_BCM63XX = no;
        # CONFIG_SERIAL_BCM63XX_CONSOLE is not set
        SERIAL_ALTERA_JTAGUART = no;
        SERIAL_ALTERA_UART = no;
        SERIAL_XILINX_PS_UART = no;
        SERIAL_XILINX_PS_UART_CONSOLE = no;
        SERIAL_ARC = no;
        SERIAL_RP2 = no;
        SERIAL_FSL_LPUART = no;
        SERIAL_FSL_LPUART_CONSOLE = no;
        SERIAL_FSL_LINFLEXUART = no;
        SERIAL_FSL_LINFLEXUART_CONSOLE = no;
        SERIAL_CONEXANT_DIGICOLOR = no;
        SERIAL_SPRD = no;
        SERIAL_STM32 = no;
        SERIAL_STM32_CONSOLE = no;
        SERIAL_MVEBU_UART = no;
        SERIAL_MVEBU_CONSOLE = no;
        SERIAL_OWL = no;
        SERIAL_OWL_CONSOLE = no;
        SERIAL_LITEUART = no;
        SERIAL_NUVOTON_MA35D1 = no;
        # SERIAL_RPI_FW = no;
        # end of Serial drivers

      })
    ];
  };
}
