{{- if eq .chezmoi.os "windows" }}

['.local/bin/oh-my-posh.exe']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v12.25.1/posh-windows-amd64.exe"
	executable = true

['.local/bin/nvim-win64']
	type="archive"
	url="https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip"
	stripComponents=1

['.local/bin/vim']
	type="archive"
	url="https://github.com/vim/vim-win32-installer/releases/download/v9.0.1050/gvim_9.0.1050_x64.zip"
	stripComponents=2

['.local/bin/winfetch.ps1']
	type = "file"
	url = "https://raw.githubusercontent.com/lptstr/winfetch/master/winfetch.ps1"
	executable = true


['.local/bin/gsudo']
	type="archive"
	url="https://github.com/gerardog/gsudo/releases/download/v2.0.4/gsudo.v2.0.4.zip"
	stripComponents = 1
	include=["x64/*"]

['.local/bin/btop']
	type="archive"
	url="https://github.com/aristocratos/btop4win/releases/download/v1.0.4/btop4win-LHM-x64.zip"
	stripComponents=1

{{- end }}


{{- if eq .chezmoi.os "linux" }}

['.local/bin/nvim.appimage']
	type = "file"
	url = "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
	executable = true

['.local/bin/oh-my-posh']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v12.25.1/posh-linux-amd64"
	executable = true

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1

{{- end }}

['.config/vim/autoload/plug.vim']
	type = "file"
	url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
