{{- if eq .chezmoi.os "windows" }}

['.devenv/cowsay']
	type = "archive"
	url = "https://github.com/lukesampson/cowsay-psh/archive/refs/heads/master.zip"
	exclude = ["**/.gitattributes", "**/.gitignore", "**/*.sublime-project", "**/.git", "**/README.md", "**/*.cow"]
	stripComponents = 1

['.devenv/bin/oh-my-posh.exe']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v7.59.4/posh-windows-amd64.exe"
	executable = true

['.devenv/bin']
	type = "archive"
	url="https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-pc-windows-msvc.zip"
	include = ['*/rg.exe']
	stripComponents = 1
['.devenv/bin/fd']
	type="archive"
	url="https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-pc-windows-msvc.zip"
	include = ['*/fd.exe']
	stripComponents = 1

['.devenv/bin/nvim-win64']
	type="archive"
	url="https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip"
	stripComponents=1 
{{- end }}


{{- if eq .chezmoi.os "linux" }}

['.devenv/bin/nvim.appimage']
	type = "file"
	url = "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
	executable = true

['.devenv/bin/oh-my-posh']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v7.59.4/posh-linux-amd64"
	executable = true

{{- end }}
