{{- if eq .chezmoi.os "windows" }}

['.local/bin/oh-my-posh.exe']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v8.37.1/posh-windows-amd64.exe"
	executable = true

['.local/bin']
	type = "archive"
	url="https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-pc-windows-msvc.zip"
	include = ['*/rg.exe']
	stripComponents = 1
['.local/bin/fd']
	type="archive"
	url="https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-pc-windows-msvc.zip"
	include = ['*/fd.exe']
	stripComponents = 1

['.local/bin/nvim-win64']
	type="archive"
	url="https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip"
	stripComponents=1
{{- end }}


{{- if eq .chezmoi.os "linux" }}

['.local/bin/nvim.appimage']
	type = "file"
	url = "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
	executable = true

['.local/bin/oh-my-posh']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v8.37.1/posh-linux-amd64"
	executable = true

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1



{{- end }}
