['Documents/Powershell/Scripts/cowsay']
	type = "archive"
	url = "https://github.com/lukesampson/cowsay-psh/archive/refs/heads/master.zip"
	exclude = [".gitattributes", ".gitignore", "*.sublime-project", ".git", "README.md"]
	stripComponents = 1

['.devenv/bin/oh-my-posh.exe']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v7.57.1/posh-windows-amd64.exe"
	executable = true

['.devenv/bin']
	type = "archive"
	url="https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-pc-windows-msvc.zip"
	include = ['*/rg.exe']
	stripComponents = 1
['devenv/bin']
	type="archive"
	url="https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-pc-windows-msvc.zip"
	include = ['*/fd.exe']
	stripComponents = 1