{{- if eq .chezmoi.os "windows" }}

['.local/bin/oh-my-posh.exe']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v21.16.2/posh-windows-amd64.exe"
	executable = true

['.local/bin/vim']
	type="archive"
	url="https://github.com/vim/vim-win32-installer/releases/download/v9.1.0516/gvim_9.1.0516_x64.zip"
	stripComponents=2

['.local/bin/winfetch.ps1']
	type = "file"
	url = "https://raw.githubusercontent.com/lptstr/winfetch/master/winfetch.ps1"
	executable = true

# ['.local/bin/gsudo']
# 	type="archive"
# 	url="https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.v2.5.1.zip"
# 	stripComponents = 1
# 	include=["x64/*"]

# ['.local/bin/btop']
# 	type="archive"
# 	url="https://github.com/aristocratos/btop4win/releases/download/v1.0.4/btop4win-LHM-x64.zip"
# 	stripComponents=1

['.local/bin']
	type="archive"
	url="https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-pc-windows-msvc.zip"
	stripComponents=1
	exclude=["*.md", "LICENSE-*"]
{{- end }}


{{- if eq .chezmoi.os "linux" }}

['.local/bin/oh-my-posh']
	type = "file"
	url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v21.16.2/posh-linux-amd64"
	executable = true

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
	exclude=['cache/**']
    stripComponents = 1

['.local/bin']
	type="archive"
	url="https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-unknown-linux-gnu.tar.gz"
	stripComponents=1
	exclude=["*.md", "LICENSE-*"]

{{- end }}

['.config/vim/autoload/plug.vim']
	type = "file"
	url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
