const layoutMapObj = {
	"Abkhazian (Russia)": "Ru (Ab)",
	Akan: "Gh (Akan)",
	Albanian: "Al",
	"Albanian (Plisi)": "Al (Plisi)",
	"Albanian (Veqilharxhi)": "Al (Veqilharxhi)",
	Amharic: "Et",
	Arabic: "Ara",
	"Arabic (Algeria)": "Dz (Ar)",
	"Arabic (AZERTY, Eastern Arabic numerals)": "Ara (Azerty Digits)",
	"Arabic (AZERTY)": "Ara (Azerty)",
	"Arabic (Buckwalter)": "Ara (Buckwalter)",
	"Arabic (Eastern Arabic numerals)": "Ara (Digits)",
	"Arabic (Macintosh)": "Ara (Mac)",
	"Arabic (Morocco)": "Ma",
	"Arabic (OLPC)": "Ara (Olpc)",
	"Arabic (Pakistan)": "Pk (Ara)",
	"Arabic (QWERTY, Eastern Arabic numerals)": "Ara (Qwerty Digits)",
	"Arabic (QWERTY)": "Ara (Qwerty)",
	"Arabic (Syria)": "Sy",
	Armenian: "Am",
	"Armenian (alt. eastern)": "Am (Eastern-Alt)",
	"Armenian (alt. phonetic)": "Am (Phonetic-Alt)",
	"Armenian (eastern)": "Am (Eastern)",
	"Armenian (phonetic)": "Am (Phonetic)",
	"Armenian (western)": "Am (Western)",
	"Asturian (Spain, with bottom-dot H and L)": "Es (Ast)",
	Avatime: "Gh (Avn)",
	Azerbaijani: "Az",
	"Azerbaijani (Cyrillic)": "Az (Cyrillic)",
	"Azerbaijani (Iran)": "Ir (Azb)",
	Bambara: "Ml",
	Bangla: "Bd",
	"Bangla (India, Baishakhi InScript)": "In (Ben Inscript)",
	"Bangla (India, Baishakhi)": "In (Ben Baishakhi)",
	"Bangla (India, Bornona)": "In (Ben Bornona)",
	"Bangla (India, Gitanjali)": "In (Ben Gitanjali)",
	"Bangla (India, Probhat)": "In (Ben Probhat)",
	"Bangla (India)": "In (Ben)",
	"Bangla (Probhat)": "Bd (Probhat)",
	Bashkirian: "Ru (Bak)",
	Belarusian: "By",
	"Belarusian (intl.)": "By (Intl)",
	"Belarusian (Latin)": "By (Latin)",
	"Belarusian (legacy)": "By (Legacy)",
	"Belarusian (phonetic)": "By (Phonetic)",
	Belgian: "Be",
	"Belgian (alt.)": "Be (Oss)",
	"Belgian (ISO, alt.)": "Be (Iso-Alternate)",
	"Belgian (Latin-9 only, alt.)": "Be (Oss Latin9)",
	"Belgian (no dead keys)": "Be (Nodeadkeys)",
	"Belgian (Wang 724 AZERTY)": "Be (Wang)",
	"Berber (Algeria, Latin)": "Dz",
	"Berber (Algeria, Tifinagh)": "Dz (Ber)",
	"Berber (Morocco, Tifinagh alt.)": "Ma (Tifinagh-Alt)",
	"Berber (Morocco, Tifinagh extended phonetic)":
		"Ma (Tifinagh-Extended-Phonetic)",
	"Berber (Morocco, Tifinagh extended)": "Ma (Tifinagh-Extended)",
	"Berber (Morocco, Tifinagh phonetic, alt.)": "Ma (Tifinagh-Alt-Phonetic)",
	"Berber (Morocco, Tifinagh phonetic)": "Ma (Tifinagh-Phonetic)",
	"Berber (Morocco, Tifinagh)": "Ma (Tifinagh)",
	Bosnian: "Ba",
	"Bosnian (US, with Bosnian digraphs)": "Ba (Unicodeus)",
	"Bosnian (US)": "Ba (Us)",
	"Bosnian (with Bosnian digraphs)": "Ba (Unicode)",
	"Bosnian (with guillemets)": "Ba (Alternatequotes)",
	Braille: "Brai",
	"Braille (left-handed inverted thumb)": "Brai (Left Hand Invert)",
	"Braille (left-handed)": "Brai (Left Hand)",
	"Braille (right-handed inverted thumb)": "Brai (Right Hand Invert)",
	"Braille (right-handed)": "Brai (Right Hand)",
	"Breton (France)": "Fr (Bre)",
	Bulgarian: "Bg",
	"Bulgarian (enhanced)": "Bg (Bekl)",
	"Bulgarian (new phonetic)": "Bg (Bas Phonetic)",
	"Bulgarian (traditional phonetic)": "Bg (Phonetic)",
	Burmese: "Mm",
	"Burmese Zawgyi": "Mm (Zawgyi)",
	"Cameroon (AZERTY, intl.)": "Cm (Azerty)",
	"Cameroon (Dvorak, intl.)": "Cm (Dvorak)",
	"Cameroon Multilingual (QWERTY, intl.)": "Cm (Qwerty)",
	"Canadian (CSA)": "Ca (Multix)",
	"Catalan (Spain, with middle-dot L)": "Es (Cat)",
	Cherokee: "Us (Chr)",
	Chinese: "Cn",
	Chuvash: "Ru (Cv)",
	"Chuvash (Latin)": "Ru (Cv Latin)",
	CloGaelach: "Ie (CloGaelach)",
	"Crimean Tatar (Turkish Alt-Q)": "Ua (Crh Alt)",
	"Crimean Tatar (Turkish F)": "Ua (Crh F)",
	"Crimean Tatar (Turkish Q)": "Ua (Crh)",
	Croatian: "Hr",
	"Croatian (US, with Croatian digraphs)": "Hr (Unicodeus)",
	"Croatian (US)": "Hr (Us)",
	"Croatian (with Croatian digraphs)": "Hr (Unicode)",
	"Croatian (with guillemets)": "Hr (Alternatequotes)",
	Czech: "Cz",
	"Czech (QWERTY, extended backslash)": "Cz (Qwerty Bksl)",
	"Czech (QWERTY, Macintosh)": "Cz (Qwerty-Mac)",
	"Czech (QWERTY)": "Cz (Qwerty)",
	"Czech (UCW, only accented letters)": "Cz (Ucw)",
	"Czech (US, Dvorak, UCW support)": "Cz (Dvorak-Ucw)",
	"Czech (with <\\|> key)": "Cz (Bksl)",
	Danish: "Dk",
	"Danish (Dvorak)": "Dk (Dvorak)",
	"Danish (Macintosh, no dead keys)": "Dk (Mac Nodeadkeys)",
	"Danish (Macintosh)": "Dk (Mac)",
	"Danish (no dead keys)": "Dk (Nodeadkeys)",
	"Danish (Windows)": "Dk (Winkeys)",
	Dari: "Af",
	"Dari (Afghanistan, OLPC)": "Af (Fa-Olpc)",
	Dhivehi: "Mv",
	Dutch: "Nl",
	"Dutch (Macintosh)": "Nl (Mac)",
	"Dutch (standard)": "Nl (Std)",
	"Dutch (US)": "Nl (Us)",
	Dzongkha: "Bt",
	"English (Australian)": "Au",
	"English (Cameroon)": "Cm",
	"English (Canada)": "Ca (Eng)",
	"English (classic Dvorak)": "Us (Dvorak-Classic)",
	"English (Colemak-DH ISO)": "Us (Colemak Dh Iso)",
	"English (Colemak-DH)": "Us (Colemak Dh)",
	"English (Colemak)": "Us (Colemak)",
	"English (Dvorak, alt. intl.)": "Us (Dvorak-Alt-Intl)",
	"English (Dvorak, intl., with dead keys)": "Us (Dvorak-Intl)",
	"English (Dvorak, left-handed)": "Us (Dvorak-L)",
	"English (Dvorak, Macintosh)": "Us (Dvorak-Mac)",
	"English (Dvorak, right-handed)": "Us (Dvorak-R)",
	"English (Dvorak)": "Us (Dvorak)",
	"English (Ghana, GILLBT)": "Gh (Gillbt)",
	"English (Ghana, multilingual)": "Gh (Generic)",
	"English (Ghana)": "Gh",
	"English (India, with rupee)": "In (Eng)",
	"English (intl., with AltGr dead keys)": "Us (Altgr-Intl)",
	"English (Macintosh)": "Us (Mac)",
	"English (Mali, US, intl.)": "Ml (Us-Intl)",
	"English (Mali, US, Macintosh)": "Ml (Us-Mac)",
	"English (Nigeria)": "Ng",
	"English (Norman)": "Us (Norman)",
	"English (programmer Dvorak)": "Us (Dvp)",
	"English (South Africa)": "Za",
	"English (the divide/multiply toggle the layout)": "Us (Olpc2)",
	"English (UK, Colemak-DH)": "Gb (Colemak Dh)",
	"English (UK, Colemak)": "Gb (Colemak)",
	"English (UK, Dvorak, with UK punctuation)": "Gb (Dvorakukp)",
	"English (UK, Dvorak)": "Gb (Dvorak)",
	"English (UK, extended, Windows)": "Gb (Extd)",
	"English (UK, intl., with dead keys)": "Gb (Intl)",
	"English (UK, Macintosh, intl.)": "Gb (Mac Intl)",
	"English (UK, Macintosh)": "Gb (Mac)",
	"English (UK)": "Gb",
	"English (US, alt. intl.)": "Us (Alt-Intl)",
	"English (US, euro on 5)": "Us (Euro)",
	"English (US, intl., with dead keys)": "Us (Intl)",
	"English (US, Symbolic)": "Us (Symbolic)",
	"English (US)": "Us",
	"English (Workman, intl., with dead keys)": "Us (Workman-Intl)",
	"English (Workman)": "Us (Workman)",
	Esperanto: "Epo",
	"Esperanto (Brazil, Nativo)": "Br (Nativo-Epo)",
	"Esperanto (legacy)": "Epo (Legacy)",
	"Esperanto (Portugal, Nativo)": "Pt (Nativo-Epo)",
	Estonian: "Ee",
	"Estonian (Dvorak)": "Ee (Dvorak)",
	"Estonian (no dead keys)": "Ee (Nodeadkeys)",
	"Estonian (US)": "Ee (Us)",
	Ewe: "Gh (Ewe)",
	Faroese: "Fo",
	"Faroese (no dead keys)": "Fo (Nodeadkeys)",
	Filipino: "Ph",
	"Filipino (Capewell-Dvorak, Baybayin)": "Ph (Capewell-Dvorak-Bay)",
	"Filipino (Capewell-Dvorak, Latin)": "Ph (Capewell-Dvorak)",
	"Filipino (Capewell-QWERF 2006, Baybayin)": "Ph (Capewell-Qwerf2k6-Bay)",
	"Filipino (Capewell-QWERF 2006, Latin)": "Ph (Capewell-Qwerf2k6)",
	"Filipino (Colemak, Baybayin)": "Ph (Colemak-Bay)",
	"Filipino (Colemak, Latin)": "Ph (Colemak)",
	"Filipino (Dvorak, Baybayin)": "Ph (Dvorak-Bay)",
	"Filipino (Dvorak, Latin)": "Ph (Dvorak)",
	"Filipino (QWERTY, Baybayin)": "Ph (Qwerty-Bay)",
	Finnish: "Fi",
	"Finnish (classic, no dead keys)": "Fi (Nodeadkeys)",
	"Finnish (classic)": "Fi (Classic)",
	"Finnish (Macintosh)": "Fi (Mac)",
	"Finnish (Windows)": "Fi (Winkeys)",
	French: "Fr",
	"French (alt., Latin-9 only)": "Fr (Oss Latin9)",
	"French (alt., no dead keys)": "Fr (Oss Nodeadkeys)",
	"French (alt.)": "Fr (Oss)",
	"French (AZERTY, AFNOR)": "Fr (Afnor)",
	"French (AZERTY)": "Fr (Azerty)",
	"French (BEPO, AFNOR)": "Fr (Bepo Afnor)",
	"French (BEPO, Latin-9 only)": "Fr (Bepo Latin9)",
	"French (BEPO)": "Fr (Bepo)",
	"French (Cameroon)": "Cm (French)",
	"French (Canada, Dvorak)": "Ca (Fr-Dvorak)",
	"French (Canada, legacy)": "Ca (Fr-Legacy)",
	"French (Canada)": "Ca",
	"French (Democratic Republic of the Congo)": "Cd",
	"French (Dvorak)": "Fr (Dvorak)",
	"French (legacy, alt., no dead keys)": "Fr (Latin9 Nodeadkeys)",
	"French (legacy, alt.)": "Fr (Latin9)",
	"French (Macintosh)": "Fr (Mac)",
	"French (Mali, alt.)": "Ml (Fr-Oss)",
	"French (Morocco)": "Ma (French)",
	"French (no dead keys)": "Fr (Nodeadkeys)",
	"French (Switzerland, Macintosh)": "Ch (Fr Mac)",
	"French (Switzerland, no dead keys)": "Ch (Fr Nodeadkeys)",
	"French (Switzerland)": "Ch (Fr)",
	"French (Togo)": "Tg",
	"French (US)": "Fr (Us)",
	"Friulian (Italy)": "It (Fur)",
	Fula: "Gh (Fula)",
	Ga: "Gh (Ga)",
	Georgian: "Ge",
	"Georgian (ergonomic)": "Ge (Ergonomic)",
	"Georgian (France, AZERTY Tskapo)": "Fr (Geo)",
	"Georgian (Italy)": "It (Geo)",
	"Georgian (MESS)": "Ge (Mess)",
	German: "De",
	"German (Austria, Macintosh)": "At (Mac)",
	"German (Austria, no dead keys)": "At (Nodeadkeys)",
	"German (Austria)": "At",
	"German (dead acute)": "De (Deadacute)",
	"German (dead grave acute)": "De (Deadgraveacute)",
	"German (dead tilde)": "De (Deadtilde)",
	"German (Dvorak)": "De (Dvorak)",
	"German (E1)": "De (E1)",
	"German (E2)": "De (E2)",
	"German (Macintosh, no dead keys)": "De (Mac Nodeadkeys)",
	"German (Macintosh)": "De (Mac)",
	"German (Neo 2)": "De (Neo)",
	"German (no dead keys)": "De (Nodeadkeys)",
	"German (QWERTY)": "De (Qwerty)",
	"German (Switzerland, legacy)": "Ch (Legacy)",
	"German (Switzerland, Macintosh)": "Ch (De Mac)",
	"German (Switzerland, no dead keys)": "Ch (De Nodeadkeys)",
	"German (Switzerland)": "Ch",
	"German (T3)": "De (T3)",
	"German (US)": "De (Us)",
	Greek: "Gr",
	"Greek (extended)": "Gr (Extended)",
	"Greek (no dead keys)": "Gr (Nodeadkeys)",
	"Greek (polytonic)": "Gr (Polytonic)",
	"Greek (simple)": "Gr (Simple)",
	Gujarati: "In (Guj)",
	"Hanyu Pinyin Letters (with AltGr dead keys)": "Cn (Altgr-Pinyin)",
	"Hausa (Ghana)": "Gh (Hausa)",
	"Hausa (Nigeria)": "Ng (Hausa)",
	Hawaiian: "Us (Haw)",
	Hebrew: "Il",
	"Hebrew (Biblical, Tiro)": "Il (Biblical)",
	"Hebrew (lyx)": "Il (Lyx)",
	"Hebrew (phonetic)": "Il (Phonetic)",
	"Hindi (Bolnagri)": "In (Bolnagri)",
	"Hindi (KaGaPa, phonetic)": "In (Hin-Kagapa)",
	"Hindi (Wx)": "In (Hin-Wx)",
	Hungarian: "Hu",
	"Hungarian (no dead keys)": "Hu (Nodeadkeys)",
	"Hungarian (QWERTY, 101-key, comma, dead keys)":
		"Hu (101 Qwerty Comma Dead)",
	"Hungarian (QWERTY, 101-key, comma, no dead keys)":
		"Hu (101 Qwerty Comma Nodead)",
	"Hungarian (QWERTY, 101-key, dot, dead keys)": "Hu (101 Qwerty Dot Dead)",
	"Hungarian (QWERTY, 101-key, dot, no dead keys)":
		"Hu (101 Qwerty Dot Nodead)",
	"Hungarian (QWERTY, 102-key, comma, dead keys)":
		"Hu (102 Qwerty Comma Dead)",
	"Hungarian (QWERTY, 102-key, comma, no dead keys)":
		"Hu (102 Qwerty Comma Nodead)",
	"Hungarian (QWERTY, 102-key, dot, dead keys)": "Hu (102 Qwerty Dot Dead)",
	"Hungarian (QWERTY, 102-key, dot, no dead keys)":
		"Hu (102 Qwerty Dot Nodead)",
	"Hungarian (QWERTY)": "Hu (Qwerty)",
	"Hungarian (QWERTZ, 101-key, comma, dead keys)":
		"Hu (101 Qwertz Comma Dead)",
	"Hungarian (QWERTZ, 101-key, comma, no dead keys)":
		"Hu (101 Qwertz Comma Nodead)",
	"Hungarian (QWERTZ, 101-key, dot, dead keys)": "Hu (101 Qwertz Dot Dead)",
	"Hungarian (QWERTZ, 101-key, dot, no dead keys)":
		"Hu (101 Qwertz Dot Nodead)",
	"Hungarian (QWERTZ, 102-key, comma, dead keys)":
		"Hu (102 Qwertz Comma Dead)",
	"Hungarian (QWERTZ, 102-key, comma, no dead keys)":
		"Hu (102 Qwertz Comma Nodead)",
	"Hungarian (QWERTZ, 102-key, dot, dead keys)": "Hu (102 Qwertz Dot Dead)",
	"Hungarian (QWERTZ, 102-key, dot, no dead keys)":
		"Hu (102 Qwertz Dot Nodead)",
	"Hungarian (standard)": "Hu (Standard)",
	Icelandic: "Is",
	"Icelandic (Dvorak)": "Is (Dvorak)",
	"Icelandic (Macintosh, legacy)": "Is (Mac Legacy)",
	"Icelandic (Macintosh)": "Is (Mac)",
	Igbo: "Ng (Igbo)",
	Indian: "In",
	"Indic IPA": "In (Iipa)",
	"Indonesian (Arab Melayu, extended phonetic)": "Id (Melayu-Phoneticx)",
	"Indonesian (Arab Melayu, phonetic)": "Id (Melayu-Phonetic)",
	"Indonesian (Arab Pegon, phonetic)": "Id (Pegon-Phonetic)",
	"Indonesian (Latin)": "Id",
	Inuktitut: "Ca (Ike)",
	Iraqi: "Iq",
	Irish: "Ie",
	"Irish (UnicodeExpert)": "Ie (UnicodeExpert)",
	Italian: "It",
	"Italian (IBM 142)": "It (Ibm)",
	"Italian (intl., with dead keys)": "It (Intl)",
	"Italian (Macintosh)": "It (Mac)",
	"Italian (no dead keys)": "It (Nodeadkeys)",
	"Italian (US)": "It (Us)",
	"Italian (Windows)": "It (Winkeys)",
	Japanese: "Jp",
	"Japanese (Dvorak)": "Jp (Dvorak)",
	"Japanese (Kana 86)": "Jp (Kana86)",
	"Japanese (Kana)": "Jp (Kana)",
	"Japanese (Macintosh)": "Jp (Mac)",
	"Japanese (OADG 109A)": "Jp (OADG109A)",
	Javanese: "Id (Javanese)",
	"Kabyle (AZERTY, with dead keys)": "Dz (Azerty-Deadkeys)",
	"Kabyle (QWERTY, UK, with dead keys)": "Dz (Qwerty-Gb-Deadkeys)",
	"Kabyle (QWERTY, US, with dead keys)": "Dz (Qwerty-Us-Deadkeys)",
	Kalmyk: "Ru (Xal)",
	Kannada: "In (Kan)",
	"Kannada (KaGaPa, phonetic)": "In (Kan-Kagapa)",
	Kashubian: "Pl (Csb)",
	Kazakh: "Kz",
	"Kazakh (extended)": "Kz (Ext)",
	"Kazakh (Latin)": "Kz (Latin)",
	"Kazakh (with Russian)": "Kz (Kazrus)",
	"Khmer (Cambodia)": "Kh",
	Kikuyu: "Ke (Kik)",
	Komi: "Ru (Kom)",
	Korean: "Kr",
	"Korean (101/104-key compatible)": "Kr (Kr104)",
	"Kurdish (Iran, Arabic-Latin)": "Ir (Ku Ara)",
	"Kurdish (Iran, F)": "Ir (Ku F)",
	"Kurdish (Iran, Latin Alt-Q)": "Ir (Ku Alt)",
	"Kurdish (Iran, Latin Q)": "Ir (Ku)",
	"Kurdish (Iraq, Arabic-Latin)": "Iq (Ku Ara)",
	"Kurdish (Iraq, F)": "Iq (Ku F)",
	"Kurdish (Iraq, Latin Alt-Q)": "Iq (Ku Alt)",
	"Kurdish (Iraq, Latin Q)": "Iq (Ku)",
	"Kurdish (Syria, F)": "Sy (Ku F)",
	"Kurdish (Syria, Latin Alt-Q)": "Sy (Ku Alt)",
	"Kurdish (Syria, Latin Q)": "Sy (Ku)",
	"Kurdish (Turkey, F)": "Tr (Ku F)",
	"Kurdish (Turkey, Latin Alt-Q)": "Tr (Ku Alt)",
	"Kurdish (Turkey, Latin Q)": "Tr (Ku)",
	Kyrgyz: "Kg",
	"Kyrgyz (phonetic)": "Kg (Phonetic)",
	Lao: "La",
	"Lao (STEA)": "La (Stea)",
	Latvian: "Lv",
	"Latvian (adapted)": "Lv (Adapted)",
	"Latvian (apostrophe)": "Lv (Apostrophe)",
	"Latvian (ergonomic, ÅªGJRMV)": "Lv (Ergonomic)",
	"Latvian (F)": "Lv (Fkey)",
	"Latvian (modern)": "Lv (Modern)",
	"Latvian (tilde)": "Lv (Tilde)",
	Lithuanian: "Lt",
	"Lithuanian (IBM LST 1205-92)": "Lt (Ibm)",
	"Lithuanian (LEKP)": "Lt (Lekp)",
	"Lithuanian (LEKPa)": "Lt (Lekpa)",
	"Lithuanian (Ratise)": "Lt (Ratise)",
	"Lithuanian (standard)": "Lt (Std)",
	"Lithuanian (US)": "Lt (Us)",
	"Lower Sorbian": "De (Dsb)",
	"Lower Sorbian (QWERTZ)": "De (Dsb Qwertz)",
	Macedonian: "Mk",
	"Macedonian (no dead keys)": "Mk (Nodeadkeys)",
	"Malay (Jawi, Arabic Keyboard)": "My",
	"Malay (Jawi, phonetic)": "My (Phonetic)",
	Malayalam: "In (Mal)",
	"Malayalam (enhanced InScript, with rupee)": "In (Mal Enhanced)",
	"Malayalam (Lalitha)": "In (Mal Lalitha)",
	Maltese: "Mt",
	"Maltese (UK, with AltGr overrides)": "Mt (Alt-Gb)",
	"Maltese (US, with AltGr overrides)": "Mt (Alt-Us)",
	"Maltese (US)": "Mt (Us)",
	"Manipuri (Eeyek)": "In (Eeyek)",
	Maori: "Mao",
	"Marathi (enhanced InScript)": "In (Marathi)",
	"Marathi (KaGaPa, phonetic)": "In (Mar-Kagapa)",
	Mari: "Ru (Chm)",
	Mmuock: "Cm (Mmuock)",
	Moldavian: "Md",
	"Moldavian (Gagauz)": "Md (Gag)",
	Mon: "Mm (Mnw)",
	"Mon (A1)": "Mm (Mnw-A1)",
	Mongolian: "Mn",
	"Mongolian (Bichig)": "Cn (Mon Trad)",
	"Mongolian (Galik)": "Cn (Mon Trad Galik)",
	"Mongolian (Manchu Galik)": "Cn (Mon Manchu Galik)",
	"Mongolian (Manchu)": "Cn (Mon Trad Manchu)",
	"Mongolian (Todo Galik)": "Cn (Mon Todo Galik)",
	"Mongolian (Todo)": "Cn (Mon Trad Todo)",
	"Mongolian (Xibe)": "Cn (Mon Trad Xibe)",
	Montenegrin: "Me",
	"Montenegrin (Cyrillic, with guillemets)": "Me (Cyrillicalternatequotes)",
	"Montenegrin (Cyrillic, ZE and ZHE swapped)": "Me (Cyrillicyz)",
	"Montenegrin (Cyrillic)": "Me (Cyrillic)",
	"Montenegrin (Latin, QWERTY)": "Me (Latinyz)",
	"Montenegrin (Latin, Unicode, QWERTY)": "Me (Latinunicodeyz)",
	"Montenegrin (Latin, Unicode)": "Me (Latinunicode)",
	"Montenegrin (Latin, with guillemets)": "Me (Latinalternatequotes)",
	"N'Ko (AZERTY)": "Gn",
	Nepali: "Np",
	"Northern Saami (Finland)": "Fi (Smi)",
	"Northern Saami (Norway, no dead keys)": "No (Smi Nodeadkeys)",
	"Northern Saami (Norway)": "No (Smi)",
	"Northern Saami (Sweden)": "Se (Smi)",
	Norwegian: "No",
	"Norwegian (Colemak)": "No (Colemak)",
	"Norwegian (Dvorak)": "No (Dvorak)",
	"Norwegian (Macintosh, no dead keys)": "No (Mac Nodeadkeys)",
	"Norwegian (Macintosh)": "No (Mac)",
	"Norwegian (no dead keys)": "No (Nodeadkeys)",
	"Norwegian (Windows)": "No (Winkeys)",
	Occitan: "Fr (Oci)",
	Ogham: "Ie (Ogam)",
	"Ogham (IS434)": "Ie (Ogam Is434)",
	"Ol Chiki": "In (Olck)",
	"Old Turkic": "Tr (Otk)",
	"Old Turkic (F)": "Tr (Otkf)",
	Oriya: "In (Ori)",
	"Oriya (Bolnagri)": "In (Ori-Bolnagri)",
	"Oriya (Wx)": "In (Ori-Wx)",
	"Ossetian (Georgia)": "Ge (Os)",
	"Ossetian (legacy)": "Ru (Os Legacy)",
	"Ossetian (Windows)": "Ru (Os Winkeys)",
	"Ottoman (F)": "Tr (Otf)",
	"Ottoman (Q)": "Tr (Ot)",
	"Pannonian Rusyn": "Rs (Rue)",
	Pashto: "Af (Ps)",
	"Pashto (Afghanistan, OLPC)": "Af (Ps-Olpc)",
	Persian: "Ir",
	"Persian (with Persian keypad)": "Ir (Pes Keypad)",
	Polish: "Pl",
	"Polish (British keyboard)": "Gb (Pl)",
	"Polish (Dvorak, with Polish quotes on key 1)": "Pl (Dvorak Altquotes)",
	"Polish (Dvorak, with Polish quotes on quotemark key)":
		"Pl (Dvorak Quotes)",
	"Polish (Dvorak)": "Pl (Dvorak)",
	"Polish (legacy)": "Pl (Legacy)",
	"Polish (programmer Dvorak)": "Pl (Dvp)",
	"Polish (QWERTZ)": "Pl (Qwertz)",
	Portuguese: "Pt",
	"Portuguese (Brazil, Dvorak)": "Br (Dvorak)",
	"Portuguese (Brazil, IBM/Lenovo ThinkPad)": "Br (Thinkpad)",
	"Portuguese (Brazil, Nativo for US keyboards)": "Br (Nativo-Us)",
	"Portuguese (Brazil, Nativo)": "Br (Nativo)",
	"Portuguese (Brazil, no dead keys)": "Br (Nodeadkeys)",
	"Portuguese (Brazil)": "Br",
	"Portuguese (Macintosh, no dead keys)": "Pt (Mac Nodeadkeys)",
	"Portuguese (Macintosh)": "Pt (Mac)",
	"Portuguese (Nativo for US keyboards)": "Pt (Nativo-Us)",
	"Portuguese (Nativo)": "Pt (Nativo)",
	"Portuguese (no dead keys)": "Pt (Nodeadkeys)",
	"Punjabi (Gurmukhi Jhelum)": "In (Jhelum)",
	"Punjabi (Gurmukhi)": "In (Guru)",
	Romanian: "Ro",
	"Romanian (Germany, no dead keys)": "De (Ro Nodeadkeys)",
	"Romanian (Germany)": "De (Ro)",
	"Romanian (standard)": "Ro (Std)",
	"Romanian (Windows)": "Ro (Winkeys)",
	Russian: "Ru",
	"Russian (Belarus)": "By (Ru)",
	"Russian (Czech, phonetic)": "Cz (Rus)",
	"Russian (DOS)": "Ru (Dos)",
	"Russian (engineering, EN)": "Ru (Ruchey En)",
	"Russian (engineering, RU)": "Ru (Ruchey Ru)",
	"Russian (Georgia)": "Ge (Ru)",
	"Russian (Germany, phonetic)": "De (Ru)",
	"Russian (Kazakhstan, with Kazakh)": "Kz (Ruskaz)",
	"Russian (legacy)": "Ru (Legacy)",
	"Russian (Macintosh)": "Ru (Mac)",
	"Russian (phonetic, AZERTY)": "Ru (Phonetic Azerty)",
	"Russian (phonetic, Dvorak)": "Ru (Phonetic Dvorak)",
	"Russian (phonetic, French)": "Ru (Phonetic Fr)",
	"Russian (phonetic, Windows)": "Ru (Phonetic Winkeys)",
	"Russian (phonetic, YAZHERTY)": "Ru (Phonetic YAZHERTY)",
	"Russian (phonetic)": "Ru (Phonetic)",
	"Russian (Poland, phonetic Dvorak)": "Pl (Ru Phonetic Dvorak)",
	"Russian (Sweden, phonetic, no dead keys)": "Se (Rus Nodeadkeys)",
	"Russian (Sweden, phonetic)": "Se (Rus)",
	"Russian (typewriter, legacy)": "Ru (Typewriter-Legacy)",
	"Russian (typewriter)": "Ru (Typewriter)",
	"Russian (Ukraine, standard RSTU)": "Ua (Rstu Ru)",
	"Russian (US, phonetic)": "Us (Rus)",
	"Saisiyat (Taiwan)": "Tw (Saisiyat)",
	Samogitian: "Lt (Sgs)",
	"Sanskrit (KaGaPa, phonetic)": "In (San-Kagapa)",
	"Scottish Gaelic": "Gb (Gla)",
	Serbian: "Rs",
	"Serbian (Cyrillic, with guillemets)": "Rs (Alternatequotes)",
	"Serbian (Cyrillic, ZE and ZHE swapped)": "Rs (Yz)",
	"Serbian (Latin, QWERTY)": "Rs (Latinyz)",
	"Serbian (Latin, Unicode, QWERTY)": "Rs (Latinunicodeyz)",
	"Serbian (Latin, Unicode)": "Rs (Latinunicode)",
	"Serbian (Latin, with guillemets)": "Rs (Latinalternatequotes)",
	"Serbian (Latin)": "Rs (Latin)",
	"Serbian (Russia)": "Ru (Srp)",
	"Serbo-Croatian (US)": "Us (Hbs)",
	Shan: "Mm (Shn)",
	"Shan (Zawgyi Tai)": "Mm (Zgt)",
	Sicilian: "It (Scn)",
	Silesian: "Pl (Szl)",
	Sindhi: "Pk (Snd)",
	"Sinhala (phonetic)": "Lk",
	"Sinhala (US)": "Lk (Us)",
	Slovak: "Sk",
	"Slovak (extended backslash)": "Sk (Bksl)",
	"Slovak (QWERTY, extended backslash)": "Sk (Qwerty Bksl)",
	"Slovak (QWERTY)": "Sk (Qwerty)",
	Slovenian: "Si",
	"Slovenian (US)": "Si (Us)",
	"Slovenian (with guillemets)": "Si (Alternatequotes)",
	Spanish: "Es",
	"Spanish (dead tilde)": "Es (Deadtilde)",
	"Spanish (Dvorak)": "Es (Dvorak)",
	"Spanish (Latin American, Colemak)": "Latam (Colemak)",
	"Spanish (Latin American, dead tilde)": "Latam (Deadtilde)",
	"Spanish (Latin American, Dvorak)": "Latam (Dvorak)",
	"Spanish (Latin American, no dead keys)": "Latam (Nodeadkeys)",
	"Spanish (Latin American)": "Latam",
	"Spanish (Macintosh)": "Es (Mac)",
	"Spanish (no dead keys)": "Es (Nodeadkeys)",
	"Spanish (Windows)": "Es (Winkeys)",
	"Swahili (Kenya)": "Ke",
	"Swahili (Tanzania)": "Tz",
	Swedish: "Se",
	"Swedish (Dvorak, intl.)": "Se (Us Dvorak)",
	"Swedish (Dvorak)": "Se (Dvorak)",
	"Swedish (Macintosh)": "Se (Mac)",
	"Swedish (no dead keys)": "Se (Nodeadkeys)",
	"Swedish (Svdvorak)": "Se (Svdvorak)",
	"Swedish (US)": "Se (Us)",
	"Swedish Sign Language": "Se (Swl)",
	Syriac: "Sy (Syc)",
	"Syriac (phonetic)": "Sy (Syc Phonetic)",
	Taiwanese: "Tw",
	"Taiwanese (indigenous)": "Tw (Indigenous)",
	Tajik: "Tj",
	"Tajik (legacy)": "Tj (Legacy)",
	"Tamil (InScript, with Arabic numerals)": "In (Tam)",
	"Tamil (InScript, with Tamil numerals)": "In (Tam Tamilnumbers)",
	"Tamil (Sri Lanka, TamilNet '99, TAB encoding)": "Lk (Tam TAB)",
	"Tamil (Sri Lanka, TamilNet '99)": "Lk (Tam Unicode)",
	"Tamil (TamilNet '99 with Tamil numerals)": "In (Tamilnet Tamilnumbers)",
	"Tamil (TamilNet '99, TAB encoding)": "In (Tamilnet TAB)",
	"Tamil (TamilNet '99, TSCII encoding)": "In (Tamilnet TSCII)",
	"Tamil (TamilNet '99)": "In (Tamilnet)",
	Tarifit: "Ma (Rif)",
	Tatar: "Ru (Tt)",
	Telugu: "In (Tel)",
	"Telugu (KaGaPa, phonetic)": "In (Tel-Kagapa)",
	"Telugu (Sarala)": "In (Tel-Sarala)",
	Thai: "Th",
	"Thai (Pattachote)": "Th (Pat)",
	"Thai (TIS-820.2538)": "Th (Tis)",
	Tibetan: "Cn (Tib)",
	"Tibetan (with ASCII numerals)": "Cn (Tib Asciinum)",
	Tswana: "Bw",
	Turkish: "Tr",
	"Turkish (Alt-Q)": "Tr (Alt)",
	"Turkish (E)": "Tr (E)",
	"Turkish (F)": "Tr (F)",
	"Turkish (Germany)": "De (Tr)",
	"Turkish (intl., with dead keys)": "Tr (Intl)",
	Turkmen: "Tm",
	"Turkmen (Alt-Q)": "Tm (Alt)",
	Udmurt: "Ru (Udm)",
	Ukrainian: "Ua",
	"Ukrainian (homophonic)": "Ua (Homophonic)",
	"Ukrainian (legacy)": "Ua (Legacy)",
	"Ukrainian (macOS)": "Ua (MacOS)",
	"Ukrainian (phonetic)": "Ua (Phonetic)",
	"Ukrainian (standard RSTU)": "Ua (Rstu)",
	"Ukrainian (typewriter)": "Ua (Typewriter)",
	"Ukrainian (Windows)": "Ua (Winkeys)",
	"Urdu (alt. phonetic)": "In (Urd-Phonetic3)",
	"Urdu (Pakistan, CRULP)": "Pk (Urd-Crulp)",
	"Urdu (Pakistan, NLA)": "Pk (Urd-Nla)",
	"Urdu (Pakistan)": "Pk",
	"Urdu (phonetic)": "In (Urd-Phonetic)",
	"Urdu (Windows)": "In (Urd-Winkeys)",
	Uyghur: "Cn (Ug)",
	Uzbek: "Uz",
	"Uzbek (Afghanistan, OLPC)": "Af (Uz-Olpc)",
	"Uzbek (Afghanistan)": "Af (Uz)",
	"Uzbek (Latin)": "Uz (Latin)",
	Vietnamese: "Vn",
	"Vietnamese (France)": "Vn (Fr)",
	"Vietnamese (US)": "Vn (Us)",
	Wolof: "Sn",
	Yakut: "Ru (Sah)",
	Yoruba: "Ng (Yoruba)",
	"Unknown Layout": "Unknown",
} as const;

export type LayoutKeys = keyof typeof layoutMapObj;
export type LayoutValues = (typeof layoutMapObj)[LayoutKeys];

export const layoutMap = layoutMapObj;
