[symlinks]
"bin/executable_sh-toy.exe" = "C:\\Users\\awest/.local/bin/sh-toy.exe"
"config/cowsay\\001_bulbasaur.cow" = "C:\\Users\\awest/.config/cowsay\\001_bulbasaur.cow"
"config/cowsay\\004_charmander.cow" = "C:\\Users\\awest/.config/cowsay\\004_charmander.cow"
"config/cowsay\\007_squirtle.cow" = "C:\\Users\\awest/.config/cowsay\\007_squirtle.cow"
"config/cowsay\\025_pikachu-alola-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-alola-cap.cow"
"config/cowsay\\025_pikachu-belle.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-belle.cow"
"config/cowsay\\025_pikachu-cosplay.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-cosplay.cow"
"config/cowsay\\025_pikachu-hoenn-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-hoenn-cap.cow"
"config/cowsay\\025_pikachu-kalos-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-kalos-cap.cow"
"config/cowsay\\025_pikachu-libre.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-libre.cow"
"config/cowsay\\025_pikachu-original-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-original-cap.cow"
"config/cowsay\\025_pikachu-partner-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-partner-cap.cow"
"config/cowsay\\025_pikachu-phd.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-phd.cow"
"config/cowsay\\025_pikachu-pop-star.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-pop-star.cow"
"config/cowsay\\025_pikachu-rock-star.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-rock-star.cow"
"config/cowsay\\025_pikachu-sinnoh-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-sinnoh-cap.cow"
"config/cowsay\\025_pikachu-starter.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-starter.cow"
"config/cowsay\\025_pikachu-unova-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-unova-cap.cow"
"config/cowsay\\025_pikachu-world-cap.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu-world-cap.cow"
"config/cowsay\\025_pikachu.cow" = "C:\\Users\\awest/.config/cowsay\\025_pikachu.cow"
"config/cowsay\\026_raichu-alola.cow" = "C:\\Users\\awest/.config/cowsay\\026_raichu-alola.cow"
"config/cowsay\\035_clefairy.cow" = "C:\\Users\\awest/.config/cowsay\\035_clefairy.cow"
"config/cowsay\\037_vulpix-alola.cow" = "C:\\Users\\awest/.config/cowsay\\037_vulpix-alola.cow"
"config/cowsay\\037_vulpix.cow" = "C:\\Users\\awest/.config/cowsay\\037_vulpix.cow"
"config/cowsay\\039_jigglypuff.cow" = "C:\\Users\\awest/.config/cowsay\\039_jigglypuff.cow"
"config/cowsay\\133_eevee-starter.cow" = "C:\\Users\\awest/.config/cowsay\\133_eevee-starter.cow"
"config/cowsay\\133_eevee.cow" = "C:\\Users\\awest/.config/cowsay\\133_eevee.cow"
"config/cowsay\\137_porygon.cow" = "C:\\Users\\awest/.config/cowsay\\137_porygon.cow"
"config/cowsay\\143_snorlax.cow" = "C:\\Users\\awest/.config/cowsay\\143_snorlax.cow"
"config/cowsay\\172_pichu-spiky-eared.cow" = "C:\\Users\\awest/.config/cowsay\\172_pichu-spiky-eared.cow"
"config/cowsay\\172_pichu.cow" = "C:\\Users\\awest/.config/cowsay\\172_pichu.cow"
"config/cowsay\\194_wooper.cow" = "C:\\Users\\awest/.config/cowsay\\194_wooper.cow"
"config/cowsay\\251_celebi.cow" = "C:\\Users\\awest/.config/cowsay\\251_celebi.cow"
"config/cowsay\\280_ralts.cow" = "C:\\Users\\awest/.config/cowsay\\280_ralts.cow"
"config/cowsay\\333_swablu.cow" = "C:\\Users\\awest/.config/cowsay\\333_swablu.cow"
"config/cowsay\\387_turtwig.cow" = "C:\\Users\\awest/.config/cowsay\\387_turtwig.cow"
"config/cowsay\\393_piplup.cow" = "C:\\Users\\awest/.config/cowsay\\393_piplup.cow"
"config/cowsay\\417_pachirisu.cow" = "C:\\Users\\awest/.config/cowsay\\417_pachirisu.cow"
"config/cowsay\\438_bonsly.cow" = "C:\\Users\\awest/.config/cowsay\\438_bonsly.cow"
"config/cowsay\\446_munchlax.cow" = "C:\\Users\\awest/.config/cowsay\\446_munchlax.cow"
"config/cowsay\\479_rotom-fan.cow" = "C:\\Users\\awest/.config/cowsay\\479_rotom-fan.cow"
"config/cowsay\\479_rotom-frost.cow" = "C:\\Users\\awest/.config/cowsay\\479_rotom-frost.cow"
"config/cowsay\\479_rotom-heat.cow" = "C:\\Users\\awest/.config/cowsay\\479_rotom-heat.cow"
"config/cowsay\\479_rotom-mow.cow" = "C:\\Users\\awest/.config/cowsay\\479_rotom-mow.cow"
"config/cowsay\\479_rotom-wash.cow" = "C:\\Users\\awest/.config/cowsay\\479_rotom-wash.cow"
"config/cowsay\\479_rotom.cow" = "C:\\Users\\awest/.config/cowsay\\479_rotom.cow"
"config/cowsay\\492_shaymin-sky.cow" = "C:\\Users\\awest/.config/cowsay\\492_shaymin-sky.cow"
"config/cowsay\\492_shaymin.cow" = "C:\\Users\\awest/.config/cowsay\\492_shaymin.cow"
"config/cowsay\\546_cottonee.cow" = "C:\\Users\\awest/.config/cowsay\\546_cottonee.cow"
"config/cowsay\\577_solosis.cow" = "C:\\Users\\awest/.config/cowsay\\577_solosis.cow"
"config/cowsay\\653_fennekin.cow" = "C:\\Users\\awest/.config/cowsay\\653_fennekin.cow"
"config/cowsay\\656_froakie.cow" = "C:\\Users\\awest/.config/cowsay\\656_froakie.cow"
"config/cowsay\\722_rowlet.cow" = "C:\\Users\\awest/.config/cowsay\\722_rowlet.cow"
"config/cowsay\\734_yungoos.cow" = "C:\\Users\\awest/.config/cowsay\\734_yungoos.cow"
"config/cowsay\\771_pyukumuku.cow" = "C:\\Users\\awest/.config/cowsay\\771_pyukumuku.cow"
"config/cowsay\\775_komala.cow" = "C:\\Users\\awest/.config/cowsay\\775_komala.cow"
"config/cowsay\\777_togedemaru.cow" = "C:\\Users\\awest/.config/cowsay\\777_togedemaru.cow"
"config/cowsay\\808_meltan.cow" = "C:\\Users\\awest/.config/cowsay\\808_meltan.cow"
"config/cowsay\\872_snom.cow" = "C:\\Users\\awest/.config/cowsay\\872_snom.cow"
"config/cowsay\\F_025_pikachu-alola-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-alola-cap.cow"
"config/cowsay\\F_025_pikachu-hoenn-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-hoenn-cap.cow"
"config/cowsay\\F_025_pikachu-kalos-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-kalos-cap.cow"
"config/cowsay\\F_025_pikachu-original-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-original-cap.cow"
"config/cowsay\\F_025_pikachu-partner-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-partner-cap.cow"
"config/cowsay\\F_025_pikachu-sinnoh-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-sinnoh-cap.cow"
"config/cowsay\\F_025_pikachu-starter.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-starter.cow"
"config/cowsay\\F_025_pikachu-unova-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-unova-cap.cow"
"config/cowsay\\F_025_pikachu-world-cap.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu-world-cap.cow"
"config/cowsay\\F_025_pikachu.cow" = "C:\\Users\\awest/.config/cowsay\\F_025_pikachu.cow"
"config/cowsay\\aperture.cow" = "C:\\Users\\awest/.config/cowsay\\aperture.cow"
"config/cowsay\\black-mesa.cow" = "C:\\Users\\awest/.config/cowsay\\black-mesa.cow"
"config/cowsay\\box.cow" = "C:\\Users\\awest/.config/cowsay\\box.cow"
"config/cowsay\\clippy.cow" = "C:\\Users\\awest/.config/cowsay\\clippy.cow"
"config/cowsay\\companion-cube.cow" = "C:\\Users\\awest/.config/cowsay\\companion-cube.cow"
"config/cowsay\\cube.cow" = "C:\\Users\\awest/.config/cowsay\\cube.cow"
"config/cowsay\\default.cow" = "C:\\Users\\awest/.config/cowsay\\default.cow"
"config/cowsay\\dragon-and-cow.cow" = "C:\\Users\\awest/.config/cowsay\\dragon-and-cow.cow"
"config/cowsay\\dragon.cow" = "C:\\Users\\awest/.config/cowsay\\dragon.cow"
"config/cowsay\\roflcopter.cow" = "C:\\Users\\awest/.config/cowsay\\roflcopter.cow"
"config/cowsay\\tux.cow" = "C:\\Users\\awest/.config/cowsay\\tux.cow"
"config/fortunes.txt" = "C:\\Users\\awest/.config/fortunes.txt"
"config/omp-theme.json" = "C:\\Users\\awest/.config/theme.omp.json"
"profile.ps1" = "C:\\Users\\awest/Onedrive/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[templates]
gitconfig = "C:\\Users\\awest/.gitconfig"
